// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCowboyRoundBetDetail = "cowboy_round_bet_detail"

// CowboyRoundBetDetail mapped from table <cowboy_round_bet_detail>
type CowboyRoundBetDetail struct {
	ID         int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Roomuuid   *uint64 `gorm:"column:roomuuid;type:bigint(20) unsigned;index:idx_cowboy_round_bet_detail_roomuuid,priority:1" json:"roomuuid"`
	HandNum    *int64  `gorm:"column:hand_num;type:bigint(20)" json:"hand_num"`
	UID        *uint32 `gorm:"column:uid;type:int(11) unsigned;index:idx_cowboy_round_bet_detail_uid,priority:1" json:"uid"`
	Name       *string `gorm:"column:name;type:varchar(255)" json:"name"`
	Option     *int32  `gorm:"column:option;type:int(11)" json:"option"`
	BetAmount  *uint64 `gorm:"column:bet_amount;type:bigint(20) unsigned" json:"bet_amount"`
	WinAmount  *int64  `gorm:"column:win_amount;type:bigint(20)" json:"win_amount"`
	RecordTime *int64  `gorm:"column:record_time;type:bigint(20);index:idx_cowboy_round_bet_detail_record_time,priority:1" json:"record_time"`
	AutoBet    *int32  `gorm:"column:auto_bet;type:int(11)" json:"auto_bet"`
	Gameuuid   *uint64 `gorm:"column:gameuuid;type:bigint(20) unsigned;index:idx_cowboy_round_bet_detail_gameuuid,priority:1" json:"gameuuid"`
}

// TableName CowboyRoundBetDetail's table name
func (*CowboyRoundBetDetail) TableName() string {
	return TableNameCowboyRoundBetDetail
}
