// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameEveryLevelGameCensu = "every_level_game_census"

// EveryLevelGameCensu 每日各级别牌局开桌统计
type EveryLevelGameCensu struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键id" json:"id"`                                             // 主键id
	NormalModel string  `gorm:"column:normal_model;type:text;not null;comment:普通局各级别开桌数，json格式" json:"normal_model"`                                     // 普通局各级别开桌数，json格式
	ShortModel  string  `gorm:"column:short_model;type:text;not null;comment:短牌局各级别开桌数，json格式" json:"short_model"`                                       // 短牌局各级别开桌数，json格式
	CensusTime  uint32  `gorm:"column:census_time;type:int(11) unsigned;not null;index:census_time,priority:1;comment:统计时间，统计日期的时间戳" json:"census_time"` // 统计时间，统计日期的时间戳
	CreateTime  uint32  `gorm:"column:create_time;type:int(11) unsigned;not null;index:create_time,priority:1;comment:创建时间" json:"create_time"`          // 创建时间
	Total       uint32  `gorm:"column:total;type:int(11) unsigned;not null;index:total,priority:1;comment:当日总牌局数" json:"total"`                          // 当日总牌局数
	NormalTotal uint32  `gorm:"column:normal_total;type:int(11) unsigned;not null;index:normal_total,priority:1;comment:当日普通局总局数" json:"normal_total"`   // 当日普通局总局数
	ShortTotal  uint32  `gorm:"column:short_total;type:int(11) unsigned;not null;index:short_total,priority:1;comment:当日短牌局总局数" json:"short_total"`      // 当日短牌局总局数
	SourceType  *uint32 `gorm:"column:source_type;type:int(11) unsigned;not null;default:2" json:"source_type"`
}

// TableName EveryLevelGameCensu's table name
func (*EveryLevelGameCensu) TableName() string {
	return TableNameEveryLevelGameCensu
}
