// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameGameCoinInventoryIncrDetail = "game_coin_inventory_incr_detail"

// GameCoinInventoryIncrDetail 小游戏币增发记录
type GameCoinInventoryIncrDetail struct {
	ID           uint64 `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:数据" json:"id"` // 数据
	ChangeTime   *int64 `gorm:"column:change_time;type:bigint(20);comment:时间" json:"change_time"`                      // 时间
	BeforeAmount *int64 `gorm:"column:before_amount;type:bigint(20)" json:"before_amount"`
	AfterAmount  *int64 `gorm:"column:after_amount;type:bigint(20)" json:"after_amount"`
	ChangeAmount *int64 `gorm:"column:change_amount;type:bigint(20)" json:"change_amount"`
}

// TableName GameCoinInventoryIncrDetail's table name
func (*GameCoinInventoryIncrDetail) TableName() string {
	return TableNameGameCoinInventoryIncrDetail
}
