// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePointOrderUserInfo = "point_order_user_info"

// PointOrderUserInfo 积分订单玩家记录
type PointOrderUserInfo struct {
	ID         uint64  `gorm:"column:id;type:bigint(20) unsigned;primaryKey;autoIncrement:true;comment:数据" json:"id"`             // 数据
	CreateTime *int64  `gorm:"column:create_time;type:bigint(20);index:idx_create_time,priority:1;comment:时间" json:"create_time"` // 时间
	Amount     *int64  `gorm:"column:amount;type:bigint(20);comment:金额" json:"amount"`                                            // 金额
	UserID     *uint32 `gorm:"column:user_id;type:int(11) unsigned;index:idx_user_id,priority:1" json:"user_id"`
	UserName   *string `gorm:"column:user_name;type:varchar(255)" json:"user_name"`
	OrderID    *uint64 `gorm:"column:order_id;type:bigint(20) unsigned;index:idx_order_id,priority:1" json:"order_id"`
	Desc       *string `gorm:"column:desc;type:varchar(255);comment:备注" json:"desc"` // 备注
}

// TableName PointOrderUserInfo's table name
func (*PointOrderUserInfo) TableName() string {
	return TableNamePointOrderUserInfo
}
