// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStrongboxBlacklist = "strongbox_blacklist"

// StrongboxBlacklist mapped from table <strongbox_blacklist>
type StrongboxBlacklist struct {
	ID            int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	UID           *uint32 `gorm:"column:uid;type:int(11) unsigned;index:idx_time_type,priority:1" json:"uid"`
	ChangeTime    *uint32 `gorm:"column:change_time;type:int(11) unsigned;index:idx_change_time,priority:1;index:idx_time_type,priority:2" json:"change_time"`
	ClubID        *uint32 `gorm:"column:club_id;type:int(11) unsigned" json:"club_id"`
	RoomID        *uint32 `gorm:"column:room_id;type:int(11) unsigned;index:idx_item_202009_room_id,priority:1" json:"room_id"`
	RoleName      *string `gorm:"column:role_name;type:varchar(255)" json:"role_name"`
	ChangeChannel *uint32 `gorm:"column:change_channel;type:int(11) unsigned;index:idx_time_type,priority:3" json:"change_channel"`
	CurrencyType  *uint32 `gorm:"column:currency_type;type:int(11) unsigned" json:"currency_type"`
	SourceType    *uint32 `gorm:"column:source_type;type:int(11) unsigned" json:"source_type"`
	ChangeAmount  *int64  `gorm:"column:change_amount;type:bigint(20)" json:"change_amount"`
	OrderID       *string `gorm:"column:order_id;type:varchar(255)" json:"order_id"`
	Param1        *int64  `gorm:"column:param1;type:bigint(20)" json:"param1"`
	Param2        *int64  `gorm:"column:param2;type:bigint(20)" json:"param2"`
	Param3        *int64  `gorm:"column:param3;type:bigint(20)" json:"param3"`
	Desc          *string `gorm:"column:desc;type:varchar(255)" json:"desc"`
	RoomName      *string `gorm:"column:room_name;type:varchar(255)" json:"room_name"`
	RecordTime    *int64  `gorm:"column:record_time;type:bigint(20)" json:"record_time"`
	Mode          *int32  `gorm:"column:mode;type:int(11);default:1" json:"mode"`
	Blind         *int32  `gorm:"column:blind;type:int(11)" json:"blind"`
	Ante          *int64  `gorm:"column:ante;type:bigint(20)" json:"ante"`
}

// TableName StrongboxBlacklist's table name
func (*StrongboxBlacklist) TableName() string {
	return TableNameStrongboxBlacklist
}
