// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUIDClubChange = "uid_club_change"

// UIDClubChange mapped from table <uid_club_change>
type UIDClubChange struct {
	ID             uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID            *uint32 `gorm:"column:uid;type:int(11) unsigned;index:idx_uid_change_time,priority:1" json:"uid"`
	OldFirstClubid *uint32 `gorm:"column:old_first_clubid;type:int(11) unsigned" json:"old_first_clubid"`
	NewFirstClubid *uint32 `gorm:"column:new_first_clubid;type:int(11) unsigned" json:"new_first_clubid"`
	ChangeTime     *uint32 `gorm:"column:change_time;type:int(11) unsigned;index:idx_uid_change_time,priority:2" json:"change_time"`
}

// TableName UIDClubChange's table name
func (*UIDClubChange) TableName() string {
	return TableNameUIDClubChange
}
