// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoboyRoomMoneyDaily = "videoboy_room_money_daily"

// VideoboyRoomMoneyDaily mapped from table <videoboy_room_money_daily>
type VideoboyRoomMoneyDaily struct {
	ID             int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	RecordTime     *int64  `gorm:"column:record_time;type:bigint(20);index:idx_roomid_uuid,priority:1" json:"record_time"`
	Roomuuid       *uint64 `gorm:"column:roomuuid;type:bigint(20) unsigned;index:idx_roomid_uuid,priority:2" json:"roomuuid"`
	HandNum        *uint64 `gorm:"column:hand_num;type:bigint(20) unsigned" json:"hand_num"`
	RoomLevel      *int32  `gorm:"column:room_level;type:int(11)" json:"room_level"`
	TotalBet       *uint64 `gorm:"column:total_bet;type:bigint(20) unsigned" json:"total_bet"`
	SysWin         *int64  `gorm:"column:sys_win;type:bigint(20)" json:"sys_win"`
	CurrTime       *int64  `gorm:"column:curr_time;type:bigint(20);index:idx_roomid_uuid,priority:3" json:"curr_time"`
	OptionHitTotal *string `gorm:"column:option_hit_total;type:varchar(1024)" json:"option_hit_total"`
}

// TableName VideoboyRoomMoneyDaily's table name
func (*VideoboyRoomMoneyDaily) TableName() string {
	return TableNameVideoboyRoomMoneyDaily
}
