// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBingoRecordCache = "bingo_record_cache"

// BingoRecordCache 抽奖中奖玩家表临时数据表
type BingoRecordCache struct {
	ID        uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	LastMaxID int32  `gorm:"column:last_max_id;type:int(11);not null;comment:抽奖中奖玩家表记录最后一条记录的id" json:"last_max_id"` // 抽奖中奖玩家表记录最后一条记录的id
}

// TableName BingoRecordCache's table name
func (*BingoRecordCache) TableName() string {
	return TableNameBingoRecordCache
}
