// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbErrorReport = "dtb_error_report"

// DtbErrorReport 错误奔溃报告表
type DtbErrorReport struct {
	ID             uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:id" json:"id"`                                       // id
	UID            int32   `gorm:"column:uid;type:int(11);not null;comment:用户id" json:"uid"`                                                                 // 用户id
	DeviceType     *string `gorm:"column:device_type;type:varchar(30);not null;default:1;comment:设备类型" json:"device_type"`                                   // 设备类型
	DeviceVersion  string  `gorm:"column:device_version;type:varchar(32);not null;comment:设备版本号" json:"device_version"`                                      // 设备版本号
	DeviceUUID     string  `gorm:"column:device_uuid;type:varchar(100);not null;comment:设备版本号" json:"device_uuid"`                                           // 设备版本号
	ClientType     *int32  `gorm:"column:client_type;type:tinyint(4);not null;default:1;comment:客户端类型 1常规 2海外 3H5常规 4H5海外 5WEB常规 6WEB海外" json:"client_type"` // 客户端类型 1常规 2海外 3H5常规 4H5海外 5WEB常规 6WEB海外
	ClientVersion  string  `gorm:"column:client_version;type:varchar(32);not null;comment:客户端版本号" json:"client_version"`                                     // 客户端版本号
	ClientLanguage string  `gorm:"column:client_language;type:varchar(32);not null;comment:客户端语言" json:"client_language"`                                    // 客户端语言
	ReportInfo     string  `gorm:"column:report_info;type:varchar(2048);not null;comment:报告信息" json:"report_info"`                                           // 报告信息
	ReportTime     uint32  `gorm:"column:report_time;type:int(11) unsigned;not null;comment:报告时间" json:"report_time"`                                        // 报告时间
}

// TableName DtbErrorReport's table name
func (*DtbErrorReport) TableName() string {
	return TableNameDtbErrorReport
}
