// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbUserDeleteLog = "dtb_user_delete_log"

// DtbUserDeleteLog 删除账号日志
type DtbUserDeleteLog struct {
	ID           uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Username     *string `gorm:"column:username;type:varchar(32)" json:"username"`
	ClientType   int32   `gorm:"column:client_type;type:tinyint(4);not null" json:"client_type"`
	DeviceType   int32   `gorm:"column:device_type;type:tinyint(4);not null" json:"device_type"`
	DeviceUUID   string  `gorm:"column:device_uuid;type:varchar(64);not null" json:"device_uuid"`
	IP           string  `gorm:"column:ip;type:varchar(40);not null" json:"ip"`
	APIErrorCode *int32  `gorm:"column:api_error_code;type:int(11);comment:紀錄接口 error_code; 0: 成功, 其他為失敗" json:"api_error_code"` // 紀錄接口 error_code; 0: 成功, 其他為失敗
	APIErrorMsg  *string `gorm:"column:api_error_msg;type:varchar(255);comment:记录接口错误讯息" json:"api_error_msg"`                   // 记录接口错误讯息
	CreatedAt    int32   `gorm:"column:created_at;type:int(11);not null" json:"created_at"`
}

// TableName DtbUserDeleteLog's table name
func (*DtbUserDeleteLog) TableName() string {
	return TableNameDtbUserDeleteLog
}
