// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbRegisterIPLog = "dtb_register_ip_log"

// DtbRegisterIPLog mapped from table <dtb_register_ip_log>
type DtbRegisterIPLog struct {
	ID         int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	RegIP      *string `gorm:"column:reg_ip;type:varchar(15);comment:IP" json:"reg_ip"`                           // IP
	Num        *uint32 `gorm:"column:num;type:tinyint(4) unsigned;not null;default:2;comment:当天剩余注册数" json:"num"` // 当天剩余注册数
	CreateTime uint32  `gorm:"column:create_time;type:int(11) unsigned;not null;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime uint32  `gorm:"column:update_time;type:int(11) unsigned;not null;comment:修改时间" json:"update_time"` // 修改时间
}

// TableName DtbRegisterIPLog's table name
func (*DtbRegisterIPLog) TableName() string {
	return TableNameDtbRegisterIPLog
}
