// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbCowRoomOrder = "dtb_cow_room_order"

// DtbCowRoomOrder 德州牛仔房间审核表
type DtbCowRoomOrder struct {
	ID         int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:id" json:"id"`                                                                                       // id
	CID        uint32  `gorm:"column:c_id;type:int(11) unsigned;not null;comment:创建人id" json:"c_id"`                                                                                            // 创建人id
	AdminID    uint32  `gorm:"column:admin_id;type:int(11) unsigned;not null;comment:审核人id" json:"admin_id"`                                                                                    // 审核人id
	Status     bool    `gorm:"column:status;type:tinyint(1);not null;index:status,priority:1;comment:状态 0草稿箱 1审核中、 2通过、 3驳回、 删除（通过状态除外记录，物理删除数据库记录；通过状态记录的调接口删除牛仔房间然后执行数据库物理删除）" json:"status"` // 状态 0草稿箱 1审核中、 2通过、 3驳回、 删除（通过状态除外记录，物理删除数据库记录；通过状态记录的调接口删除牛仔房间然后执行数据库物理删除）
	Reason     string  `gorm:"column:reason;type:varchar(80);not null;comment:驳回理由" json:"reason"`                                                                                              // 驳回理由
	CowRoomCfg string  `gorm:"column:cow_room_cfg;type:text;not null;comment:德州牛仔房间参数" json:"cow_room_cfg"`                                                                                     // 德州牛仔房间参数
	Roomuuid   *string `gorm:"column:roomuuid;type:varchar(50);not null;default:0;comment:德州牛仔房间roomuuid" json:"roomuuid"`                                                                      // 德州牛仔房间roomuuid
	MState     *bool   `gorm:"column:m_state;type:tinyint(1);not null;default:1;comment:状态 0开启 1关闭" json:"m_state"`                                                                             // 状态 0开启 1关闭
	CreateTime uint32  `gorm:"column:create_time;type:int(11) unsigned;not null;index:create_time,priority:1;comment:创建时间" json:"create_time"`                                                  // 创建时间
	UpdateTime uint32  `gorm:"column:update_time;type:int(11) unsigned;not null;comment:修改时间" json:"update_time"`                                                                               // 修改时间
}

// TableName DtbCowRoomOrder's table name
func (*DtbCowRoomOrder) TableName() string {
	return TableNameDtbCowRoomOrder
}
