// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbLamp = "dtb_lamp"

// DtbLamp 跑马灯信息数据表
type DtbLamp struct {
	ID           int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键id" json:"id"`                                      // 主键id
	PlayNum      *int32  `gorm:"column:play_num;type:int(11);not null;default:1;comment:播放次数" json:"play_num"`                                     // 播放次数
	Content      *string `gorm:"column:content;type:text;comment:跑马灯内容" json:"content"`                                                            // 跑马灯内容
	PublicType   *int32  `gorm:"column:public_type;type:tinyint(4);not null;default:1;comment:发布时间类型:1即时;2定时" json:"public_type"`                  // 发布时间类型:1即时;2定时
	PublicTime   int32   `gorm:"column:public_time;type:int(11);not null;index:idx_public_time,priority:1;comment:发布时间" json:"public_time"`        // 发布时间
	FinishTime   *int32  `gorm:"column:finish_time;type:int(11);index:idx_finish_time,priority:1;comment:完成时间" json:"finish_time"`                 // 完成时间
	SendInterval *int32  `gorm:"column:send_interval;type:int(11);comment:发送间隔" json:"send_interval"`                                              // 发送间隔
	CreatedTime  int32   `gorm:"column:created_time;type:int(11);not null;comment:创建时间" json:"created_time"`                                       // 创建时间
	UpdatedTime  int32   `gorm:"column:updated_time;type:int(11);not null;comment:修改时间" json:"updated_time"`                                       // 修改时间
	Status       int32   `gorm:"column:status;type:tinyint(4);not null;index:status,priority:1;comment:跑马灯状态:1已发布;0未发布,2撤回" json:"status"`         // 跑马灯状态:1已发布;0未发布,2撤回
	Type         string  `gorm:"column:type;type:varchar(100);not null;comment:跑马灯范围:1大厅、2德州、10德州牛仔、20必下局、30百人德州、40急速德州、50视频牛仔、60必下局" json:"type"` // 跑马灯范围:1大厅、2德州、10德州牛仔、20必下局、30百人德州、40急速德州、50视频牛仔、60必下局
	Lobby        *int32  `gorm:"column:lobby;type:tinyint(4);not null;default:1;comment:大厅是否发跑马灯:1是、0否；type为0和1时，该字段必填是" json:"lobby"`             // 大厅是否发跑马灯:1是、0否；type为0和1时，该字段必填是
	PublishType  *uint32 `gorm:"column:publish_type;type:int(11) unsigned;default:1;comment:发布范围是否支持多游戏：1只支持单个游戏、2支持多游戏" json:"publish_type"`      // 发布范围是否支持多游戏：1只支持单个游戏、2支持多游戏
}

// TableName DtbLamp's table name
func (*DtbLamp) TableName() string {
	return TableNameDtbLamp
}
