// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbEmail = "dtb_email"

// DtbEmail 邮件数据表
type DtbEmail struct {
	ID                  int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键id" json:"id"`                                                                                  // 主键id
	MailReceiverID      *int32  `gorm:"column:mail_receiver_id;type:int(11);not null;index:mail_receiver_id,priority:1;default:1;comment:接受者uid，关联表dtb_user_main，非0，公告接受者为1" json:"mail_receiver_id"` // 接受者uid，关联表dtb_user_main，非0，公告接受者为1
	MailType            *int32  `gorm:"column:mail_type;type:tinyint(4);not null;index:mail_type,priority:1;default:1;comment:邮件类型:1邮件;2需要及时弹出的公告;3不需要及时弹出的公告" json:"mail_type"`                      // 邮件类型:1邮件;2需要及时弹出的公告;3不需要及时弹出的公告
	MailStatus          *int32  `gorm:"column:mail_status;type:tinyint(4);not null;index:mail_status,priority:1;default:1;comment:邮件状态:1已读;2未读" json:"mail_status"`                                   // 邮件状态:1已读;2未读
	MailTitle           *string `gorm:"column:mail_title;type:text;comment:邮件标题" json:"mail_title"`                                                                                                   // 邮件标题
	MailSenderID        *int32  `gorm:"column:mail_sender_id;type:int(11);not null;index:mail_sender_id,priority:1;default:1;comment:发送者uid，关联表dtb_user_main" json:"mail_sender_id"`                  // 发送者uid，关联表dtb_user_main
	MailAppellation     string  `gorm:"column:mail_appellation;type:varchar(150);not null;comment:邮件抬头" json:"mail_appellation"`                                                                      // 邮件抬头
	MailContent         *string `gorm:"column:mail_content;type:text;comment:邮件内容" json:"mail_content"`                                                                                               // 邮件内容
	MailInscribe        *string `gorm:"column:mail_inscribe;type:text;comment:邮件签名" json:"mail_inscribe"`                                                                                             // 邮件签名
	MailSendTime        int32   `gorm:"column:mail_send_time;type:int(11);not null;index:mail_send_time,priority:1;comment:邮件发送时间，时间戳" json:"mail_send_time"`                                         // 邮件发送时间，时间戳
	MailExpiredtime     int32   `gorm:"column:mail_expiredtime;type:int(11);not null;comment:失效时间，时间戳" json:"mail_expiredtime"`                                                                       // 失效时间，时间戳
	CreateTime          int32   `gorm:"column:create_time;type:int(11);not null;index:create_time,priority:1;comment:邮件创建时间，时间戳" json:"create_time"`                                                  // 邮件创建时间，时间戳
	IsDraft             *int32  `gorm:"column:is_draft;type:tinyint(4);not null;default:1;comment:是否草稿:1草稿;0非草稿" json:"is_draft"`                                                                     // 是否草稿:1草稿;0非草稿
	IsCallback          int32   `gorm:"column:is_callback;type:tinyint(4);not null;comment:是否撤回:1已撤回;0未撤回" json:"is_callback"`                                                                        // 是否撤回:1已撤回;0未撤回
	IsTiming            int32   `gorm:"column:is_timing;type:tinyint(4);not null;comment:是否定时邮件:1是;0否" json:"is_timing"`                                                                              // 是否定时邮件:1是;0否
	SystemID            uint32  `gorm:"column:system_id;type:int(11) unsigned;not null;comment:操作人id" json:"system_id"`                                                                               // 操作人id
	SystemName          string  `gorm:"column:system_name;type:varchar(100);not null;comment:操作人账号" json:"system_name"`                                                                               // 操作人账号
	IsGroup             int32   `gorm:"column:is_group;type:tinyint(4);not null;comment:是否群发：0不是 1是" json:"is_group"`                                                                                 // 是否群发：0不是 1是
	MailReceiverList    *string `gorm:"column:mail_receiver_list;type:mediumtext;comment:群发邮件收件人列表" json:"mail_receiver_list"`                                                                        // 群发邮件收件人列表
	IsTpl               int32   `gorm:"column:is_tpl;type:tinyint(4);not null;comment:是否模板:1是 0否" json:"is_tpl"`                                                                                      // 是否模板:1是 0否
	MailSenderName      *string `gorm:"column:mail_sender_name;type:varchar(255);not null;default:管理员;comment:发件人昵称" json:"mail_sender_name"`                                                         // 发件人昵称
	MailRealID          int32   `gorm:"column:mail_real_id;type:int(11);not null;comment:邮件真实ID" json:"mail_real_id"`                                                                                 // 邮件真实ID
	MailCopy            *string `gorm:"column:mail_copy;type:text;comment:邮件可复制项" json:"mail_copy"`                                                                                                   // 邮件可复制项
	MailContentReserved *string `gorm:"column:mail_content_reserved;type:text;comment:邮件内容1" json:"mail_content_reserved"`                                                                            // 邮件内容1
	MailTplID           *int32  `gorm:"column:mail_tpl_id;type:int(11);comment:模板ID" json:"mail_tpl_id"`                                                                                              // 模板ID
}

// TableName DtbEmail's table name
func (*DtbEmail) TableName() string {
	return TableNameDtbEmail
}
