// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbUserSm = "dtb_user_sms"

// DtbUserSm 用户发送短信表
type DtbUserSm struct {
	ID         uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UserID     *uint32 `gorm:"column:user_id;type:int(11) unsigned;comment:用户编号" json:"user_id"`                                                   // 用户编号
	ClubID     *uint32 `gorm:"column:club_id;type:int(11) unsigned;comment:俱乐部ID" json:"club_id"`                                                  // 俱乐部ID
	AreaCode   *string `gorm:"column:areaCode;type:varchar(10);index:idx_dus_mobile_areacode,priority:2;comment:国家区号" json:"areaCode"`             // 国家区号
	Mobile     *string `gorm:"column:mobile;type:varchar(255);index:idx_dus_mobile_areacode,priority:1;comment:手机号" json:"mobile"`                 // 手机号
	Msg        *string `gorm:"column:msg;type:text;comment:短信内容" json:"msg"`                                                                       // 短信内容
	VCode      *string `gorm:"column:v_code;type:varchar(20);comment:用于手机验证的验证码" json:"v_code"`                                                    // 用于手机验证的验证码
	ClientType *uint32 `gorm:"column:client_type;type:tinyint(4) unsigned;not null;default:1;comment:客户端类型 1常规 2海外 3H5" json:"client_type"`        // 客户端类型 1常规 2海外 3H5
	Channel    *uint32 `gorm:"column:channel;type:tinyint(4) unsigned;not null;default:1;comment:通道类型" json:"channel"`                             // 通道类型
	SendCode   *uint32 `gorm:"column:send_code;type:tinyint(4) unsigned;not null;default:1;comment:发送类型 1APP 2后台" json:"send_code"`                // 发送类型 1APP 2后台
	Stype      *uint32 `gorm:"column:stype;type:tinyint(4) unsigned;default:1;comment:发送类型  1注册验证，2找回密码，3解除绑定手机号，4重新绑定手机号,8玩家后台找回密码" json:"stype"` // 发送类型  1注册验证，2找回密码，3解除绑定手机号，4重新绑定手机号,8玩家后台找回密码
	ReturnCode *int32  `gorm:"column:return_code;type:int(11);comment:返回状态码 0成功 1错误" json:"return_code"`                                           // 返回状态码 0成功 1错误
	VStatus    *uint32 `gorm:"column:v_status;type:tinyint(4) unsigned;comment:验证状态" json:"v_status"`                                              // 验证状态
	IsDelete   *uint32 `gorm:"column:is_delete;type:tinyint(4) unsigned;comment:是否删除:0:未删除 1:已删除" json:"is_delete"`                                // 是否删除:0:未删除 1:已删除
	AddTime    *uint32 `gorm:"column:add_time;type:int(11) unsigned;comment:添加时间" json:"add_time"`                                                 // 添加时间
	AddIP      string  `gorm:"column:add_ip;type:varchar(25);not null;comment:IP" json:"add_ip"`                                                   // IP
	SendType   *int32  `gorm:"column:send_type;type:tinyint(4);not null;default:1;comment:发送类别 1短信 2私聊" json:"send_type"`                          // 发送类别 1短信 2私聊
}

// TableName DtbUserSm's table name
func (*DtbUserSm) TableName() string {
	return TableNameDtbUserSm
}
