// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameHelpWrapRecord = "help_wrap_record"

// HelpWrapRecord mapped from table <help_wrap_record>
type HelpWrapRecord struct {
	BingoID uint64 `gorm:"column:bingo_id;type:bigint(20) unsigned;primaryKey;comment:抽奖记录表id" json:"bingo_id"` // 抽奖记录表id
	Code    *int32 `gorm:"column:code;type:int(11);uniqueIndex:code,priority:1;comment:验证码" json:"code"`        // 验证码
}

// TableName HelpWrapRecord's table name
func (*HelpWrapRecord) TableName() string {
	return TableNameHelpWrapRecord
}
