// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLotteryConfig = "lottery_config"

// LotteryConfig 抽奖配置数据表
type LotteryConfig struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键id" json:"id"`                                               // 主键id
	PacketValue uint32  `gorm:"column:packet_value;type:int(11) unsigned;not null;comment:红包价值，单位分" json:"packet_value"`                                   // 红包价值，单位分
	PacketNum   uint32  `gorm:"column:packet_num;type:int(11) unsigned;not null;comment:红包总数量" json:"packet_num"`                                          // 红包总数量
	LotteryNum  uint32  `gorm:"column:lottery_num;type:int(11) unsigned;not null;comment:已发送的红包数量" json:"lottery_num"`                                     // 已发送的红包数量
	RuleCfg     *string `gorm:"column:rule_cfg;type:text;comment:牌局等级参数和手数范围条件，json格式" json:"rule_cfg"`                                                    // 牌局等级参数和手数范围条件，json格式
	Percent     *bool   `gorm:"column:percent;type:tinyint(1);not null;default:80;comment:百分比，80%红包发给满足game_hand的玩家" json:"percent"`                       // 百分比，80%红包发给满足game_hand的玩家
	AdminName   *string `gorm:"column:admin_name;type:varchar(30);comment:操作人账号名" json:"admin_name"`                                                       // 操作人账号名
	Status      *int32  `gorm:"column:status;type:tinyint(4);not null;index:status,priority:1;default:1;comment:状态：1禁用、2启用、3已发完。启用状态配置只有一条" json:"status"` // 状态：1禁用、2启用、3已发完。启用状态配置只有一条
	CreateTime  uint32  `gorm:"column:create_time;type:int(11) unsigned;not null;index:create_time,priority:1;comment:创建时间" json:"create_time"`            // 创建时间
	UpdateTime  uint32  `gorm:"column:update_time;type:int(11) unsigned;not null;comment:更新时间" json:"update_time"`                                         // 更新时间
}

// TableName LotteryConfig's table name
func (*LotteryConfig) TableName() string {
	return TableNameLotteryConfig
}
