// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMemeSystemBase = "meme_system_base"

// MemeSystemBase 系统-字典
type MemeSystemBase struct {
	ID        int64      `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	Type      *string    `gorm:"column:type;type:varchar(20);index:idx_system_base_type,priority:1;comment:数据类型" json:"type"`  // 数据类型
	Code      *string    `gorm:"column:code;type:varchar(50);index:idx_system_base_code,priority:1;comment:数据代码" json:"code"`  // 数据代码
	Name      *string    `gorm:"column:name;type:varchar(200);index:idx_system_base_name,priority:1;comment:数据名称" json:"name"` // 数据名称
	Content   *string    `gorm:"column:content;type:text;comment:数据内容" json:"content"`                                         // 数据内容
	Sort      *int64     `gorm:"column:sort;type:bigint(20);comment:排序权重" json:"sort"`                                         // 排序权重
	Status    *bool      `gorm:"column:status;type:tinyint(1);default:1;comment:数据状态(0禁用,1启动)" json:"status"`                  // 数据状态(0禁用,1启动)
	Deleted   *bool      `gorm:"column:deleted;type:tinyint(1);comment:删除状态(0正常,1已删)" json:"deleted"`                          // 删除状态(0正常,1已删)
	DeletedAt *string    `gorm:"column:deleted_at;type:varchar(20);comment:删除时间" json:"deleted_at"`                            // 删除时间
	DeletedBy *int64     `gorm:"column:deleted_by;type:bigint(20);comment:删除用户" json:"deleted_by"`                             // 删除用户
	CreateAt  *time.Time `gorm:"column:create_at;type:datetime;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`       // 创建时间
}

// TableName MemeSystemBase's table name
func (*MemeSystemBase) TableName() string {
	return TableNameMemeSystemBase
}
