// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserReadHumanBoyWarnmningRecord = "user_read_human_boy_warnmning_record"

// UserReadHumanBoyWarnmningRecord 各个用户查看百人局小牛告警信息记录表
type UserReadHumanBoyWarnmningRecord struct {
	ID        uint32     `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID       uint32     `gorm:"column:uid;type:int(11) unsigned;not null;index:i_uid,priority:1;comment:用户id" json:"uid"`                                   // 用户id
	RecordNum uint32     `gorm:"column:record_num;type:int(11) unsigned;not null;comment:查看告警数目" json:"record_num"`                                          // 查看告警数目
	CreateAt  *time.Time `gorm:"column:create_at;type:datetime;not null;index:create_at,priority:1;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
}

// TableName UserReadHumanBoyWarnmningRecord's table name
func (*UserReadHumanBoyWarnmningRecord) TableName() string {
	return TableNameUserReadHumanBoyWarnmningRecord
}
