// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newDtbDailyratioRecord(db *gorm.DB, opts ...gen.DOOption) dtbDailyratioRecord {
	_dtbDailyratioRecord := dtbDailyratioRecord{}

	_dtbDailyratioRecord.dtbDailyratioRecordDo.UseDB(db, opts...)
	_dtbDailyratioRecord.dtbDailyratioRecordDo.UseModel(&model.DtbDailyratioRecord{})

	tableName := _dtbDailyratioRecord.dtbDailyratioRecordDo.TableName()
	_dtbDailyratioRecord.ALL = field.NewAsterisk(tableName)
	_dtbDailyratioRecord.ID = field.NewInt64(tableName, "id")
	_dtbDailyratioRecord.Date = field.NewTime(tableName, "date")
	_dtbDailyratioRecord.CurrencyFrom = field.NewString(tableName, "currency_from")
	_dtbDailyratioRecord.CurrencyTo = field.NewString(tableName, "currency_to")
	_dtbDailyratioRecord.CurrencyRate = field.NewFloat64(tableName, "currency_rate")
	_dtbDailyratioRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_dtbDailyratioRecord.UpdatedAt = field.NewTime(tableName, "updated_at")

	_dtbDailyratioRecord.fillFieldMap()

	return _dtbDailyratioRecord
}

type dtbDailyratioRecord struct {
	dtbDailyratioRecordDo

	ALL          field.Asterisk
	ID           field.Int64
	Date         field.Time
	CurrencyFrom field.String  // CNY 人民币、USD 美元
	CurrencyTo   field.String  // CNY 人民币、USD 美元
	CurrencyRate field.Float64 // 汇率. exchange ratio
	CreatedAt    field.Time
	UpdatedAt    field.Time

	fieldMap map[string]field.Expr
}

func (d dtbDailyratioRecord) Table(newTableName string) *dtbDailyratioRecord {
	d.dtbDailyratioRecordDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dtbDailyratioRecord) As(alias string) *dtbDailyratioRecord {
	d.dtbDailyratioRecordDo.DO = *(d.dtbDailyratioRecordDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dtbDailyratioRecord) updateTableName(table string) *dtbDailyratioRecord {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt64(table, "id")
	d.Date = field.NewTime(table, "date")
	d.CurrencyFrom = field.NewString(table, "currency_from")
	d.CurrencyTo = field.NewString(table, "currency_to")
	d.CurrencyRate = field.NewFloat64(table, "currency_rate")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")

	d.fillFieldMap()

	return d
}

func (d *dtbDailyratioRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dtbDailyratioRecord) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["id"] = d.ID
	d.fieldMap["date"] = d.Date
	d.fieldMap["currency_from"] = d.CurrencyFrom
	d.fieldMap["currency_to"] = d.CurrencyTo
	d.fieldMap["currency_rate"] = d.CurrencyRate
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
}

func (d dtbDailyratioRecord) clone(db *gorm.DB) dtbDailyratioRecord {
	d.dtbDailyratioRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dtbDailyratioRecord) replaceDB(db *gorm.DB) dtbDailyratioRecord {
	d.dtbDailyratioRecordDo.ReplaceDB(db)
	return d
}

type dtbDailyratioRecordDo struct{ gen.DO }

type IDtbDailyratioRecordDo interface {
	gen.SubQuery
	Debug() IDtbDailyratioRecordDo
	WithContext(ctx context.Context) IDtbDailyratioRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDtbDailyratioRecordDo
	WriteDB() IDtbDailyratioRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDtbDailyratioRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDtbDailyratioRecordDo
	Not(conds ...gen.Condition) IDtbDailyratioRecordDo
	Or(conds ...gen.Condition) IDtbDailyratioRecordDo
	Select(conds ...field.Expr) IDtbDailyratioRecordDo
	Where(conds ...gen.Condition) IDtbDailyratioRecordDo
	Order(conds ...field.Expr) IDtbDailyratioRecordDo
	Distinct(cols ...field.Expr) IDtbDailyratioRecordDo
	Omit(cols ...field.Expr) IDtbDailyratioRecordDo
	Join(table schema.Tabler, on ...field.Expr) IDtbDailyratioRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDtbDailyratioRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDtbDailyratioRecordDo
	Group(cols ...field.Expr) IDtbDailyratioRecordDo
	Having(conds ...gen.Condition) IDtbDailyratioRecordDo
	Limit(limit int) IDtbDailyratioRecordDo
	Offset(offset int) IDtbDailyratioRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbDailyratioRecordDo
	Unscoped() IDtbDailyratioRecordDo
	Create(values ...*model.DtbDailyratioRecord) error
	CreateInBatches(values []*model.DtbDailyratioRecord, batchSize int) error
	Save(values ...*model.DtbDailyratioRecord) error
	First() (*model.DtbDailyratioRecord, error)
	Take() (*model.DtbDailyratioRecord, error)
	Last() (*model.DtbDailyratioRecord, error)
	Find() ([]*model.DtbDailyratioRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbDailyratioRecord, err error)
	FindInBatches(result *[]*model.DtbDailyratioRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DtbDailyratioRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDtbDailyratioRecordDo
	Assign(attrs ...field.AssignExpr) IDtbDailyratioRecordDo
	Joins(fields ...field.RelationField) IDtbDailyratioRecordDo
	Preload(fields ...field.RelationField) IDtbDailyratioRecordDo
	FirstOrInit() (*model.DtbDailyratioRecord, error)
	FirstOrCreate() (*model.DtbDailyratioRecord, error)
	FindByPage(offset int, limit int) (result []*model.DtbDailyratioRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDtbDailyratioRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dtbDailyratioRecordDo) Debug() IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Debug())
}

func (d dtbDailyratioRecordDo) WithContext(ctx context.Context) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dtbDailyratioRecordDo) ReadDB() IDtbDailyratioRecordDo {
	return d.Clauses(dbresolver.Read)
}

func (d dtbDailyratioRecordDo) WriteDB() IDtbDailyratioRecordDo {
	return d.Clauses(dbresolver.Write)
}

func (d dtbDailyratioRecordDo) Session(config *gorm.Session) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Session(config))
}

func (d dtbDailyratioRecordDo) Clauses(conds ...clause.Expression) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dtbDailyratioRecordDo) Returning(value interface{}, columns ...string) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dtbDailyratioRecordDo) Not(conds ...gen.Condition) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dtbDailyratioRecordDo) Or(conds ...gen.Condition) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dtbDailyratioRecordDo) Select(conds ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dtbDailyratioRecordDo) Where(conds ...gen.Condition) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dtbDailyratioRecordDo) Order(conds ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dtbDailyratioRecordDo) Distinct(cols ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dtbDailyratioRecordDo) Omit(cols ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dtbDailyratioRecordDo) Join(table schema.Tabler, on ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dtbDailyratioRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dtbDailyratioRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dtbDailyratioRecordDo) Group(cols ...field.Expr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dtbDailyratioRecordDo) Having(conds ...gen.Condition) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dtbDailyratioRecordDo) Limit(limit int) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dtbDailyratioRecordDo) Offset(offset int) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dtbDailyratioRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dtbDailyratioRecordDo) Unscoped() IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dtbDailyratioRecordDo) Create(values ...*model.DtbDailyratioRecord) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dtbDailyratioRecordDo) CreateInBatches(values []*model.DtbDailyratioRecord, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dtbDailyratioRecordDo) Save(values ...*model.DtbDailyratioRecord) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dtbDailyratioRecordDo) First() (*model.DtbDailyratioRecord, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbDailyratioRecord), nil
	}
}

func (d dtbDailyratioRecordDo) Take() (*model.DtbDailyratioRecord, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbDailyratioRecord), nil
	}
}

func (d dtbDailyratioRecordDo) Last() (*model.DtbDailyratioRecord, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbDailyratioRecord), nil
	}
}

func (d dtbDailyratioRecordDo) Find() ([]*model.DtbDailyratioRecord, error) {
	result, err := d.DO.Find()
	return result.([]*model.DtbDailyratioRecord), err
}

func (d dtbDailyratioRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbDailyratioRecord, err error) {
	buf := make([]*model.DtbDailyratioRecord, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dtbDailyratioRecordDo) FindInBatches(result *[]*model.DtbDailyratioRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dtbDailyratioRecordDo) Attrs(attrs ...field.AssignExpr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dtbDailyratioRecordDo) Assign(attrs ...field.AssignExpr) IDtbDailyratioRecordDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dtbDailyratioRecordDo) Joins(fields ...field.RelationField) IDtbDailyratioRecordDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dtbDailyratioRecordDo) Preload(fields ...field.RelationField) IDtbDailyratioRecordDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dtbDailyratioRecordDo) FirstOrInit() (*model.DtbDailyratioRecord, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbDailyratioRecord), nil
	}
}

func (d dtbDailyratioRecordDo) FirstOrCreate() (*model.DtbDailyratioRecord, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbDailyratioRecord), nil
	}
}

func (d dtbDailyratioRecordDo) FindByPage(offset int, limit int) (result []*model.DtbDailyratioRecord, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dtbDailyratioRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dtbDailyratioRecordDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dtbDailyratioRecordDo) Delete(models ...*model.DtbDailyratioRecord) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dtbDailyratioRecordDo) withDO(do gen.Dao) *dtbDailyratioRecordDo {
	d.DO = *do.(*gen.DO)
	return d
}
