// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newFairplayEmail(db *gorm.DB, opts ...gen.DOOption) fairplayEmail {
	_fairplayEmail := fairplayEmail{}

	_fairplayEmail.fairplayEmailDo.UseDB(db, opts...)
	_fairplayEmail.fairplayEmailDo.UseModel(&model.FairplayEmail{})

	tableName := _fairplayEmail.fairplayEmailDo.TableName()
	_fairplayEmail.ALL = field.NewAsterisk(tableName)
	_fairplayEmail.ID = field.NewUint32(tableName, "id")
	_fairplayEmail.ReportID = field.NewUint32(tableName, "report_id")
	_fairplayEmail.SenderID = field.NewUint32(tableName, "sender_id")
	_fairplayEmail.ReceiverID = field.NewUint32(tableName, "receiver_id")
	_fairplayEmail.ReceiverMail = field.NewString(tableName, "receiver_mail")
	_fairplayEmail.Title = field.NewString(tableName, "title")
	_fairplayEmail.Content = field.NewString(tableName, "content")
	_fairplayEmail.CreateTime = field.NewUint32(tableName, "create_time")
	_fairplayEmail.UpdateTime = field.NewUint32(tableName, "update_time")

	_fairplayEmail.fillFieldMap()

	return _fairplayEmail
}

// fairplayEmail 邮件记录表
type fairplayEmail struct {
	fairplayEmailDo

	ALL          field.Asterisk
	ID           field.Uint32 // id
	ReportID     field.Uint32 // 举报记录id
	SenderID     field.Uint32 // 发送者uid
	ReceiverID   field.Uint32 // 接收者uid
	ReceiverMail field.String // 接收者邮箱
	Title        field.String // 标题
	Content      field.String // 内容
	CreateTime   field.Uint32 // 创建时间
	UpdateTime   field.Uint32 // 修改时间

	fieldMap map[string]field.Expr
}

func (f fairplayEmail) Table(newTableName string) *fairplayEmail {
	f.fairplayEmailDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fairplayEmail) As(alias string) *fairplayEmail {
	f.fairplayEmailDo.DO = *(f.fairplayEmailDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fairplayEmail) updateTableName(table string) *fairplayEmail {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewUint32(table, "id")
	f.ReportID = field.NewUint32(table, "report_id")
	f.SenderID = field.NewUint32(table, "sender_id")
	f.ReceiverID = field.NewUint32(table, "receiver_id")
	f.ReceiverMail = field.NewString(table, "receiver_mail")
	f.Title = field.NewString(table, "title")
	f.Content = field.NewString(table, "content")
	f.CreateTime = field.NewUint32(table, "create_time")
	f.UpdateTime = field.NewUint32(table, "update_time")

	f.fillFieldMap()

	return f
}

func (f *fairplayEmail) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fairplayEmail) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 9)
	f.fieldMap["id"] = f.ID
	f.fieldMap["report_id"] = f.ReportID
	f.fieldMap["sender_id"] = f.SenderID
	f.fieldMap["receiver_id"] = f.ReceiverID
	f.fieldMap["receiver_mail"] = f.ReceiverMail
	f.fieldMap["title"] = f.Title
	f.fieldMap["content"] = f.Content
	f.fieldMap["create_time"] = f.CreateTime
	f.fieldMap["update_time"] = f.UpdateTime
}

func (f fairplayEmail) clone(db *gorm.DB) fairplayEmail {
	f.fairplayEmailDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fairplayEmail) replaceDB(db *gorm.DB) fairplayEmail {
	f.fairplayEmailDo.ReplaceDB(db)
	return f
}

type fairplayEmailDo struct{ gen.DO }

type IFairplayEmailDo interface {
	gen.SubQuery
	Debug() IFairplayEmailDo
	WithContext(ctx context.Context) IFairplayEmailDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFairplayEmailDo
	WriteDB() IFairplayEmailDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFairplayEmailDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFairplayEmailDo
	Not(conds ...gen.Condition) IFairplayEmailDo
	Or(conds ...gen.Condition) IFairplayEmailDo
	Select(conds ...field.Expr) IFairplayEmailDo
	Where(conds ...gen.Condition) IFairplayEmailDo
	Order(conds ...field.Expr) IFairplayEmailDo
	Distinct(cols ...field.Expr) IFairplayEmailDo
	Omit(cols ...field.Expr) IFairplayEmailDo
	Join(table schema.Tabler, on ...field.Expr) IFairplayEmailDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFairplayEmailDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFairplayEmailDo
	Group(cols ...field.Expr) IFairplayEmailDo
	Having(conds ...gen.Condition) IFairplayEmailDo
	Limit(limit int) IFairplayEmailDo
	Offset(offset int) IFairplayEmailDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFairplayEmailDo
	Unscoped() IFairplayEmailDo
	Create(values ...*model.FairplayEmail) error
	CreateInBatches(values []*model.FairplayEmail, batchSize int) error
	Save(values ...*model.FairplayEmail) error
	First() (*model.FairplayEmail, error)
	Take() (*model.FairplayEmail, error)
	Last() (*model.FairplayEmail, error)
	Find() ([]*model.FairplayEmail, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FairplayEmail, err error)
	FindInBatches(result *[]*model.FairplayEmail, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.FairplayEmail) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFairplayEmailDo
	Assign(attrs ...field.AssignExpr) IFairplayEmailDo
	Joins(fields ...field.RelationField) IFairplayEmailDo
	Preload(fields ...field.RelationField) IFairplayEmailDo
	FirstOrInit() (*model.FairplayEmail, error)
	FirstOrCreate() (*model.FairplayEmail, error)
	FindByPage(offset int, limit int) (result []*model.FairplayEmail, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFairplayEmailDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f fairplayEmailDo) Debug() IFairplayEmailDo {
	return f.withDO(f.DO.Debug())
}

func (f fairplayEmailDo) WithContext(ctx context.Context) IFairplayEmailDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fairplayEmailDo) ReadDB() IFairplayEmailDo {
	return f.Clauses(dbresolver.Read)
}

func (f fairplayEmailDo) WriteDB() IFairplayEmailDo {
	return f.Clauses(dbresolver.Write)
}

func (f fairplayEmailDo) Session(config *gorm.Session) IFairplayEmailDo {
	return f.withDO(f.DO.Session(config))
}

func (f fairplayEmailDo) Clauses(conds ...clause.Expression) IFairplayEmailDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fairplayEmailDo) Returning(value interface{}, columns ...string) IFairplayEmailDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fairplayEmailDo) Not(conds ...gen.Condition) IFairplayEmailDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fairplayEmailDo) Or(conds ...gen.Condition) IFairplayEmailDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fairplayEmailDo) Select(conds ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fairplayEmailDo) Where(conds ...gen.Condition) IFairplayEmailDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fairplayEmailDo) Order(conds ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fairplayEmailDo) Distinct(cols ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fairplayEmailDo) Omit(cols ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fairplayEmailDo) Join(table schema.Tabler, on ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fairplayEmailDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fairplayEmailDo) RightJoin(table schema.Tabler, on ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fairplayEmailDo) Group(cols ...field.Expr) IFairplayEmailDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fairplayEmailDo) Having(conds ...gen.Condition) IFairplayEmailDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fairplayEmailDo) Limit(limit int) IFairplayEmailDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fairplayEmailDo) Offset(offset int) IFairplayEmailDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fairplayEmailDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFairplayEmailDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fairplayEmailDo) Unscoped() IFairplayEmailDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fairplayEmailDo) Create(values ...*model.FairplayEmail) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fairplayEmailDo) CreateInBatches(values []*model.FairplayEmail, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fairplayEmailDo) Save(values ...*model.FairplayEmail) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fairplayEmailDo) First() (*model.FairplayEmail, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FairplayEmail), nil
	}
}

func (f fairplayEmailDo) Take() (*model.FairplayEmail, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FairplayEmail), nil
	}
}

func (f fairplayEmailDo) Last() (*model.FairplayEmail, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FairplayEmail), nil
	}
}

func (f fairplayEmailDo) Find() ([]*model.FairplayEmail, error) {
	result, err := f.DO.Find()
	return result.([]*model.FairplayEmail), err
}

func (f fairplayEmailDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FairplayEmail, err error) {
	buf := make([]*model.FairplayEmail, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fairplayEmailDo) FindInBatches(result *[]*model.FairplayEmail, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fairplayEmailDo) Attrs(attrs ...field.AssignExpr) IFairplayEmailDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fairplayEmailDo) Assign(attrs ...field.AssignExpr) IFairplayEmailDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fairplayEmailDo) Joins(fields ...field.RelationField) IFairplayEmailDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fairplayEmailDo) Preload(fields ...field.RelationField) IFairplayEmailDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fairplayEmailDo) FirstOrInit() (*model.FairplayEmail, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FairplayEmail), nil
	}
}

func (f fairplayEmailDo) FirstOrCreate() (*model.FairplayEmail, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FairplayEmail), nil
	}
}

func (f fairplayEmailDo) FindByPage(offset int, limit int) (result []*model.FairplayEmail, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fairplayEmailDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fairplayEmailDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fairplayEmailDo) Delete(models ...*model.FairplayEmail) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fairplayEmailDo) withDO(do gen.Dao) *fairplayEmailDo {
	f.DO = *do.(*gen.DO)
	return f
}
