// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                           = new(Query)
	AmountLimit                 *amountLimit
	AmountLimitDetail           *amountLimitDetail
	AofUIDLuckdrawDetail        *aofUIDLuckdrawDetail
	AofUIDTransIncomeDetail     *aofUIDTransIncomeDetail
	ChargeLoss                  *chargeLoss
	Club2alliMonthyContr        *club2alliMonthyContr
	CoinAPILog                  *coinAPILog
	CoinAdminErrorPwdRecord     *coinAdminErrorPwdRecord
	CowboyGameEnd               *cowboyGameEnd
	CowboyRoom                  *cowboyRoom
	CowboyRoomAlarmRecord       *cowboyRoomAlarmRecord
	CowboyRoomMoneyDaily        *cowboyRoomMoneyDaily
	CowboyRoundBetDetail        *cowboyRoundBetDetail
	CowbyoyRoomAlarmRecord      *cowbyoyRoomAlarmRecord
	CowbyoyRoomMoneyDaily       *cowbyoyRoomMoneyDaily
	DailyGamehand               *dailyGamehand
	DailyUsdtInfo               *dailyUsdtInfo
	DeviceinfoRecord            *deviceinfoRecord
	DomainReport                *domainReport
	DtbCfdSyncDaily             *dtbCfdSyncDaily
	DtbDailyratioRecord         *dtbDailyratioRecord
	DtbHabaSyncDaily            *dtbHabaSyncDaily
	EveryLevelGameCensu         *everyLevelGameCensu
	FairplayEmail               *fairplayEmail
	FairplayRecord              *fairplayRecord
	FairplayRecordAction        *fairplayRecordAction
	FairplayReport              *fairplayReport
	GameCoinInventoryIncrDetail *gameCoinInventoryIncrDetail
	GameCoinOrder               *gameCoinOrder
	GameCoinOrderUserInfo       *gameCoinOrderUserInfo
	GameCoinOrderUserType       *gameCoinOrderUserType
	GoldChangeDatum             *goldChangeDatum
	GoldCoinInventoryIncrDetail *goldCoinInventoryIncrDetail
	GoldCoinOrder               *goldCoinOrder
	GoldCoinOrderUserInfo       *goldCoinOrderUserInfo
	GoldCoinOrderUserType       *goldCoinOrderUserType
	GoldcoinInventory           *goldcoinInventory
	HandinfoRecord              *handinfoRecord
	HumanboyDatum               *humanboyDatum
	HumanboyGameEnd             *humanboyGameEnd
	HumanboyPlayGameRecord      *humanboyPlayGameRecord
	HumanboyRoom                *humanboyRoom
	HumanboyRoomAlarmRecord     *humanboyRoomAlarmRecord
	HumanboyRoomMoneyDaily      *humanboyRoomMoneyDaily
	KickoffJackpotRecord        *kickoffJackpotRecord
	ManuallyCreateRoom          *manuallyCreateRoom
	MemeDaily                   *memeDaily
	MemePropsIncrDetail         *memePropsIncrDetail
	MemePropsLog                *memePropsLog
	MttRefundRecord             *mttRefundRecord
	MultiplayerBrush            *multiplayerBrush
	MultiplayerBrushDetail      *multiplayerBrushDetail
	ObFetchHistory              *obFetchHistory
	ObOnlineBalance             *obOnlineBalance
	PlatUserDailyContr          *platUserDailyContr
	PointInventoryIncrDetail    *pointInventoryIncrDetail
	PointOrder                  *pointOrder
	PointOrderUserInfo          *pointOrderUserInfo
	PointOrderUserType          *pointOrderUserType
	PokerGameEnd                *pokerGameEnd
	PokerRoom                   *pokerRoom
	PokerRoomAlarmRecord        *pokerRoomAlarmRecord
	PokerRoomMoneyDaily         *pokerRoomMoneyDaily
	PpFetchHistory              *ppFetchHistory
	ScFinanceReport             *scFinanceReport
	ScInventoryIncrDetail       *scInventoryIncrDetail
	ScOrder                     *scOrder
	ScOrderUserInfo             *scOrderUserInfo
	ScOrderUserType             *scOrderUserType
	SmallGamesValidDailyBet     *smallGamesValidDailyBet
	SnakeAdminAction            *snakeAdminAction
	SnakeNode                   *snakeNode
	SnakeRecordAction           *snakeRecordAction
	SnakeRole                   *snakeRole
	SnakeUser                   *snakeUser
	StrongboxBlacklist          *strongboxBlacklist
	TForbidAccountLog           *tForbidAccountLog
	TPlatformBalanceReport      *tPlatformBalanceReport
	TUndepositAmountReport      *tUndepositAmountReport
	TUnwithdrawn                *tUnwithdrawn
	TipsGiftsDetail             *tipsGiftsDetail
	TipsObtainedRecord          *tipsObtainedRecord
	Toolpay                     *toolpay
	UIDClubChange               *uIDClubChange
	UserClassMonthStat          *userClassMonthStat
	UserEveryLevelHandInfo      *userEveryLevelHandInfo
	UserGame                    *userGame
	UserGuessCfgDatum           *userGuessCfgDatum
	UserPlayedMonthStat         *userPlayedMonthStat
	VideoboyDatum               *videoboyDatum
	VideoboyGameEnd             *videoboyGameEnd
	VideoboyRevertNoendround    *videoboyRevertNoendround
	VideoboyRevertRound         *videoboyRevertRound
	VideoboyRoom                *videoboyRoom
	VideoboyRoomAlarmRecord     *videoboyRoomAlarmRecord
	VideoboyRoomMoneyDaily      *videoboyRoomMoneyDaily
	VoidBet                     *voidBet
	ZoomUIDIncomeDaily          *zoomUIDIncomeDaily
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AmountLimit = &Q.AmountLimit
	AmountLimitDetail = &Q.AmountLimitDetail
	AofUIDLuckdrawDetail = &Q.AofUIDLuckdrawDetail
	AofUIDTransIncomeDetail = &Q.AofUIDTransIncomeDetail
	ChargeLoss = &Q.ChargeLoss
	Club2alliMonthyContr = &Q.Club2alliMonthyContr
	CoinAPILog = &Q.CoinAPILog
	CoinAdminErrorPwdRecord = &Q.CoinAdminErrorPwdRecord
	CowboyGameEnd = &Q.CowboyGameEnd
	CowboyRoom = &Q.CowboyRoom
	CowboyRoomAlarmRecord = &Q.CowboyRoomAlarmRecord
	CowboyRoomMoneyDaily = &Q.CowboyRoomMoneyDaily
	CowboyRoundBetDetail = &Q.CowboyRoundBetDetail
	CowbyoyRoomAlarmRecord = &Q.CowbyoyRoomAlarmRecord
	CowbyoyRoomMoneyDaily = &Q.CowbyoyRoomMoneyDaily
	DailyGamehand = &Q.DailyGamehand
	DailyUsdtInfo = &Q.DailyUsdtInfo
	DeviceinfoRecord = &Q.DeviceinfoRecord
	DomainReport = &Q.DomainReport
	DtbCfdSyncDaily = &Q.DtbCfdSyncDaily
	DtbDailyratioRecord = &Q.DtbDailyratioRecord
	DtbHabaSyncDaily = &Q.DtbHabaSyncDaily
	EveryLevelGameCensu = &Q.EveryLevelGameCensu
	FairplayEmail = &Q.FairplayEmail
	FairplayRecord = &Q.FairplayRecord
	FairplayRecordAction = &Q.FairplayRecordAction
	FairplayReport = &Q.FairplayReport
	GameCoinInventoryIncrDetail = &Q.GameCoinInventoryIncrDetail
	GameCoinOrder = &Q.GameCoinOrder
	GameCoinOrderUserInfo = &Q.GameCoinOrderUserInfo
	GameCoinOrderUserType = &Q.GameCoinOrderUserType
	GoldChangeDatum = &Q.GoldChangeDatum
	GoldCoinInventoryIncrDetail = &Q.GoldCoinInventoryIncrDetail
	GoldCoinOrder = &Q.GoldCoinOrder
	GoldCoinOrderUserInfo = &Q.GoldCoinOrderUserInfo
	GoldCoinOrderUserType = &Q.GoldCoinOrderUserType
	GoldcoinInventory = &Q.GoldcoinInventory
	HandinfoRecord = &Q.HandinfoRecord
	HumanboyDatum = &Q.HumanboyDatum
	HumanboyGameEnd = &Q.HumanboyGameEnd
	HumanboyPlayGameRecord = &Q.HumanboyPlayGameRecord
	HumanboyRoom = &Q.HumanboyRoom
	HumanboyRoomAlarmRecord = &Q.HumanboyRoomAlarmRecord
	HumanboyRoomMoneyDaily = &Q.HumanboyRoomMoneyDaily
	KickoffJackpotRecord = &Q.KickoffJackpotRecord
	ManuallyCreateRoom = &Q.ManuallyCreateRoom
	MemeDaily = &Q.MemeDaily
	MemePropsIncrDetail = &Q.MemePropsIncrDetail
	MemePropsLog = &Q.MemePropsLog
	MttRefundRecord = &Q.MttRefundRecord
	MultiplayerBrush = &Q.MultiplayerBrush
	MultiplayerBrushDetail = &Q.MultiplayerBrushDetail
	ObFetchHistory = &Q.ObFetchHistory
	ObOnlineBalance = &Q.ObOnlineBalance
	PlatUserDailyContr = &Q.PlatUserDailyContr
	PointInventoryIncrDetail = &Q.PointInventoryIncrDetail
	PointOrder = &Q.PointOrder
	PointOrderUserInfo = &Q.PointOrderUserInfo
	PointOrderUserType = &Q.PointOrderUserType
	PokerGameEnd = &Q.PokerGameEnd
	PokerRoom = &Q.PokerRoom
	PokerRoomAlarmRecord = &Q.PokerRoomAlarmRecord
	PokerRoomMoneyDaily = &Q.PokerRoomMoneyDaily
	PpFetchHistory = &Q.PpFetchHistory
	ScFinanceReport = &Q.ScFinanceReport
	ScInventoryIncrDetail = &Q.ScInventoryIncrDetail
	ScOrder = &Q.ScOrder
	ScOrderUserInfo = &Q.ScOrderUserInfo
	ScOrderUserType = &Q.ScOrderUserType
	SmallGamesValidDailyBet = &Q.SmallGamesValidDailyBet
	SnakeAdminAction = &Q.SnakeAdminAction
	SnakeNode = &Q.SnakeNode
	SnakeRecordAction = &Q.SnakeRecordAction
	SnakeRole = &Q.SnakeRole
	SnakeUser = &Q.SnakeUser
	StrongboxBlacklist = &Q.StrongboxBlacklist
	TForbidAccountLog = &Q.TForbidAccountLog
	TPlatformBalanceReport = &Q.TPlatformBalanceReport
	TUndepositAmountReport = &Q.TUndepositAmountReport
	TUnwithdrawn = &Q.TUnwithdrawn
	TipsGiftsDetail = &Q.TipsGiftsDetail
	TipsObtainedRecord = &Q.TipsObtainedRecord
	Toolpay = &Q.Toolpay
	UIDClubChange = &Q.UIDClubChange
	UserClassMonthStat = &Q.UserClassMonthStat
	UserEveryLevelHandInfo = &Q.UserEveryLevelHandInfo
	UserGame = &Q.UserGame
	UserGuessCfgDatum = &Q.UserGuessCfgDatum
	UserPlayedMonthStat = &Q.UserPlayedMonthStat
	VideoboyDatum = &Q.VideoboyDatum
	VideoboyGameEnd = &Q.VideoboyGameEnd
	VideoboyRevertNoendround = &Q.VideoboyRevertNoendround
	VideoboyRevertRound = &Q.VideoboyRevertRound
	VideoboyRoom = &Q.VideoboyRoom
	VideoboyRoomAlarmRecord = &Q.VideoboyRoomAlarmRecord
	VideoboyRoomMoneyDaily = &Q.VideoboyRoomMoneyDaily
	VoidBet = &Q.VoidBet
	ZoomUIDIncomeDaily = &Q.ZoomUIDIncomeDaily
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                          db,
		AmountLimit:                 newAmountLimit(db, opts...),
		AmountLimitDetail:           newAmountLimitDetail(db, opts...),
		AofUIDLuckdrawDetail:        newAofUIDLuckdrawDetail(db, opts...),
		AofUIDTransIncomeDetail:     newAofUIDTransIncomeDetail(db, opts...),
		ChargeLoss:                  newChargeLoss(db, opts...),
		Club2alliMonthyContr:        newClub2alliMonthyContr(db, opts...),
		CoinAPILog:                  newCoinAPILog(db, opts...),
		CoinAdminErrorPwdRecord:     newCoinAdminErrorPwdRecord(db, opts...),
		CowboyGameEnd:               newCowboyGameEnd(db, opts...),
		CowboyRoom:                  newCowboyRoom(db, opts...),
		CowboyRoomAlarmRecord:       newCowboyRoomAlarmRecord(db, opts...),
		CowboyRoomMoneyDaily:        newCowboyRoomMoneyDaily(db, opts...),
		CowboyRoundBetDetail:        newCowboyRoundBetDetail(db, opts...),
		CowbyoyRoomAlarmRecord:      newCowbyoyRoomAlarmRecord(db, opts...),
		CowbyoyRoomMoneyDaily:       newCowbyoyRoomMoneyDaily(db, opts...),
		DailyGamehand:               newDailyGamehand(db, opts...),
		DailyUsdtInfo:               newDailyUsdtInfo(db, opts...),
		DeviceinfoRecord:            newDeviceinfoRecord(db, opts...),
		DomainReport:                newDomainReport(db, opts...),
		DtbCfdSyncDaily:             newDtbCfdSyncDaily(db, opts...),
		DtbDailyratioRecord:         newDtbDailyratioRecord(db, opts...),
		DtbHabaSyncDaily:            newDtbHabaSyncDaily(db, opts...),
		EveryLevelGameCensu:         newEveryLevelGameCensu(db, opts...),
		FairplayEmail:               newFairplayEmail(db, opts...),
		FairplayRecord:              newFairplayRecord(db, opts...),
		FairplayRecordAction:        newFairplayRecordAction(db, opts...),
		FairplayReport:              newFairplayReport(db, opts...),
		GameCoinInventoryIncrDetail: newGameCoinInventoryIncrDetail(db, opts...),
		GameCoinOrder:               newGameCoinOrder(db, opts...),
		GameCoinOrderUserInfo:       newGameCoinOrderUserInfo(db, opts...),
		GameCoinOrderUserType:       newGameCoinOrderUserType(db, opts...),
		GoldChangeDatum:             newGoldChangeDatum(db, opts...),
		GoldCoinInventoryIncrDetail: newGoldCoinInventoryIncrDetail(db, opts...),
		GoldCoinOrder:               newGoldCoinOrder(db, opts...),
		GoldCoinOrderUserInfo:       newGoldCoinOrderUserInfo(db, opts...),
		GoldCoinOrderUserType:       newGoldCoinOrderUserType(db, opts...),
		GoldcoinInventory:           newGoldcoinInventory(db, opts...),
		HandinfoRecord:              newHandinfoRecord(db, opts...),
		HumanboyDatum:               newHumanboyDatum(db, opts...),
		HumanboyGameEnd:             newHumanboyGameEnd(db, opts...),
		HumanboyPlayGameRecord:      newHumanboyPlayGameRecord(db, opts...),
		HumanboyRoom:                newHumanboyRoom(db, opts...),
		HumanboyRoomAlarmRecord:     newHumanboyRoomAlarmRecord(db, opts...),
		HumanboyRoomMoneyDaily:      newHumanboyRoomMoneyDaily(db, opts...),
		KickoffJackpotRecord:        newKickoffJackpotRecord(db, opts...),
		ManuallyCreateRoom:          newManuallyCreateRoom(db, opts...),
		MemeDaily:                   newMemeDaily(db, opts...),
		MemePropsIncrDetail:         newMemePropsIncrDetail(db, opts...),
		MemePropsLog:                newMemePropsLog(db, opts...),
		MttRefundRecord:             newMttRefundRecord(db, opts...),
		MultiplayerBrush:            newMultiplayerBrush(db, opts...),
		MultiplayerBrushDetail:      newMultiplayerBrushDetail(db, opts...),
		ObFetchHistory:              newObFetchHistory(db, opts...),
		ObOnlineBalance:             newObOnlineBalance(db, opts...),
		PlatUserDailyContr:          newPlatUserDailyContr(db, opts...),
		PointInventoryIncrDetail:    newPointInventoryIncrDetail(db, opts...),
		PointOrder:                  newPointOrder(db, opts...),
		PointOrderUserInfo:          newPointOrderUserInfo(db, opts...),
		PointOrderUserType:          newPointOrderUserType(db, opts...),
		PokerGameEnd:                newPokerGameEnd(db, opts...),
		PokerRoom:                   newPokerRoom(db, opts...),
		PokerRoomAlarmRecord:        newPokerRoomAlarmRecord(db, opts...),
		PokerRoomMoneyDaily:         newPokerRoomMoneyDaily(db, opts...),
		PpFetchHistory:              newPpFetchHistory(db, opts...),
		ScFinanceReport:             newScFinanceReport(db, opts...),
		ScInventoryIncrDetail:       newScInventoryIncrDetail(db, opts...),
		ScOrder:                     newScOrder(db, opts...),
		ScOrderUserInfo:             newScOrderUserInfo(db, opts...),
		ScOrderUserType:             newScOrderUserType(db, opts...),
		SmallGamesValidDailyBet:     newSmallGamesValidDailyBet(db, opts...),
		SnakeAdminAction:            newSnakeAdminAction(db, opts...),
		SnakeNode:                   newSnakeNode(db, opts...),
		SnakeRecordAction:           newSnakeRecordAction(db, opts...),
		SnakeRole:                   newSnakeRole(db, opts...),
		SnakeUser:                   newSnakeUser(db, opts...),
		StrongboxBlacklist:          newStrongboxBlacklist(db, opts...),
		TForbidAccountLog:           newTForbidAccountLog(db, opts...),
		TPlatformBalanceReport:      newTPlatformBalanceReport(db, opts...),
		TUndepositAmountReport:      newTUndepositAmountReport(db, opts...),
		TUnwithdrawn:                newTUnwithdrawn(db, opts...),
		TipsGiftsDetail:             newTipsGiftsDetail(db, opts...),
		TipsObtainedRecord:          newTipsObtainedRecord(db, opts...),
		Toolpay:                     newToolpay(db, opts...),
		UIDClubChange:               newUIDClubChange(db, opts...),
		UserClassMonthStat:          newUserClassMonthStat(db, opts...),
		UserEveryLevelHandInfo:      newUserEveryLevelHandInfo(db, opts...),
		UserGame:                    newUserGame(db, opts...),
		UserGuessCfgDatum:           newUserGuessCfgDatum(db, opts...),
		UserPlayedMonthStat:         newUserPlayedMonthStat(db, opts...),
		VideoboyDatum:               newVideoboyDatum(db, opts...),
		VideoboyGameEnd:             newVideoboyGameEnd(db, opts...),
		VideoboyRevertNoendround:    newVideoboyRevertNoendround(db, opts...),
		VideoboyRevertRound:         newVideoboyRevertRound(db, opts...),
		VideoboyRoom:                newVideoboyRoom(db, opts...),
		VideoboyRoomAlarmRecord:     newVideoboyRoomAlarmRecord(db, opts...),
		VideoboyRoomMoneyDaily:      newVideoboyRoomMoneyDaily(db, opts...),
		VoidBet:                     newVoidBet(db, opts...),
		ZoomUIDIncomeDaily:          newZoomUIDIncomeDaily(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AmountLimit                 amountLimit
	AmountLimitDetail           amountLimitDetail
	AofUIDLuckdrawDetail        aofUIDLuckdrawDetail
	AofUIDTransIncomeDetail     aofUIDTransIncomeDetail
	ChargeLoss                  chargeLoss
	Club2alliMonthyContr        club2alliMonthyContr
	CoinAPILog                  coinAPILog
	CoinAdminErrorPwdRecord     coinAdminErrorPwdRecord
	CowboyGameEnd               cowboyGameEnd
	CowboyRoom                  cowboyRoom
	CowboyRoomAlarmRecord       cowboyRoomAlarmRecord
	CowboyRoomMoneyDaily        cowboyRoomMoneyDaily
	CowboyRoundBetDetail        cowboyRoundBetDetail
	CowbyoyRoomAlarmRecord      cowbyoyRoomAlarmRecord
	CowbyoyRoomMoneyDaily       cowbyoyRoomMoneyDaily
	DailyGamehand               dailyGamehand
	DailyUsdtInfo               dailyUsdtInfo
	DeviceinfoRecord            deviceinfoRecord
	DomainReport                domainReport
	DtbCfdSyncDaily             dtbCfdSyncDaily
	DtbDailyratioRecord         dtbDailyratioRecord
	DtbHabaSyncDaily            dtbHabaSyncDaily
	EveryLevelGameCensu         everyLevelGameCensu
	FairplayEmail               fairplayEmail
	FairplayRecord              fairplayRecord
	FairplayRecordAction        fairplayRecordAction
	FairplayReport              fairplayReport
	GameCoinInventoryIncrDetail gameCoinInventoryIncrDetail
	GameCoinOrder               gameCoinOrder
	GameCoinOrderUserInfo       gameCoinOrderUserInfo
	GameCoinOrderUserType       gameCoinOrderUserType
	GoldChangeDatum             goldChangeDatum
	GoldCoinInventoryIncrDetail goldCoinInventoryIncrDetail
	GoldCoinOrder               goldCoinOrder
	GoldCoinOrderUserInfo       goldCoinOrderUserInfo
	GoldCoinOrderUserType       goldCoinOrderUserType
	GoldcoinInventory           goldcoinInventory
	HandinfoRecord              handinfoRecord
	HumanboyDatum               humanboyDatum
	HumanboyGameEnd             humanboyGameEnd
	HumanboyPlayGameRecord      humanboyPlayGameRecord
	HumanboyRoom                humanboyRoom
	HumanboyRoomAlarmRecord     humanboyRoomAlarmRecord
	HumanboyRoomMoneyDaily      humanboyRoomMoneyDaily
	KickoffJackpotRecord        kickoffJackpotRecord
	ManuallyCreateRoom          manuallyCreateRoom
	MemeDaily                   memeDaily
	MemePropsIncrDetail         memePropsIncrDetail
	MemePropsLog                memePropsLog
	MttRefundRecord             mttRefundRecord
	MultiplayerBrush            multiplayerBrush
	MultiplayerBrushDetail      multiplayerBrushDetail
	ObFetchHistory              obFetchHistory
	ObOnlineBalance             obOnlineBalance
	PlatUserDailyContr          platUserDailyContr
	PointInventoryIncrDetail    pointInventoryIncrDetail
	PointOrder                  pointOrder
	PointOrderUserInfo          pointOrderUserInfo
	PointOrderUserType          pointOrderUserType
	PokerGameEnd                pokerGameEnd
	PokerRoom                   pokerRoom
	PokerRoomAlarmRecord        pokerRoomAlarmRecord
	PokerRoomMoneyDaily         pokerRoomMoneyDaily
	PpFetchHistory              ppFetchHistory
	ScFinanceReport             scFinanceReport
	ScInventoryIncrDetail       scInventoryIncrDetail
	ScOrder                     scOrder
	ScOrderUserInfo             scOrderUserInfo
	ScOrderUserType             scOrderUserType
	SmallGamesValidDailyBet     smallGamesValidDailyBet
	SnakeAdminAction            snakeAdminAction
	SnakeNode                   snakeNode
	SnakeRecordAction           snakeRecordAction
	SnakeRole                   snakeRole
	SnakeUser                   snakeUser
	StrongboxBlacklist          strongboxBlacklist
	TForbidAccountLog           tForbidAccountLog
	TPlatformBalanceReport      tPlatformBalanceReport
	TUndepositAmountReport      tUndepositAmountReport
	TUnwithdrawn                tUnwithdrawn
	TipsGiftsDetail             tipsGiftsDetail
	TipsObtainedRecord          tipsObtainedRecord
	Toolpay                     toolpay
	UIDClubChange               uIDClubChange
	UserClassMonthStat          userClassMonthStat
	UserEveryLevelHandInfo      userEveryLevelHandInfo
	UserGame                    userGame
	UserGuessCfgDatum           userGuessCfgDatum
	UserPlayedMonthStat         userPlayedMonthStat
	VideoboyDatum               videoboyDatum
	VideoboyGameEnd             videoboyGameEnd
	VideoboyRevertNoendround    videoboyRevertNoendround
	VideoboyRevertRound         videoboyRevertRound
	VideoboyRoom                videoboyRoom
	VideoboyRoomAlarmRecord     videoboyRoomAlarmRecord
	VideoboyRoomMoneyDaily      videoboyRoomMoneyDaily
	VoidBet                     voidBet
	ZoomUIDIncomeDaily          zoomUIDIncomeDaily
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                          db,
		AmountLimit:                 q.AmountLimit.clone(db),
		AmountLimitDetail:           q.AmountLimitDetail.clone(db),
		AofUIDLuckdrawDetail:        q.AofUIDLuckdrawDetail.clone(db),
		AofUIDTransIncomeDetail:     q.AofUIDTransIncomeDetail.clone(db),
		ChargeLoss:                  q.ChargeLoss.clone(db),
		Club2alliMonthyContr:        q.Club2alliMonthyContr.clone(db),
		CoinAPILog:                  q.CoinAPILog.clone(db),
		CoinAdminErrorPwdRecord:     q.CoinAdminErrorPwdRecord.clone(db),
		CowboyGameEnd:               q.CowboyGameEnd.clone(db),
		CowboyRoom:                  q.CowboyRoom.clone(db),
		CowboyRoomAlarmRecord:       q.CowboyRoomAlarmRecord.clone(db),
		CowboyRoomMoneyDaily:        q.CowboyRoomMoneyDaily.clone(db),
		CowboyRoundBetDetail:        q.CowboyRoundBetDetail.clone(db),
		CowbyoyRoomAlarmRecord:      q.CowbyoyRoomAlarmRecord.clone(db),
		CowbyoyRoomMoneyDaily:       q.CowbyoyRoomMoneyDaily.clone(db),
		DailyGamehand:               q.DailyGamehand.clone(db),
		DailyUsdtInfo:               q.DailyUsdtInfo.clone(db),
		DeviceinfoRecord:            q.DeviceinfoRecord.clone(db),
		DomainReport:                q.DomainReport.clone(db),
		DtbCfdSyncDaily:             q.DtbCfdSyncDaily.clone(db),
		DtbDailyratioRecord:         q.DtbDailyratioRecord.clone(db),
		DtbHabaSyncDaily:            q.DtbHabaSyncDaily.clone(db),
		EveryLevelGameCensu:         q.EveryLevelGameCensu.clone(db),
		FairplayEmail:               q.FairplayEmail.clone(db),
		FairplayRecord:              q.FairplayRecord.clone(db),
		FairplayRecordAction:        q.FairplayRecordAction.clone(db),
		FairplayReport:              q.FairplayReport.clone(db),
		GameCoinInventoryIncrDetail: q.GameCoinInventoryIncrDetail.clone(db),
		GameCoinOrder:               q.GameCoinOrder.clone(db),
		GameCoinOrderUserInfo:       q.GameCoinOrderUserInfo.clone(db),
		GameCoinOrderUserType:       q.GameCoinOrderUserType.clone(db),
		GoldChangeDatum:             q.GoldChangeDatum.clone(db),
		GoldCoinInventoryIncrDetail: q.GoldCoinInventoryIncrDetail.clone(db),
		GoldCoinOrder:               q.GoldCoinOrder.clone(db),
		GoldCoinOrderUserInfo:       q.GoldCoinOrderUserInfo.clone(db),
		GoldCoinOrderUserType:       q.GoldCoinOrderUserType.clone(db),
		GoldcoinInventory:           q.GoldcoinInventory.clone(db),
		HandinfoRecord:              q.HandinfoRecord.clone(db),
		HumanboyDatum:               q.HumanboyDatum.clone(db),
		HumanboyGameEnd:             q.HumanboyGameEnd.clone(db),
		HumanboyPlayGameRecord:      q.HumanboyPlayGameRecord.clone(db),
		HumanboyRoom:                q.HumanboyRoom.clone(db),
		HumanboyRoomAlarmRecord:     q.HumanboyRoomAlarmRecord.clone(db),
		HumanboyRoomMoneyDaily:      q.HumanboyRoomMoneyDaily.clone(db),
		KickoffJackpotRecord:        q.KickoffJackpotRecord.clone(db),
		ManuallyCreateRoom:          q.ManuallyCreateRoom.clone(db),
		MemeDaily:                   q.MemeDaily.clone(db),
		MemePropsIncrDetail:         q.MemePropsIncrDetail.clone(db),
		MemePropsLog:                q.MemePropsLog.clone(db),
		MttRefundRecord:             q.MttRefundRecord.clone(db),
		MultiplayerBrush:            q.MultiplayerBrush.clone(db),
		MultiplayerBrushDetail:      q.MultiplayerBrushDetail.clone(db),
		ObFetchHistory:              q.ObFetchHistory.clone(db),
		ObOnlineBalance:             q.ObOnlineBalance.clone(db),
		PlatUserDailyContr:          q.PlatUserDailyContr.clone(db),
		PointInventoryIncrDetail:    q.PointInventoryIncrDetail.clone(db),
		PointOrder:                  q.PointOrder.clone(db),
		PointOrderUserInfo:          q.PointOrderUserInfo.clone(db),
		PointOrderUserType:          q.PointOrderUserType.clone(db),
		PokerGameEnd:                q.PokerGameEnd.clone(db),
		PokerRoom:                   q.PokerRoom.clone(db),
		PokerRoomAlarmRecord:        q.PokerRoomAlarmRecord.clone(db),
		PokerRoomMoneyDaily:         q.PokerRoomMoneyDaily.clone(db),
		PpFetchHistory:              q.PpFetchHistory.clone(db),
		ScFinanceReport:             q.ScFinanceReport.clone(db),
		ScInventoryIncrDetail:       q.ScInventoryIncrDetail.clone(db),
		ScOrder:                     q.ScOrder.clone(db),
		ScOrderUserInfo:             q.ScOrderUserInfo.clone(db),
		ScOrderUserType:             q.ScOrderUserType.clone(db),
		SmallGamesValidDailyBet:     q.SmallGamesValidDailyBet.clone(db),
		SnakeAdminAction:            q.SnakeAdminAction.clone(db),
		SnakeNode:                   q.SnakeNode.clone(db),
		SnakeRecordAction:           q.SnakeRecordAction.clone(db),
		SnakeRole:                   q.SnakeRole.clone(db),
		SnakeUser:                   q.SnakeUser.clone(db),
		StrongboxBlacklist:          q.StrongboxBlacklist.clone(db),
		TForbidAccountLog:           q.TForbidAccountLog.clone(db),
		TPlatformBalanceReport:      q.TPlatformBalanceReport.clone(db),
		TUndepositAmountReport:      q.TUndepositAmountReport.clone(db),
		TUnwithdrawn:                q.TUnwithdrawn.clone(db),
		TipsGiftsDetail:             q.TipsGiftsDetail.clone(db),
		TipsObtainedRecord:          q.TipsObtainedRecord.clone(db),
		Toolpay:                     q.Toolpay.clone(db),
		UIDClubChange:               q.UIDClubChange.clone(db),
		UserClassMonthStat:          q.UserClassMonthStat.clone(db),
		UserEveryLevelHandInfo:      q.UserEveryLevelHandInfo.clone(db),
		UserGame:                    q.UserGame.clone(db),
		UserGuessCfgDatum:           q.UserGuessCfgDatum.clone(db),
		UserPlayedMonthStat:         q.UserPlayedMonthStat.clone(db),
		VideoboyDatum:               q.VideoboyDatum.clone(db),
		VideoboyGameEnd:             q.VideoboyGameEnd.clone(db),
		VideoboyRevertNoendround:    q.VideoboyRevertNoendround.clone(db),
		VideoboyRevertRound:         q.VideoboyRevertRound.clone(db),
		VideoboyRoom:                q.VideoboyRoom.clone(db),
		VideoboyRoomAlarmRecord:     q.VideoboyRoomAlarmRecord.clone(db),
		VideoboyRoomMoneyDaily:      q.VideoboyRoomMoneyDaily.clone(db),
		VoidBet:                     q.VoidBet.clone(db),
		ZoomUIDIncomeDaily:          q.ZoomUIDIncomeDaily.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                          db,
		AmountLimit:                 q.AmountLimit.replaceDB(db),
		AmountLimitDetail:           q.AmountLimitDetail.replaceDB(db),
		AofUIDLuckdrawDetail:        q.AofUIDLuckdrawDetail.replaceDB(db),
		AofUIDTransIncomeDetail:     q.AofUIDTransIncomeDetail.replaceDB(db),
		ChargeLoss:                  q.ChargeLoss.replaceDB(db),
		Club2alliMonthyContr:        q.Club2alliMonthyContr.replaceDB(db),
		CoinAPILog:                  q.CoinAPILog.replaceDB(db),
		CoinAdminErrorPwdRecord:     q.CoinAdminErrorPwdRecord.replaceDB(db),
		CowboyGameEnd:               q.CowboyGameEnd.replaceDB(db),
		CowboyRoom:                  q.CowboyRoom.replaceDB(db),
		CowboyRoomAlarmRecord:       q.CowboyRoomAlarmRecord.replaceDB(db),
		CowboyRoomMoneyDaily:        q.CowboyRoomMoneyDaily.replaceDB(db),
		CowboyRoundBetDetail:        q.CowboyRoundBetDetail.replaceDB(db),
		CowbyoyRoomAlarmRecord:      q.CowbyoyRoomAlarmRecord.replaceDB(db),
		CowbyoyRoomMoneyDaily:       q.CowbyoyRoomMoneyDaily.replaceDB(db),
		DailyGamehand:               q.DailyGamehand.replaceDB(db),
		DailyUsdtInfo:               q.DailyUsdtInfo.replaceDB(db),
		DeviceinfoRecord:            q.DeviceinfoRecord.replaceDB(db),
		DomainReport:                q.DomainReport.replaceDB(db),
		DtbCfdSyncDaily:             q.DtbCfdSyncDaily.replaceDB(db),
		DtbDailyratioRecord:         q.DtbDailyratioRecord.replaceDB(db),
		DtbHabaSyncDaily:            q.DtbHabaSyncDaily.replaceDB(db),
		EveryLevelGameCensu:         q.EveryLevelGameCensu.replaceDB(db),
		FairplayEmail:               q.FairplayEmail.replaceDB(db),
		FairplayRecord:              q.FairplayRecord.replaceDB(db),
		FairplayRecordAction:        q.FairplayRecordAction.replaceDB(db),
		FairplayReport:              q.FairplayReport.replaceDB(db),
		GameCoinInventoryIncrDetail: q.GameCoinInventoryIncrDetail.replaceDB(db),
		GameCoinOrder:               q.GameCoinOrder.replaceDB(db),
		GameCoinOrderUserInfo:       q.GameCoinOrderUserInfo.replaceDB(db),
		GameCoinOrderUserType:       q.GameCoinOrderUserType.replaceDB(db),
		GoldChangeDatum:             q.GoldChangeDatum.replaceDB(db),
		GoldCoinInventoryIncrDetail: q.GoldCoinInventoryIncrDetail.replaceDB(db),
		GoldCoinOrder:               q.GoldCoinOrder.replaceDB(db),
		GoldCoinOrderUserInfo:       q.GoldCoinOrderUserInfo.replaceDB(db),
		GoldCoinOrderUserType:       q.GoldCoinOrderUserType.replaceDB(db),
		GoldcoinInventory:           q.GoldcoinInventory.replaceDB(db),
		HandinfoRecord:              q.HandinfoRecord.replaceDB(db),
		HumanboyDatum:               q.HumanboyDatum.replaceDB(db),
		HumanboyGameEnd:             q.HumanboyGameEnd.replaceDB(db),
		HumanboyPlayGameRecord:      q.HumanboyPlayGameRecord.replaceDB(db),
		HumanboyRoom:                q.HumanboyRoom.replaceDB(db),
		HumanboyRoomAlarmRecord:     q.HumanboyRoomAlarmRecord.replaceDB(db),
		HumanboyRoomMoneyDaily:      q.HumanboyRoomMoneyDaily.replaceDB(db),
		KickoffJackpotRecord:        q.KickoffJackpotRecord.replaceDB(db),
		ManuallyCreateRoom:          q.ManuallyCreateRoom.replaceDB(db),
		MemeDaily:                   q.MemeDaily.replaceDB(db),
		MemePropsIncrDetail:         q.MemePropsIncrDetail.replaceDB(db),
		MemePropsLog:                q.MemePropsLog.replaceDB(db),
		MttRefundRecord:             q.MttRefundRecord.replaceDB(db),
		MultiplayerBrush:            q.MultiplayerBrush.replaceDB(db),
		MultiplayerBrushDetail:      q.MultiplayerBrushDetail.replaceDB(db),
		ObFetchHistory:              q.ObFetchHistory.replaceDB(db),
		ObOnlineBalance:             q.ObOnlineBalance.replaceDB(db),
		PlatUserDailyContr:          q.PlatUserDailyContr.replaceDB(db),
		PointInventoryIncrDetail:    q.PointInventoryIncrDetail.replaceDB(db),
		PointOrder:                  q.PointOrder.replaceDB(db),
		PointOrderUserInfo:          q.PointOrderUserInfo.replaceDB(db),
		PointOrderUserType:          q.PointOrderUserType.replaceDB(db),
		PokerGameEnd:                q.PokerGameEnd.replaceDB(db),
		PokerRoom:                   q.PokerRoom.replaceDB(db),
		PokerRoomAlarmRecord:        q.PokerRoomAlarmRecord.replaceDB(db),
		PokerRoomMoneyDaily:         q.PokerRoomMoneyDaily.replaceDB(db),
		PpFetchHistory:              q.PpFetchHistory.replaceDB(db),
		ScFinanceReport:             q.ScFinanceReport.replaceDB(db),
		ScInventoryIncrDetail:       q.ScInventoryIncrDetail.replaceDB(db),
		ScOrder:                     q.ScOrder.replaceDB(db),
		ScOrderUserInfo:             q.ScOrderUserInfo.replaceDB(db),
		ScOrderUserType:             q.ScOrderUserType.replaceDB(db),
		SmallGamesValidDailyBet:     q.SmallGamesValidDailyBet.replaceDB(db),
		SnakeAdminAction:            q.SnakeAdminAction.replaceDB(db),
		SnakeNode:                   q.SnakeNode.replaceDB(db),
		SnakeRecordAction:           q.SnakeRecordAction.replaceDB(db),
		SnakeRole:                   q.SnakeRole.replaceDB(db),
		SnakeUser:                   q.SnakeUser.replaceDB(db),
		StrongboxBlacklist:          q.StrongboxBlacklist.replaceDB(db),
		TForbidAccountLog:           q.TForbidAccountLog.replaceDB(db),
		TPlatformBalanceReport:      q.TPlatformBalanceReport.replaceDB(db),
		TUndepositAmountReport:      q.TUndepositAmountReport.replaceDB(db),
		TUnwithdrawn:                q.TUnwithdrawn.replaceDB(db),
		TipsGiftsDetail:             q.TipsGiftsDetail.replaceDB(db),
		TipsObtainedRecord:          q.TipsObtainedRecord.replaceDB(db),
		Toolpay:                     q.Toolpay.replaceDB(db),
		UIDClubChange:               q.UIDClubChange.replaceDB(db),
		UserClassMonthStat:          q.UserClassMonthStat.replaceDB(db),
		UserEveryLevelHandInfo:      q.UserEveryLevelHandInfo.replaceDB(db),
		UserGame:                    q.UserGame.replaceDB(db),
		UserGuessCfgDatum:           q.UserGuessCfgDatum.replaceDB(db),
		UserPlayedMonthStat:         q.UserPlayedMonthStat.replaceDB(db),
		VideoboyDatum:               q.VideoboyDatum.replaceDB(db),
		VideoboyGameEnd:             q.VideoboyGameEnd.replaceDB(db),
		VideoboyRevertNoendround:    q.VideoboyRevertNoendround.replaceDB(db),
		VideoboyRevertRound:         q.VideoboyRevertRound.replaceDB(db),
		VideoboyRoom:                q.VideoboyRoom.replaceDB(db),
		VideoboyRoomAlarmRecord:     q.VideoboyRoomAlarmRecord.replaceDB(db),
		VideoboyRoomMoneyDaily:      q.VideoboyRoomMoneyDaily.replaceDB(db),
		VoidBet:                     q.VoidBet.replaceDB(db),
		ZoomUIDIncomeDaily:          q.ZoomUIDIncomeDaily.replaceDB(db),
	}
}

type queryCtx struct {
	AmountLimit                 IAmountLimitDo
	AmountLimitDetail           IAmountLimitDetailDo
	AofUIDLuckdrawDetail        IAofUIDLuckdrawDetailDo
	AofUIDTransIncomeDetail     IAofUIDTransIncomeDetailDo
	ChargeLoss                  IChargeLossDo
	Club2alliMonthyContr        IClub2alliMonthyContrDo
	CoinAPILog                  ICoinAPILogDo
	CoinAdminErrorPwdRecord     ICoinAdminErrorPwdRecordDo
	CowboyGameEnd               ICowboyGameEndDo
	CowboyRoom                  ICowboyRoomDo
	CowboyRoomAlarmRecord       ICowboyRoomAlarmRecordDo
	CowboyRoomMoneyDaily        ICowboyRoomMoneyDailyDo
	CowboyRoundBetDetail        ICowboyRoundBetDetailDo
	CowbyoyRoomAlarmRecord      ICowbyoyRoomAlarmRecordDo
	CowbyoyRoomMoneyDaily       ICowbyoyRoomMoneyDailyDo
	DailyGamehand               IDailyGamehandDo
	DailyUsdtInfo               IDailyUsdtInfoDo
	DeviceinfoRecord            IDeviceinfoRecordDo
	DomainReport                IDomainReportDo
	DtbCfdSyncDaily             IDtbCfdSyncDailyDo
	DtbDailyratioRecord         IDtbDailyratioRecordDo
	DtbHabaSyncDaily            IDtbHabaSyncDailyDo
	EveryLevelGameCensu         IEveryLevelGameCensuDo
	FairplayEmail               IFairplayEmailDo
	FairplayRecord              IFairplayRecordDo
	FairplayRecordAction        IFairplayRecordActionDo
	FairplayReport              IFairplayReportDo
	GameCoinInventoryIncrDetail IGameCoinInventoryIncrDetailDo
	GameCoinOrder               IGameCoinOrderDo
	GameCoinOrderUserInfo       IGameCoinOrderUserInfoDo
	GameCoinOrderUserType       IGameCoinOrderUserTypeDo
	GoldChangeDatum             IGoldChangeDatumDo
	GoldCoinInventoryIncrDetail IGoldCoinInventoryIncrDetailDo
	GoldCoinOrder               IGoldCoinOrderDo
	GoldCoinOrderUserInfo       IGoldCoinOrderUserInfoDo
	GoldCoinOrderUserType       IGoldCoinOrderUserTypeDo
	GoldcoinInventory           IGoldcoinInventoryDo
	HandinfoRecord              IHandinfoRecordDo
	HumanboyDatum               IHumanboyDatumDo
	HumanboyGameEnd             IHumanboyGameEndDo
	HumanboyPlayGameRecord      IHumanboyPlayGameRecordDo
	HumanboyRoom                IHumanboyRoomDo
	HumanboyRoomAlarmRecord     IHumanboyRoomAlarmRecordDo
	HumanboyRoomMoneyDaily      IHumanboyRoomMoneyDailyDo
	KickoffJackpotRecord        IKickoffJackpotRecordDo
	ManuallyCreateRoom          IManuallyCreateRoomDo
	MemeDaily                   IMemeDailyDo
	MemePropsIncrDetail         IMemePropsIncrDetailDo
	MemePropsLog                IMemePropsLogDo
	MttRefundRecord             IMttRefundRecordDo
	MultiplayerBrush            IMultiplayerBrushDo
	MultiplayerBrushDetail      IMultiplayerBrushDetailDo
	ObFetchHistory              IObFetchHistoryDo
	ObOnlineBalance             IObOnlineBalanceDo
	PlatUserDailyContr          IPlatUserDailyContrDo
	PointInventoryIncrDetail    IPointInventoryIncrDetailDo
	PointOrder                  IPointOrderDo
	PointOrderUserInfo          IPointOrderUserInfoDo
	PointOrderUserType          IPointOrderUserTypeDo
	PokerGameEnd                IPokerGameEndDo
	PokerRoom                   IPokerRoomDo
	PokerRoomAlarmRecord        IPokerRoomAlarmRecordDo
	PokerRoomMoneyDaily         IPokerRoomMoneyDailyDo
	PpFetchHistory              IPpFetchHistoryDo
	ScFinanceReport             IScFinanceReportDo
	ScInventoryIncrDetail       IScInventoryIncrDetailDo
	ScOrder                     IScOrderDo
	ScOrderUserInfo             IScOrderUserInfoDo
	ScOrderUserType             IScOrderUserTypeDo
	SmallGamesValidDailyBet     ISmallGamesValidDailyBetDo
	SnakeAdminAction            ISnakeAdminActionDo
	SnakeNode                   ISnakeNodeDo
	SnakeRecordAction           ISnakeRecordActionDo
	SnakeRole                   ISnakeRoleDo
	SnakeUser                   ISnakeUserDo
	StrongboxBlacklist          IStrongboxBlacklistDo
	TForbidAccountLog           ITForbidAccountLogDo
	TPlatformBalanceReport      ITPlatformBalanceReportDo
	TUndepositAmountReport      ITUndepositAmountReportDo
	TUnwithdrawn                ITUnwithdrawnDo
	TipsGiftsDetail             ITipsGiftsDetailDo
	TipsObtainedRecord          ITipsObtainedRecordDo
	Toolpay                     IToolpayDo
	UIDClubChange               IUIDClubChangeDo
	UserClassMonthStat          IUserClassMonthStatDo
	UserEveryLevelHandInfo      IUserEveryLevelHandInfoDo
	UserGame                    IUserGameDo
	UserGuessCfgDatum           IUserGuessCfgDatumDo
	UserPlayedMonthStat         IUserPlayedMonthStatDo
	VideoboyDatum               IVideoboyDatumDo
	VideoboyGameEnd             IVideoboyGameEndDo
	VideoboyRevertNoendround    IVideoboyRevertNoendroundDo
	VideoboyRevertRound         IVideoboyRevertRoundDo
	VideoboyRoom                IVideoboyRoomDo
	VideoboyRoomAlarmRecord     IVideoboyRoomAlarmRecordDo
	VideoboyRoomMoneyDaily      IVideoboyRoomMoneyDailyDo
	VoidBet                     IVoidBetDo
	ZoomUIDIncomeDaily          IZoomUIDIncomeDailyDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AmountLimit:                 q.AmountLimit.WithContext(ctx),
		AmountLimitDetail:           q.AmountLimitDetail.WithContext(ctx),
		AofUIDLuckdrawDetail:        q.AofUIDLuckdrawDetail.WithContext(ctx),
		AofUIDTransIncomeDetail:     q.AofUIDTransIncomeDetail.WithContext(ctx),
		ChargeLoss:                  q.ChargeLoss.WithContext(ctx),
		Club2alliMonthyContr:        q.Club2alliMonthyContr.WithContext(ctx),
		CoinAPILog:                  q.CoinAPILog.WithContext(ctx),
		CoinAdminErrorPwdRecord:     q.CoinAdminErrorPwdRecord.WithContext(ctx),
		CowboyGameEnd:               q.CowboyGameEnd.WithContext(ctx),
		CowboyRoom:                  q.CowboyRoom.WithContext(ctx),
		CowboyRoomAlarmRecord:       q.CowboyRoomAlarmRecord.WithContext(ctx),
		CowboyRoomMoneyDaily:        q.CowboyRoomMoneyDaily.WithContext(ctx),
		CowboyRoundBetDetail:        q.CowboyRoundBetDetail.WithContext(ctx),
		CowbyoyRoomAlarmRecord:      q.CowbyoyRoomAlarmRecord.WithContext(ctx),
		CowbyoyRoomMoneyDaily:       q.CowbyoyRoomMoneyDaily.WithContext(ctx),
		DailyGamehand:               q.DailyGamehand.WithContext(ctx),
		DailyUsdtInfo:               q.DailyUsdtInfo.WithContext(ctx),
		DeviceinfoRecord:            q.DeviceinfoRecord.WithContext(ctx),
		DomainReport:                q.DomainReport.WithContext(ctx),
		DtbCfdSyncDaily:             q.DtbCfdSyncDaily.WithContext(ctx),
		DtbDailyratioRecord:         q.DtbDailyratioRecord.WithContext(ctx),
		DtbHabaSyncDaily:            q.DtbHabaSyncDaily.WithContext(ctx),
		EveryLevelGameCensu:         q.EveryLevelGameCensu.WithContext(ctx),
		FairplayEmail:               q.FairplayEmail.WithContext(ctx),
		FairplayRecord:              q.FairplayRecord.WithContext(ctx),
		FairplayRecordAction:        q.FairplayRecordAction.WithContext(ctx),
		FairplayReport:              q.FairplayReport.WithContext(ctx),
		GameCoinInventoryIncrDetail: q.GameCoinInventoryIncrDetail.WithContext(ctx),
		GameCoinOrder:               q.GameCoinOrder.WithContext(ctx),
		GameCoinOrderUserInfo:       q.GameCoinOrderUserInfo.WithContext(ctx),
		GameCoinOrderUserType:       q.GameCoinOrderUserType.WithContext(ctx),
		GoldChangeDatum:             q.GoldChangeDatum.WithContext(ctx),
		GoldCoinInventoryIncrDetail: q.GoldCoinInventoryIncrDetail.WithContext(ctx),
		GoldCoinOrder:               q.GoldCoinOrder.WithContext(ctx),
		GoldCoinOrderUserInfo:       q.GoldCoinOrderUserInfo.WithContext(ctx),
		GoldCoinOrderUserType:       q.GoldCoinOrderUserType.WithContext(ctx),
		GoldcoinInventory:           q.GoldcoinInventory.WithContext(ctx),
		HandinfoRecord:              q.HandinfoRecord.WithContext(ctx),
		HumanboyDatum:               q.HumanboyDatum.WithContext(ctx),
		HumanboyGameEnd:             q.HumanboyGameEnd.WithContext(ctx),
		HumanboyPlayGameRecord:      q.HumanboyPlayGameRecord.WithContext(ctx),
		HumanboyRoom:                q.HumanboyRoom.WithContext(ctx),
		HumanboyRoomAlarmRecord:     q.HumanboyRoomAlarmRecord.WithContext(ctx),
		HumanboyRoomMoneyDaily:      q.HumanboyRoomMoneyDaily.WithContext(ctx),
		KickoffJackpotRecord:        q.KickoffJackpotRecord.WithContext(ctx),
		ManuallyCreateRoom:          q.ManuallyCreateRoom.WithContext(ctx),
		MemeDaily:                   q.MemeDaily.WithContext(ctx),
		MemePropsIncrDetail:         q.MemePropsIncrDetail.WithContext(ctx),
		MemePropsLog:                q.MemePropsLog.WithContext(ctx),
		MttRefundRecord:             q.MttRefundRecord.WithContext(ctx),
		MultiplayerBrush:            q.MultiplayerBrush.WithContext(ctx),
		MultiplayerBrushDetail:      q.MultiplayerBrushDetail.WithContext(ctx),
		ObFetchHistory:              q.ObFetchHistory.WithContext(ctx),
		ObOnlineBalance:             q.ObOnlineBalance.WithContext(ctx),
		PlatUserDailyContr:          q.PlatUserDailyContr.WithContext(ctx),
		PointInventoryIncrDetail:    q.PointInventoryIncrDetail.WithContext(ctx),
		PointOrder:                  q.PointOrder.WithContext(ctx),
		PointOrderUserInfo:          q.PointOrderUserInfo.WithContext(ctx),
		PointOrderUserType:          q.PointOrderUserType.WithContext(ctx),
		PokerGameEnd:                q.PokerGameEnd.WithContext(ctx),
		PokerRoom:                   q.PokerRoom.WithContext(ctx),
		PokerRoomAlarmRecord:        q.PokerRoomAlarmRecord.WithContext(ctx),
		PokerRoomMoneyDaily:         q.PokerRoomMoneyDaily.WithContext(ctx),
		PpFetchHistory:              q.PpFetchHistory.WithContext(ctx),
		ScFinanceReport:             q.ScFinanceReport.WithContext(ctx),
		ScInventoryIncrDetail:       q.ScInventoryIncrDetail.WithContext(ctx),
		ScOrder:                     q.ScOrder.WithContext(ctx),
		ScOrderUserInfo:             q.ScOrderUserInfo.WithContext(ctx),
		ScOrderUserType:             q.ScOrderUserType.WithContext(ctx),
		SmallGamesValidDailyBet:     q.SmallGamesValidDailyBet.WithContext(ctx),
		SnakeAdminAction:            q.SnakeAdminAction.WithContext(ctx),
		SnakeNode:                   q.SnakeNode.WithContext(ctx),
		SnakeRecordAction:           q.SnakeRecordAction.WithContext(ctx),
		SnakeRole:                   q.SnakeRole.WithContext(ctx),
		SnakeUser:                   q.SnakeUser.WithContext(ctx),
		StrongboxBlacklist:          q.StrongboxBlacklist.WithContext(ctx),
		TForbidAccountLog:           q.TForbidAccountLog.WithContext(ctx),
		TPlatformBalanceReport:      q.TPlatformBalanceReport.WithContext(ctx),
		TUndepositAmountReport:      q.TUndepositAmountReport.WithContext(ctx),
		TUnwithdrawn:                q.TUnwithdrawn.WithContext(ctx),
		TipsGiftsDetail:             q.TipsGiftsDetail.WithContext(ctx),
		TipsObtainedRecord:          q.TipsObtainedRecord.WithContext(ctx),
		Toolpay:                     q.Toolpay.WithContext(ctx),
		UIDClubChange:               q.UIDClubChange.WithContext(ctx),
		UserClassMonthStat:          q.UserClassMonthStat.WithContext(ctx),
		UserEveryLevelHandInfo:      q.UserEveryLevelHandInfo.WithContext(ctx),
		UserGame:                    q.UserGame.WithContext(ctx),
		UserGuessCfgDatum:           q.UserGuessCfgDatum.WithContext(ctx),
		UserPlayedMonthStat:         q.UserPlayedMonthStat.WithContext(ctx),
		VideoboyDatum:               q.VideoboyDatum.WithContext(ctx),
		VideoboyGameEnd:             q.VideoboyGameEnd.WithContext(ctx),
		VideoboyRevertNoendround:    q.VideoboyRevertNoendround.WithContext(ctx),
		VideoboyRevertRound:         q.VideoboyRevertRound.WithContext(ctx),
		VideoboyRoom:                q.VideoboyRoom.WithContext(ctx),
		VideoboyRoomAlarmRecord:     q.VideoboyRoomAlarmRecord.WithContext(ctx),
		VideoboyRoomMoneyDaily:      q.VideoboyRoomMoneyDaily.WithContext(ctx),
		VoidBet:                     q.VoidBet.WithContext(ctx),
		ZoomUIDIncomeDaily:          q.ZoomUIDIncomeDaily.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
