// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newGoldCoinOrderUserType(db *gorm.DB, opts ...gen.DOOption) goldCoinOrderUserType {
	_goldCoinOrderUserType := goldCoinOrderUserType{}

	_goldCoinOrderUserType.goldCoinOrderUserTypeDo.UseDB(db, opts...)
	_goldCoinOrderUserType.goldCoinOrderUserTypeDo.UseModel(&model.GoldCoinOrderUserType{})

	tableName := _goldCoinOrderUserType.goldCoinOrderUserTypeDo.TableName()
	_goldCoinOrderUserType.ALL = field.NewAsterisk(tableName)
	_goldCoinOrderUserType.ID = field.NewUint32(tableName, "id")
	_goldCoinOrderUserType.UserTypeName = field.NewString(tableName, "user_type_name")
	_goldCoinOrderUserType.IsInvalid = field.NewBool(tableName, "is_invalid")

	_goldCoinOrderUserType.fillFieldMap()

	return _goldCoinOrderUserType
}

// goldCoinOrderUserType 金币订单的用途
type goldCoinOrderUserType struct {
	goldCoinOrderUserTypeDo

	ALL          field.Asterisk
	ID           field.Uint32 // 数据
	UserTypeName field.String // 名称
	IsInvalid    field.Bool   // 用途是否有效 0-有效 1-无效

	fieldMap map[string]field.Expr
}

func (g goldCoinOrderUserType) Table(newTableName string) *goldCoinOrderUserType {
	g.goldCoinOrderUserTypeDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goldCoinOrderUserType) As(alias string) *goldCoinOrderUserType {
	g.goldCoinOrderUserTypeDo.DO = *(g.goldCoinOrderUserTypeDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goldCoinOrderUserType) updateTableName(table string) *goldCoinOrderUserType {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint32(table, "id")
	g.UserTypeName = field.NewString(table, "user_type_name")
	g.IsInvalid = field.NewBool(table, "is_invalid")

	g.fillFieldMap()

	return g
}

func (g *goldCoinOrderUserType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goldCoinOrderUserType) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 3)
	g.fieldMap["id"] = g.ID
	g.fieldMap["user_type_name"] = g.UserTypeName
	g.fieldMap["is_invalid"] = g.IsInvalid
}

func (g goldCoinOrderUserType) clone(db *gorm.DB) goldCoinOrderUserType {
	g.goldCoinOrderUserTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goldCoinOrderUserType) replaceDB(db *gorm.DB) goldCoinOrderUserType {
	g.goldCoinOrderUserTypeDo.ReplaceDB(db)
	return g
}

type goldCoinOrderUserTypeDo struct{ gen.DO }

type IGoldCoinOrderUserTypeDo interface {
	gen.SubQuery
	Debug() IGoldCoinOrderUserTypeDo
	WithContext(ctx context.Context) IGoldCoinOrderUserTypeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGoldCoinOrderUserTypeDo
	WriteDB() IGoldCoinOrderUserTypeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGoldCoinOrderUserTypeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGoldCoinOrderUserTypeDo
	Not(conds ...gen.Condition) IGoldCoinOrderUserTypeDo
	Or(conds ...gen.Condition) IGoldCoinOrderUserTypeDo
	Select(conds ...field.Expr) IGoldCoinOrderUserTypeDo
	Where(conds ...gen.Condition) IGoldCoinOrderUserTypeDo
	Order(conds ...field.Expr) IGoldCoinOrderUserTypeDo
	Distinct(cols ...field.Expr) IGoldCoinOrderUserTypeDo
	Omit(cols ...field.Expr) IGoldCoinOrderUserTypeDo
	Join(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserTypeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserTypeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserTypeDo
	Group(cols ...field.Expr) IGoldCoinOrderUserTypeDo
	Having(conds ...gen.Condition) IGoldCoinOrderUserTypeDo
	Limit(limit int) IGoldCoinOrderUserTypeDo
	Offset(offset int) IGoldCoinOrderUserTypeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGoldCoinOrderUserTypeDo
	Unscoped() IGoldCoinOrderUserTypeDo
	Create(values ...*model.GoldCoinOrderUserType) error
	CreateInBatches(values []*model.GoldCoinOrderUserType, batchSize int) error
	Save(values ...*model.GoldCoinOrderUserType) error
	First() (*model.GoldCoinOrderUserType, error)
	Take() (*model.GoldCoinOrderUserType, error)
	Last() (*model.GoldCoinOrderUserType, error)
	Find() ([]*model.GoldCoinOrderUserType, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoldCoinOrderUserType, err error)
	FindInBatches(result *[]*model.GoldCoinOrderUserType, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GoldCoinOrderUserType) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGoldCoinOrderUserTypeDo
	Assign(attrs ...field.AssignExpr) IGoldCoinOrderUserTypeDo
	Joins(fields ...field.RelationField) IGoldCoinOrderUserTypeDo
	Preload(fields ...field.RelationField) IGoldCoinOrderUserTypeDo
	FirstOrInit() (*model.GoldCoinOrderUserType, error)
	FirstOrCreate() (*model.GoldCoinOrderUserType, error)
	FindByPage(offset int, limit int) (result []*model.GoldCoinOrderUserType, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGoldCoinOrderUserTypeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g goldCoinOrderUserTypeDo) Debug() IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Debug())
}

func (g goldCoinOrderUserTypeDo) WithContext(ctx context.Context) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goldCoinOrderUserTypeDo) ReadDB() IGoldCoinOrderUserTypeDo {
	return g.Clauses(dbresolver.Read)
}

func (g goldCoinOrderUserTypeDo) WriteDB() IGoldCoinOrderUserTypeDo {
	return g.Clauses(dbresolver.Write)
}

func (g goldCoinOrderUserTypeDo) Session(config *gorm.Session) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Session(config))
}

func (g goldCoinOrderUserTypeDo) Clauses(conds ...clause.Expression) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goldCoinOrderUserTypeDo) Returning(value interface{}, columns ...string) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goldCoinOrderUserTypeDo) Not(conds ...gen.Condition) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goldCoinOrderUserTypeDo) Or(conds ...gen.Condition) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goldCoinOrderUserTypeDo) Select(conds ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goldCoinOrderUserTypeDo) Where(conds ...gen.Condition) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goldCoinOrderUserTypeDo) Order(conds ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goldCoinOrderUserTypeDo) Distinct(cols ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goldCoinOrderUserTypeDo) Omit(cols ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goldCoinOrderUserTypeDo) Join(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goldCoinOrderUserTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goldCoinOrderUserTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goldCoinOrderUserTypeDo) Group(cols ...field.Expr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goldCoinOrderUserTypeDo) Having(conds ...gen.Condition) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goldCoinOrderUserTypeDo) Limit(limit int) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goldCoinOrderUserTypeDo) Offset(offset int) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goldCoinOrderUserTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goldCoinOrderUserTypeDo) Unscoped() IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goldCoinOrderUserTypeDo) Create(values ...*model.GoldCoinOrderUserType) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goldCoinOrderUserTypeDo) CreateInBatches(values []*model.GoldCoinOrderUserType, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goldCoinOrderUserTypeDo) Save(values ...*model.GoldCoinOrderUserType) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goldCoinOrderUserTypeDo) First() (*model.GoldCoinOrderUserType, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserType), nil
	}
}

func (g goldCoinOrderUserTypeDo) Take() (*model.GoldCoinOrderUserType, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserType), nil
	}
}

func (g goldCoinOrderUserTypeDo) Last() (*model.GoldCoinOrderUserType, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserType), nil
	}
}

func (g goldCoinOrderUserTypeDo) Find() ([]*model.GoldCoinOrderUserType, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoldCoinOrderUserType), err
}

func (g goldCoinOrderUserTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoldCoinOrderUserType, err error) {
	buf := make([]*model.GoldCoinOrderUserType, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goldCoinOrderUserTypeDo) FindInBatches(result *[]*model.GoldCoinOrderUserType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goldCoinOrderUserTypeDo) Attrs(attrs ...field.AssignExpr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goldCoinOrderUserTypeDo) Assign(attrs ...field.AssignExpr) IGoldCoinOrderUserTypeDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goldCoinOrderUserTypeDo) Joins(fields ...field.RelationField) IGoldCoinOrderUserTypeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goldCoinOrderUserTypeDo) Preload(fields ...field.RelationField) IGoldCoinOrderUserTypeDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goldCoinOrderUserTypeDo) FirstOrInit() (*model.GoldCoinOrderUserType, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserType), nil
	}
}

func (g goldCoinOrderUserTypeDo) FirstOrCreate() (*model.GoldCoinOrderUserType, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserType), nil
	}
}

func (g goldCoinOrderUserTypeDo) FindByPage(offset int, limit int) (result []*model.GoldCoinOrderUserType, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goldCoinOrderUserTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goldCoinOrderUserTypeDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goldCoinOrderUserTypeDo) Delete(models ...*model.GoldCoinOrderUserType) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goldCoinOrderUserTypeDo) withDO(do gen.Dao) *goldCoinOrderUserTypeDo {
	g.DO = *do.(*gen.DO)
	return g
}
