// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newGoldCoinOrderUserInfo(db *gorm.DB, opts ...gen.DOOption) goldCoinOrderUserInfo {
	_goldCoinOrderUserInfo := goldCoinOrderUserInfo{}

	_goldCoinOrderUserInfo.goldCoinOrderUserInfoDo.UseDB(db, opts...)
	_goldCoinOrderUserInfo.goldCoinOrderUserInfoDo.UseModel(&model.GoldCoinOrderUserInfo{})

	tableName := _goldCoinOrderUserInfo.goldCoinOrderUserInfoDo.TableName()
	_goldCoinOrderUserInfo.ALL = field.NewAsterisk(tableName)
	_goldCoinOrderUserInfo.ID = field.NewUint64(tableName, "id")
	_goldCoinOrderUserInfo.CreateTime = field.NewInt64(tableName, "create_time")
	_goldCoinOrderUserInfo.Amount = field.NewInt64(tableName, "amount")
	_goldCoinOrderUserInfo.UserID = field.NewUint32(tableName, "user_id")
	_goldCoinOrderUserInfo.UserName = field.NewString(tableName, "user_name")
	_goldCoinOrderUserInfo.OrderID = field.NewUint64(tableName, "order_id")
	_goldCoinOrderUserInfo.Desc = field.NewString(tableName, "desc")
	_goldCoinOrderUserInfo.CoinType = field.NewInt32(tableName, "coin_type")

	_goldCoinOrderUserInfo.fillFieldMap()

	return _goldCoinOrderUserInfo
}

// goldCoinOrderUserInfo 金币订单玩家记录
type goldCoinOrderUserInfo struct {
	goldCoinOrderUserInfoDo

	ALL        field.Asterisk
	ID         field.Uint64 // 数据
	CreateTime field.Int64  // 时间
	Amount     field.Int64  // 金额
	UserID     field.Uint32
	UserName   field.String
	OrderID    field.Uint64
	Desc       field.String // 备注
	CoinType   field.Int32  // 币用途, 0 paid, 1 Promotional

	fieldMap map[string]field.Expr
}

func (g goldCoinOrderUserInfo) Table(newTableName string) *goldCoinOrderUserInfo {
	g.goldCoinOrderUserInfoDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g goldCoinOrderUserInfo) As(alias string) *goldCoinOrderUserInfo {
	g.goldCoinOrderUserInfoDo.DO = *(g.goldCoinOrderUserInfoDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *goldCoinOrderUserInfo) updateTableName(table string) *goldCoinOrderUserInfo {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint64(table, "id")
	g.CreateTime = field.NewInt64(table, "create_time")
	g.Amount = field.NewInt64(table, "amount")
	g.UserID = field.NewUint32(table, "user_id")
	g.UserName = field.NewString(table, "user_name")
	g.OrderID = field.NewUint64(table, "order_id")
	g.Desc = field.NewString(table, "desc")
	g.CoinType = field.NewInt32(table, "coin_type")

	g.fillFieldMap()

	return g
}

func (g *goldCoinOrderUserInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *goldCoinOrderUserInfo) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["create_time"] = g.CreateTime
	g.fieldMap["amount"] = g.Amount
	g.fieldMap["user_id"] = g.UserID
	g.fieldMap["user_name"] = g.UserName
	g.fieldMap["order_id"] = g.OrderID
	g.fieldMap["desc"] = g.Desc
	g.fieldMap["coin_type"] = g.CoinType
}

func (g goldCoinOrderUserInfo) clone(db *gorm.DB) goldCoinOrderUserInfo {
	g.goldCoinOrderUserInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g goldCoinOrderUserInfo) replaceDB(db *gorm.DB) goldCoinOrderUserInfo {
	g.goldCoinOrderUserInfoDo.ReplaceDB(db)
	return g
}

type goldCoinOrderUserInfoDo struct{ gen.DO }

type IGoldCoinOrderUserInfoDo interface {
	gen.SubQuery
	Debug() IGoldCoinOrderUserInfoDo
	WithContext(ctx context.Context) IGoldCoinOrderUserInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGoldCoinOrderUserInfoDo
	WriteDB() IGoldCoinOrderUserInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGoldCoinOrderUserInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGoldCoinOrderUserInfoDo
	Not(conds ...gen.Condition) IGoldCoinOrderUserInfoDo
	Or(conds ...gen.Condition) IGoldCoinOrderUserInfoDo
	Select(conds ...field.Expr) IGoldCoinOrderUserInfoDo
	Where(conds ...gen.Condition) IGoldCoinOrderUserInfoDo
	Order(conds ...field.Expr) IGoldCoinOrderUserInfoDo
	Distinct(cols ...field.Expr) IGoldCoinOrderUserInfoDo
	Omit(cols ...field.Expr) IGoldCoinOrderUserInfoDo
	Join(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserInfoDo
	Group(cols ...field.Expr) IGoldCoinOrderUserInfoDo
	Having(conds ...gen.Condition) IGoldCoinOrderUserInfoDo
	Limit(limit int) IGoldCoinOrderUserInfoDo
	Offset(offset int) IGoldCoinOrderUserInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGoldCoinOrderUserInfoDo
	Unscoped() IGoldCoinOrderUserInfoDo
	Create(values ...*model.GoldCoinOrderUserInfo) error
	CreateInBatches(values []*model.GoldCoinOrderUserInfo, batchSize int) error
	Save(values ...*model.GoldCoinOrderUserInfo) error
	First() (*model.GoldCoinOrderUserInfo, error)
	Take() (*model.GoldCoinOrderUserInfo, error)
	Last() (*model.GoldCoinOrderUserInfo, error)
	Find() ([]*model.GoldCoinOrderUserInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoldCoinOrderUserInfo, err error)
	FindInBatches(result *[]*model.GoldCoinOrderUserInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GoldCoinOrderUserInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGoldCoinOrderUserInfoDo
	Assign(attrs ...field.AssignExpr) IGoldCoinOrderUserInfoDo
	Joins(fields ...field.RelationField) IGoldCoinOrderUserInfoDo
	Preload(fields ...field.RelationField) IGoldCoinOrderUserInfoDo
	FirstOrInit() (*model.GoldCoinOrderUserInfo, error)
	FirstOrCreate() (*model.GoldCoinOrderUserInfo, error)
	FindByPage(offset int, limit int) (result []*model.GoldCoinOrderUserInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGoldCoinOrderUserInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g goldCoinOrderUserInfoDo) Debug() IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Debug())
}

func (g goldCoinOrderUserInfoDo) WithContext(ctx context.Context) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g goldCoinOrderUserInfoDo) ReadDB() IGoldCoinOrderUserInfoDo {
	return g.Clauses(dbresolver.Read)
}

func (g goldCoinOrderUserInfoDo) WriteDB() IGoldCoinOrderUserInfoDo {
	return g.Clauses(dbresolver.Write)
}

func (g goldCoinOrderUserInfoDo) Session(config *gorm.Session) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Session(config))
}

func (g goldCoinOrderUserInfoDo) Clauses(conds ...clause.Expression) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g goldCoinOrderUserInfoDo) Returning(value interface{}, columns ...string) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g goldCoinOrderUserInfoDo) Not(conds ...gen.Condition) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g goldCoinOrderUserInfoDo) Or(conds ...gen.Condition) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g goldCoinOrderUserInfoDo) Select(conds ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g goldCoinOrderUserInfoDo) Where(conds ...gen.Condition) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g goldCoinOrderUserInfoDo) Order(conds ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g goldCoinOrderUserInfoDo) Distinct(cols ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g goldCoinOrderUserInfoDo) Omit(cols ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g goldCoinOrderUserInfoDo) Join(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g goldCoinOrderUserInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g goldCoinOrderUserInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g goldCoinOrderUserInfoDo) Group(cols ...field.Expr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g goldCoinOrderUserInfoDo) Having(conds ...gen.Condition) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g goldCoinOrderUserInfoDo) Limit(limit int) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g goldCoinOrderUserInfoDo) Offset(offset int) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g goldCoinOrderUserInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g goldCoinOrderUserInfoDo) Unscoped() IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Unscoped())
}

func (g goldCoinOrderUserInfoDo) Create(values ...*model.GoldCoinOrderUserInfo) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g goldCoinOrderUserInfoDo) CreateInBatches(values []*model.GoldCoinOrderUserInfo, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g goldCoinOrderUserInfoDo) Save(values ...*model.GoldCoinOrderUserInfo) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g goldCoinOrderUserInfoDo) First() (*model.GoldCoinOrderUserInfo, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserInfo), nil
	}
}

func (g goldCoinOrderUserInfoDo) Take() (*model.GoldCoinOrderUserInfo, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserInfo), nil
	}
}

func (g goldCoinOrderUserInfoDo) Last() (*model.GoldCoinOrderUserInfo, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserInfo), nil
	}
}

func (g goldCoinOrderUserInfoDo) Find() ([]*model.GoldCoinOrderUserInfo, error) {
	result, err := g.DO.Find()
	return result.([]*model.GoldCoinOrderUserInfo), err
}

func (g goldCoinOrderUserInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GoldCoinOrderUserInfo, err error) {
	buf := make([]*model.GoldCoinOrderUserInfo, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g goldCoinOrderUserInfoDo) FindInBatches(result *[]*model.GoldCoinOrderUserInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g goldCoinOrderUserInfoDo) Attrs(attrs ...field.AssignExpr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g goldCoinOrderUserInfoDo) Assign(attrs ...field.AssignExpr) IGoldCoinOrderUserInfoDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g goldCoinOrderUserInfoDo) Joins(fields ...field.RelationField) IGoldCoinOrderUserInfoDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g goldCoinOrderUserInfoDo) Preload(fields ...field.RelationField) IGoldCoinOrderUserInfoDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g goldCoinOrderUserInfoDo) FirstOrInit() (*model.GoldCoinOrderUserInfo, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserInfo), nil
	}
}

func (g goldCoinOrderUserInfoDo) FirstOrCreate() (*model.GoldCoinOrderUserInfo, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GoldCoinOrderUserInfo), nil
	}
}

func (g goldCoinOrderUserInfoDo) FindByPage(offset int, limit int) (result []*model.GoldCoinOrderUserInfo, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g goldCoinOrderUserInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g goldCoinOrderUserInfoDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g goldCoinOrderUserInfoDo) Delete(models ...*model.GoldCoinOrderUserInfo) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *goldCoinOrderUserInfoDo) withDO(do gen.Dao) *goldCoinOrderUserInfoDo {
	g.DO = *do.(*gen.DO)
	return g
}
