// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"godemo/internal/dzpk_static_test/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.PlatUserDailyContr{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.PlatUserDailyContr{}) fail: %s", err)
	}
}

func Test_platUserDailyContrQuery(t *testing.T) {
	platUserDailyContr := newPlatUserDailyContr(_gen_test_db)
	platUserDailyContr = *platUserDailyContr.As(platUserDailyContr.TableName())
	_do := platUserDailyContr.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(platUserDailyContr.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <plat_user_daily_contr> fail:", err)
		return
	}

	_, ok := platUserDailyContr.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from platUserDailyContr success")
	}

	err = _do.Create(&model.PlatUserDailyContr{})
	if err != nil {
		t.Error("create item in table <plat_user_daily_contr> fail:", err)
	}

	err = _do.Save(&model.PlatUserDailyContr{})
	if err != nil {
		t.Error("create item in table <plat_user_daily_contr> fail:", err)
	}

	err = _do.CreateInBatches([]*model.PlatUserDailyContr{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Select(platUserDailyContr.ALL).Take()
	if err != nil {
		t.Error("Take() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <plat_user_daily_contr> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.PlatUserDailyContr{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Select(platUserDailyContr.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Select(platUserDailyContr.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <plat_user_daily_contr> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.ScanByPage(&model.PlatUserDailyContr{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <plat_user_daily_contr> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <plat_user_daily_contr> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <plat_user_daily_contr> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <plat_user_daily_contr> fail:", err)
	}
}
