// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newSnakeRole(db *gorm.DB, opts ...gen.DOOption) snakeRole {
	_snakeRole := snakeRole{}

	_snakeRole.snakeRoleDo.UseDB(db, opts...)
	_snakeRole.snakeRoleDo.UseModel(&model.SnakeRole{})

	tableName := _snakeRole.snakeRoleDo.TableName()
	_snakeRole.ALL = field.NewAsterisk(tableName)
	_snakeRole.ID = field.NewInt32(tableName, "id")
	_snakeRole.Rolename = field.NewString(tableName, "rolename")
	_snakeRole.Rule = field.NewString(tableName, "rule")

	_snakeRole.fillFieldMap()

	return _snakeRole
}

type snakeRole struct {
	snakeRoleDo

	ALL      field.Asterisk
	ID       field.Int32  // id
	Rolename field.String // 角色名称
	Rule     field.String // 权限节点数据

	fieldMap map[string]field.Expr
}

func (s snakeRole) Table(newTableName string) *snakeRole {
	s.snakeRoleDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s snakeRole) As(alias string) *snakeRole {
	s.snakeRoleDo.DO = *(s.snakeRoleDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *snakeRole) updateTableName(table string) *snakeRole {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.Rolename = field.NewString(table, "rolename")
	s.Rule = field.NewString(table, "rule")

	s.fillFieldMap()

	return s
}

func (s *snakeRole) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *snakeRole) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 3)
	s.fieldMap["id"] = s.ID
	s.fieldMap["rolename"] = s.Rolename
	s.fieldMap["rule"] = s.Rule
}

func (s snakeRole) clone(db *gorm.DB) snakeRole {
	s.snakeRoleDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s snakeRole) replaceDB(db *gorm.DB) snakeRole {
	s.snakeRoleDo.ReplaceDB(db)
	return s
}

type snakeRoleDo struct{ gen.DO }

type ISnakeRoleDo interface {
	gen.SubQuery
	Debug() ISnakeRoleDo
	WithContext(ctx context.Context) ISnakeRoleDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISnakeRoleDo
	WriteDB() ISnakeRoleDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISnakeRoleDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISnakeRoleDo
	Not(conds ...gen.Condition) ISnakeRoleDo
	Or(conds ...gen.Condition) ISnakeRoleDo
	Select(conds ...field.Expr) ISnakeRoleDo
	Where(conds ...gen.Condition) ISnakeRoleDo
	Order(conds ...field.Expr) ISnakeRoleDo
	Distinct(cols ...field.Expr) ISnakeRoleDo
	Omit(cols ...field.Expr) ISnakeRoleDo
	Join(table schema.Tabler, on ...field.Expr) ISnakeRoleDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISnakeRoleDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISnakeRoleDo
	Group(cols ...field.Expr) ISnakeRoleDo
	Having(conds ...gen.Condition) ISnakeRoleDo
	Limit(limit int) ISnakeRoleDo
	Offset(offset int) ISnakeRoleDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISnakeRoleDo
	Unscoped() ISnakeRoleDo
	Create(values ...*model.SnakeRole) error
	CreateInBatches(values []*model.SnakeRole, batchSize int) error
	Save(values ...*model.SnakeRole) error
	First() (*model.SnakeRole, error)
	Take() (*model.SnakeRole, error)
	Last() (*model.SnakeRole, error)
	Find() ([]*model.SnakeRole, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SnakeRole, err error)
	FindInBatches(result *[]*model.SnakeRole, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SnakeRole) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISnakeRoleDo
	Assign(attrs ...field.AssignExpr) ISnakeRoleDo
	Joins(fields ...field.RelationField) ISnakeRoleDo
	Preload(fields ...field.RelationField) ISnakeRoleDo
	FirstOrInit() (*model.SnakeRole, error)
	FirstOrCreate() (*model.SnakeRole, error)
	FindByPage(offset int, limit int) (result []*model.SnakeRole, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISnakeRoleDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s snakeRoleDo) Debug() ISnakeRoleDo {
	return s.withDO(s.DO.Debug())
}

func (s snakeRoleDo) WithContext(ctx context.Context) ISnakeRoleDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s snakeRoleDo) ReadDB() ISnakeRoleDo {
	return s.Clauses(dbresolver.Read)
}

func (s snakeRoleDo) WriteDB() ISnakeRoleDo {
	return s.Clauses(dbresolver.Write)
}

func (s snakeRoleDo) Session(config *gorm.Session) ISnakeRoleDo {
	return s.withDO(s.DO.Session(config))
}

func (s snakeRoleDo) Clauses(conds ...clause.Expression) ISnakeRoleDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s snakeRoleDo) Returning(value interface{}, columns ...string) ISnakeRoleDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s snakeRoleDo) Not(conds ...gen.Condition) ISnakeRoleDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s snakeRoleDo) Or(conds ...gen.Condition) ISnakeRoleDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s snakeRoleDo) Select(conds ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s snakeRoleDo) Where(conds ...gen.Condition) ISnakeRoleDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s snakeRoleDo) Order(conds ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s snakeRoleDo) Distinct(cols ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s snakeRoleDo) Omit(cols ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s snakeRoleDo) Join(table schema.Tabler, on ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s snakeRoleDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s snakeRoleDo) RightJoin(table schema.Tabler, on ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s snakeRoleDo) Group(cols ...field.Expr) ISnakeRoleDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s snakeRoleDo) Having(conds ...gen.Condition) ISnakeRoleDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s snakeRoleDo) Limit(limit int) ISnakeRoleDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s snakeRoleDo) Offset(offset int) ISnakeRoleDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s snakeRoleDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISnakeRoleDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s snakeRoleDo) Unscoped() ISnakeRoleDo {
	return s.withDO(s.DO.Unscoped())
}

func (s snakeRoleDo) Create(values ...*model.SnakeRole) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s snakeRoleDo) CreateInBatches(values []*model.SnakeRole, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s snakeRoleDo) Save(values ...*model.SnakeRole) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s snakeRoleDo) First() (*model.SnakeRole, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnakeRole), nil
	}
}

func (s snakeRoleDo) Take() (*model.SnakeRole, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnakeRole), nil
	}
}

func (s snakeRoleDo) Last() (*model.SnakeRole, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnakeRole), nil
	}
}

func (s snakeRoleDo) Find() ([]*model.SnakeRole, error) {
	result, err := s.DO.Find()
	return result.([]*model.SnakeRole), err
}

func (s snakeRoleDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SnakeRole, err error) {
	buf := make([]*model.SnakeRole, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s snakeRoleDo) FindInBatches(result *[]*model.SnakeRole, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s snakeRoleDo) Attrs(attrs ...field.AssignExpr) ISnakeRoleDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s snakeRoleDo) Assign(attrs ...field.AssignExpr) ISnakeRoleDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s snakeRoleDo) Joins(fields ...field.RelationField) ISnakeRoleDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s snakeRoleDo) Preload(fields ...field.RelationField) ISnakeRoleDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s snakeRoleDo) FirstOrInit() (*model.SnakeRole, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnakeRole), nil
	}
}

func (s snakeRoleDo) FirstOrCreate() (*model.SnakeRole, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SnakeRole), nil
	}
}

func (s snakeRoleDo) FindByPage(offset int, limit int) (result []*model.SnakeRole, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s snakeRoleDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s snakeRoleDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s snakeRoleDo) Delete(models ...*model.SnakeRole) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *snakeRoleDo) withDO(do gen.Dao) *snakeRoleDo {
	s.DO = *do.(*gen.DO)
	return s
}
