// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newTUnwithdrawn(db *gorm.DB, opts ...gen.DOOption) tUnwithdrawn {
	_tUnwithdrawn := tUnwithdrawn{}

	_tUnwithdrawn.tUnwithdrawnDo.UseDB(db, opts...)
	_tUnwithdrawn.tUnwithdrawnDo.UseModel(&model.TUnwithdrawn{})

	tableName := _tUnwithdrawn.tUnwithdrawnDo.TableName()
	_tUnwithdrawn.ALL = field.NewAsterisk(tableName)
	_tUnwithdrawn.UID = field.NewUint32(tableName, "uid")
	_tUnwithdrawn.TotalRecharge = field.NewInt64(tableName, "total_recharge")
	_tUnwithdrawn.UnwithCurrency = field.NewInt64(tableName, "unwith_currency")
	_tUnwithdrawn.UnwithAmount = field.NewInt64(tableName, "unwith_amount")
	_tUnwithdrawn.GiftMoneyAmount = field.NewInt64(tableName, "gift_money_amount")
	_tUnwithdrawn.AddTime = field.NewInt64(tableName, "add_time")
	_tUnwithdrawn.UpdateTime = field.NewInt64(tableName, "update_time")

	_tUnwithdrawn.fillFieldMap()

	return _tUnwithdrawn
}

type tUnwithdrawn struct {
	tUnwithdrawnDo

	ALL             field.Asterisk
	UID             field.Uint32
	TotalRecharge   field.Int64 // æ€»å……å€¼é¢
	UnwithCurrency  field.Int64 // æ¸¸æˆé‡Œäº§ç”Ÿçš„æ€»æµæ°´
	UnwithAmount    field.Int64 // ä¸å¯é¢†å–é‡‘é¢
	GiftMoneyAmount field.Int64
	AddTime         field.Int64 // åˆ›å»ºæ—¶é—´
	UpdateTime      field.Int64 // æ›´æ–°æ—¶é—´

	fieldMap map[string]field.Expr
}

func (t tUnwithdrawn) Table(newTableName string) *tUnwithdrawn {
	t.tUnwithdrawnDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tUnwithdrawn) As(alias string) *tUnwithdrawn {
	t.tUnwithdrawnDo.DO = *(t.tUnwithdrawnDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tUnwithdrawn) updateTableName(table string) *tUnwithdrawn {
	t.ALL = field.NewAsterisk(table)
	t.UID = field.NewUint32(table, "uid")
	t.TotalRecharge = field.NewInt64(table, "total_recharge")
	t.UnwithCurrency = field.NewInt64(table, "unwith_currency")
	t.UnwithAmount = field.NewInt64(table, "unwith_amount")
	t.GiftMoneyAmount = field.NewInt64(table, "gift_money_amount")
	t.AddTime = field.NewInt64(table, "add_time")
	t.UpdateTime = field.NewInt64(table, "update_time")

	t.fillFieldMap()

	return t
}

func (t *tUnwithdrawn) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tUnwithdrawn) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["uid"] = t.UID
	t.fieldMap["total_recharge"] = t.TotalRecharge
	t.fieldMap["unwith_currency"] = t.UnwithCurrency
	t.fieldMap["unwith_amount"] = t.UnwithAmount
	t.fieldMap["gift_money_amount"] = t.GiftMoneyAmount
	t.fieldMap["add_time"] = t.AddTime
	t.fieldMap["update_time"] = t.UpdateTime
}

func (t tUnwithdrawn) clone(db *gorm.DB) tUnwithdrawn {
	t.tUnwithdrawnDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tUnwithdrawn) replaceDB(db *gorm.DB) tUnwithdrawn {
	t.tUnwithdrawnDo.ReplaceDB(db)
	return t
}

type tUnwithdrawnDo struct{ gen.DO }

type ITUnwithdrawnDo interface {
	gen.SubQuery
	Debug() ITUnwithdrawnDo
	WithContext(ctx context.Context) ITUnwithdrawnDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITUnwithdrawnDo
	WriteDB() ITUnwithdrawnDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITUnwithdrawnDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITUnwithdrawnDo
	Not(conds ...gen.Condition) ITUnwithdrawnDo
	Or(conds ...gen.Condition) ITUnwithdrawnDo
	Select(conds ...field.Expr) ITUnwithdrawnDo
	Where(conds ...gen.Condition) ITUnwithdrawnDo
	Order(conds ...field.Expr) ITUnwithdrawnDo
	Distinct(cols ...field.Expr) ITUnwithdrawnDo
	Omit(cols ...field.Expr) ITUnwithdrawnDo
	Join(table schema.Tabler, on ...field.Expr) ITUnwithdrawnDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITUnwithdrawnDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITUnwithdrawnDo
	Group(cols ...field.Expr) ITUnwithdrawnDo
	Having(conds ...gen.Condition) ITUnwithdrawnDo
	Limit(limit int) ITUnwithdrawnDo
	Offset(offset int) ITUnwithdrawnDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITUnwithdrawnDo
	Unscoped() ITUnwithdrawnDo
	Create(values ...*model.TUnwithdrawn) error
	CreateInBatches(values []*model.TUnwithdrawn, batchSize int) error
	Save(values ...*model.TUnwithdrawn) error
	First() (*model.TUnwithdrawn, error)
	Take() (*model.TUnwithdrawn, error)
	Last() (*model.TUnwithdrawn, error)
	Find() ([]*model.TUnwithdrawn, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUnwithdrawn, err error)
	FindInBatches(result *[]*model.TUnwithdrawn, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TUnwithdrawn) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITUnwithdrawnDo
	Assign(attrs ...field.AssignExpr) ITUnwithdrawnDo
	Joins(fields ...field.RelationField) ITUnwithdrawnDo
	Preload(fields ...field.RelationField) ITUnwithdrawnDo
	FirstOrInit() (*model.TUnwithdrawn, error)
	FirstOrCreate() (*model.TUnwithdrawn, error)
	FindByPage(offset int, limit int) (result []*model.TUnwithdrawn, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITUnwithdrawnDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tUnwithdrawnDo) Debug() ITUnwithdrawnDo {
	return t.withDO(t.DO.Debug())
}

func (t tUnwithdrawnDo) WithContext(ctx context.Context) ITUnwithdrawnDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tUnwithdrawnDo) ReadDB() ITUnwithdrawnDo {
	return t.Clauses(dbresolver.Read)
}

func (t tUnwithdrawnDo) WriteDB() ITUnwithdrawnDo {
	return t.Clauses(dbresolver.Write)
}

func (t tUnwithdrawnDo) Session(config *gorm.Session) ITUnwithdrawnDo {
	return t.withDO(t.DO.Session(config))
}

func (t tUnwithdrawnDo) Clauses(conds ...clause.Expression) ITUnwithdrawnDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tUnwithdrawnDo) Returning(value interface{}, columns ...string) ITUnwithdrawnDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tUnwithdrawnDo) Not(conds ...gen.Condition) ITUnwithdrawnDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tUnwithdrawnDo) Or(conds ...gen.Condition) ITUnwithdrawnDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tUnwithdrawnDo) Select(conds ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tUnwithdrawnDo) Where(conds ...gen.Condition) ITUnwithdrawnDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tUnwithdrawnDo) Order(conds ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tUnwithdrawnDo) Distinct(cols ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tUnwithdrawnDo) Omit(cols ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tUnwithdrawnDo) Join(table schema.Tabler, on ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tUnwithdrawnDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tUnwithdrawnDo) RightJoin(table schema.Tabler, on ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tUnwithdrawnDo) Group(cols ...field.Expr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tUnwithdrawnDo) Having(conds ...gen.Condition) ITUnwithdrawnDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tUnwithdrawnDo) Limit(limit int) ITUnwithdrawnDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tUnwithdrawnDo) Offset(offset int) ITUnwithdrawnDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tUnwithdrawnDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITUnwithdrawnDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tUnwithdrawnDo) Unscoped() ITUnwithdrawnDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tUnwithdrawnDo) Create(values ...*model.TUnwithdrawn) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tUnwithdrawnDo) CreateInBatches(values []*model.TUnwithdrawn, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tUnwithdrawnDo) Save(values ...*model.TUnwithdrawn) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tUnwithdrawnDo) First() (*model.TUnwithdrawn, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUnwithdrawn), nil
	}
}

func (t tUnwithdrawnDo) Take() (*model.TUnwithdrawn, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUnwithdrawn), nil
	}
}

func (t tUnwithdrawnDo) Last() (*model.TUnwithdrawn, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUnwithdrawn), nil
	}
}

func (t tUnwithdrawnDo) Find() ([]*model.TUnwithdrawn, error) {
	result, err := t.DO.Find()
	return result.([]*model.TUnwithdrawn), err
}

func (t tUnwithdrawnDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUnwithdrawn, err error) {
	buf := make([]*model.TUnwithdrawn, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tUnwithdrawnDo) FindInBatches(result *[]*model.TUnwithdrawn, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tUnwithdrawnDo) Attrs(attrs ...field.AssignExpr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tUnwithdrawnDo) Assign(attrs ...field.AssignExpr) ITUnwithdrawnDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tUnwithdrawnDo) Joins(fields ...field.RelationField) ITUnwithdrawnDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tUnwithdrawnDo) Preload(fields ...field.RelationField) ITUnwithdrawnDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tUnwithdrawnDo) FirstOrInit() (*model.TUnwithdrawn, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUnwithdrawn), nil
	}
}

func (t tUnwithdrawnDo) FirstOrCreate() (*model.TUnwithdrawn, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUnwithdrawn), nil
	}
}

func (t tUnwithdrawnDo) FindByPage(offset int, limit int) (result []*model.TUnwithdrawn, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tUnwithdrawnDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tUnwithdrawnDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tUnwithdrawnDo) Delete(models ...*model.TUnwithdrawn) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tUnwithdrawnDo) withDO(do gen.Dao) *tUnwithdrawnDo {
	t.DO = *do.(*gen.DO)
	return t
}
