// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/dzpk_static_test/model"
)

func newVoidBet(db *gorm.DB, opts ...gen.DOOption) voidBet {
	_voidBet := voidBet{}

	_voidBet.voidBetDo.UseDB(db, opts...)
	_voidBet.voidBetDo.UseModel(&model.VoidBet{})

	tableName := _voidBet.voidBetDo.TableName()
	_voidBet.ALL = field.NewAsterisk(tableName)
	_voidBet.ID = field.NewInt32(tableName, "id")
	_voidBet.UID = field.NewUint32(tableName, "uid")
	_voidBet.NickName = field.NewString(tableName, "nick_name")
	_voidBet.Count_ = field.NewUint32(tableName, "count")
	_voidBet.Scale = field.NewUint32(tableName, "scale")
	_voidBet.State = field.NewUint32(tableName, "state")
	_voidBet.RecordTime = field.NewInt64(tableName, "record_time")
	_voidBet.UpdateTime = field.NewInt64(tableName, "update_time")
	_voidBet.SendTime = field.NewInt64(tableName, "send_time")
	_voidBet.RoomID = field.NewInt32(tableName, "room_id")
	_voidBet.GameID = field.NewUint32(tableName, "game_id")

	_voidBet.fillFieldMap()

	return _voidBet
}

// voidBet 无效下注记录
type voidBet struct {
	voidBetDo

	ALL        field.Asterisk
	ID         field.Int32
	UID        field.Uint32
	NickName   field.String
	Count_     field.Uint32
	Scale      field.Uint32
	State      field.Uint32
	RecordTime field.Int64
	UpdateTime field.Int64
	SendTime   field.Int64
	RoomID     field.Int32
	GameID     field.Uint32

	fieldMap map[string]field.Expr
}

func (v voidBet) Table(newTableName string) *voidBet {
	v.voidBetDo.UseTable(newTableName)
	return v.updateTableName(newTableName)
}

func (v voidBet) As(alias string) *voidBet {
	v.voidBetDo.DO = *(v.voidBetDo.As(alias).(*gen.DO))
	return v.updateTableName(alias)
}

func (v *voidBet) updateTableName(table string) *voidBet {
	v.ALL = field.NewAsterisk(table)
	v.ID = field.NewInt32(table, "id")
	v.UID = field.NewUint32(table, "uid")
	v.NickName = field.NewString(table, "nick_name")
	v.Count_ = field.NewUint32(table, "count")
	v.Scale = field.NewUint32(table, "scale")
	v.State = field.NewUint32(table, "state")
	v.RecordTime = field.NewInt64(table, "record_time")
	v.UpdateTime = field.NewInt64(table, "update_time")
	v.SendTime = field.NewInt64(table, "send_time")
	v.RoomID = field.NewInt32(table, "room_id")
	v.GameID = field.NewUint32(table, "game_id")

	v.fillFieldMap()

	return v
}

func (v *voidBet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := v.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (v *voidBet) fillFieldMap() {
	v.fieldMap = make(map[string]field.Expr, 11)
	v.fieldMap["id"] = v.ID
	v.fieldMap["uid"] = v.UID
	v.fieldMap["nick_name"] = v.NickName
	v.fieldMap["count"] = v.Count_
	v.fieldMap["scale"] = v.Scale
	v.fieldMap["state"] = v.State
	v.fieldMap["record_time"] = v.RecordTime
	v.fieldMap["update_time"] = v.UpdateTime
	v.fieldMap["send_time"] = v.SendTime
	v.fieldMap["room_id"] = v.RoomID
	v.fieldMap["game_id"] = v.GameID
}

func (v voidBet) clone(db *gorm.DB) voidBet {
	v.voidBetDo.ReplaceConnPool(db.Statement.ConnPool)
	return v
}

func (v voidBet) replaceDB(db *gorm.DB) voidBet {
	v.voidBetDo.ReplaceDB(db)
	return v
}

type voidBetDo struct{ gen.DO }

type IVoidBetDo interface {
	gen.SubQuery
	Debug() IVoidBetDo
	WithContext(ctx context.Context) IVoidBetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IVoidBetDo
	WriteDB() IVoidBetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IVoidBetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IVoidBetDo
	Not(conds ...gen.Condition) IVoidBetDo
	Or(conds ...gen.Condition) IVoidBetDo
	Select(conds ...field.Expr) IVoidBetDo
	Where(conds ...gen.Condition) IVoidBetDo
	Order(conds ...field.Expr) IVoidBetDo
	Distinct(cols ...field.Expr) IVoidBetDo
	Omit(cols ...field.Expr) IVoidBetDo
	Join(table schema.Tabler, on ...field.Expr) IVoidBetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IVoidBetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IVoidBetDo
	Group(cols ...field.Expr) IVoidBetDo
	Having(conds ...gen.Condition) IVoidBetDo
	Limit(limit int) IVoidBetDo
	Offset(offset int) IVoidBetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IVoidBetDo
	Unscoped() IVoidBetDo
	Create(values ...*model.VoidBet) error
	CreateInBatches(values []*model.VoidBet, batchSize int) error
	Save(values ...*model.VoidBet) error
	First() (*model.VoidBet, error)
	Take() (*model.VoidBet, error)
	Last() (*model.VoidBet, error)
	Find() ([]*model.VoidBet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VoidBet, err error)
	FindInBatches(result *[]*model.VoidBet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.VoidBet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IVoidBetDo
	Assign(attrs ...field.AssignExpr) IVoidBetDo
	Joins(fields ...field.RelationField) IVoidBetDo
	Preload(fields ...field.RelationField) IVoidBetDo
	FirstOrInit() (*model.VoidBet, error)
	FirstOrCreate() (*model.VoidBet, error)
	FindByPage(offset int, limit int) (result []*model.VoidBet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IVoidBetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (v voidBetDo) Debug() IVoidBetDo {
	return v.withDO(v.DO.Debug())
}

func (v voidBetDo) WithContext(ctx context.Context) IVoidBetDo {
	return v.withDO(v.DO.WithContext(ctx))
}

func (v voidBetDo) ReadDB() IVoidBetDo {
	return v.Clauses(dbresolver.Read)
}

func (v voidBetDo) WriteDB() IVoidBetDo {
	return v.Clauses(dbresolver.Write)
}

func (v voidBetDo) Session(config *gorm.Session) IVoidBetDo {
	return v.withDO(v.DO.Session(config))
}

func (v voidBetDo) Clauses(conds ...clause.Expression) IVoidBetDo {
	return v.withDO(v.DO.Clauses(conds...))
}

func (v voidBetDo) Returning(value interface{}, columns ...string) IVoidBetDo {
	return v.withDO(v.DO.Returning(value, columns...))
}

func (v voidBetDo) Not(conds ...gen.Condition) IVoidBetDo {
	return v.withDO(v.DO.Not(conds...))
}

func (v voidBetDo) Or(conds ...gen.Condition) IVoidBetDo {
	return v.withDO(v.DO.Or(conds...))
}

func (v voidBetDo) Select(conds ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.Select(conds...))
}

func (v voidBetDo) Where(conds ...gen.Condition) IVoidBetDo {
	return v.withDO(v.DO.Where(conds...))
}

func (v voidBetDo) Order(conds ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.Order(conds...))
}

func (v voidBetDo) Distinct(cols ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.Distinct(cols...))
}

func (v voidBetDo) Omit(cols ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.Omit(cols...))
}

func (v voidBetDo) Join(table schema.Tabler, on ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.Join(table, on...))
}

func (v voidBetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.LeftJoin(table, on...))
}

func (v voidBetDo) RightJoin(table schema.Tabler, on ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.RightJoin(table, on...))
}

func (v voidBetDo) Group(cols ...field.Expr) IVoidBetDo {
	return v.withDO(v.DO.Group(cols...))
}

func (v voidBetDo) Having(conds ...gen.Condition) IVoidBetDo {
	return v.withDO(v.DO.Having(conds...))
}

func (v voidBetDo) Limit(limit int) IVoidBetDo {
	return v.withDO(v.DO.Limit(limit))
}

func (v voidBetDo) Offset(offset int) IVoidBetDo {
	return v.withDO(v.DO.Offset(offset))
}

func (v voidBetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IVoidBetDo {
	return v.withDO(v.DO.Scopes(funcs...))
}

func (v voidBetDo) Unscoped() IVoidBetDo {
	return v.withDO(v.DO.Unscoped())
}

func (v voidBetDo) Create(values ...*model.VoidBet) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Create(values)
}

func (v voidBetDo) CreateInBatches(values []*model.VoidBet, batchSize int) error {
	return v.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (v voidBetDo) Save(values ...*model.VoidBet) error {
	if len(values) == 0 {
		return nil
	}
	return v.DO.Save(values)
}

func (v voidBetDo) First() (*model.VoidBet, error) {
	if result, err := v.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoidBet), nil
	}
}

func (v voidBetDo) Take() (*model.VoidBet, error) {
	if result, err := v.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoidBet), nil
	}
}

func (v voidBetDo) Last() (*model.VoidBet, error) {
	if result, err := v.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoidBet), nil
	}
}

func (v voidBetDo) Find() ([]*model.VoidBet, error) {
	result, err := v.DO.Find()
	return result.([]*model.VoidBet), err
}

func (v voidBetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.VoidBet, err error) {
	buf := make([]*model.VoidBet, 0, batchSize)
	err = v.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (v voidBetDo) FindInBatches(result *[]*model.VoidBet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return v.DO.FindInBatches(result, batchSize, fc)
}

func (v voidBetDo) Attrs(attrs ...field.AssignExpr) IVoidBetDo {
	return v.withDO(v.DO.Attrs(attrs...))
}

func (v voidBetDo) Assign(attrs ...field.AssignExpr) IVoidBetDo {
	return v.withDO(v.DO.Assign(attrs...))
}

func (v voidBetDo) Joins(fields ...field.RelationField) IVoidBetDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Joins(_f))
	}
	return &v
}

func (v voidBetDo) Preload(fields ...field.RelationField) IVoidBetDo {
	for _, _f := range fields {
		v = *v.withDO(v.DO.Preload(_f))
	}
	return &v
}

func (v voidBetDo) FirstOrInit() (*model.VoidBet, error) {
	if result, err := v.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoidBet), nil
	}
}

func (v voidBetDo) FirstOrCreate() (*model.VoidBet, error) {
	if result, err := v.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.VoidBet), nil
	}
}

func (v voidBetDo) FindByPage(offset int, limit int) (result []*model.VoidBet, count int64, err error) {
	result, err = v.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = v.Offset(-1).Limit(-1).Count()
	return
}

func (v voidBetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = v.Count()
	if err != nil {
		return
	}

	err = v.Offset(offset).Limit(limit).Scan(result)
	return
}

func (v voidBetDo) Scan(result interface{}) (err error) {
	return v.DO.Scan(result)
}

func (v voidBetDo) Delete(models ...*model.VoidBet) (result gen.ResultInfo, err error) {
	return v.DO.Delete(models)
}

func (v *voidBetDo) withDO(do gen.Dao) *voidBetDo {
	v.DO = *do.(*gen.DO)
	return v
}
