// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newDtbClubAdmin(db *gorm.DB, opts ...gen.DOOption) dtbClubAdmin {
	_dtbClubAdmin := dtbClubAdmin{}

	_dtbClubAdmin.dtbClubAdminDo.UseDB(db, opts...)
	_dtbClubAdmin.dtbClubAdminDo.UseModel(&model.DtbClubAdmin{})

	tableName := _dtbClubAdmin.dtbClubAdminDo.TableName()
	_dtbClubAdmin.ALL = field.NewAsterisk(tableName)
	_dtbClubAdmin.ID = field.NewUint32(tableName, "id")
	_dtbClubAdmin.ClubID = field.NewUint32(tableName, "club_id")
	_dtbClubAdmin.AdminID = field.NewUint32(tableName, "admin_id")
	_dtbClubAdmin.AddTime = field.NewUint32(tableName, "add_time")
	_dtbClubAdmin.Plat = field.NewBool(tableName, "plat")

	_dtbClubAdmin.fillFieldMap()

	return _dtbClubAdmin
}

// dtbClubAdmin 俱乐部管理员信息表
type dtbClubAdmin struct {
	dtbClubAdminDo

	ALL     field.Asterisk
	ID      field.Uint32
	ClubID  field.Uint32 // 俱乐部ID
	AdminID field.Uint32 // 管理员ID
	AddTime field.Uint32 // 添加时间
	Plat    field.Bool   // platform

	fieldMap map[string]field.Expr
}

func (d dtbClubAdmin) Table(newTableName string) *dtbClubAdmin {
	d.dtbClubAdminDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dtbClubAdmin) As(alias string) *dtbClubAdmin {
	d.dtbClubAdminDo.DO = *(d.dtbClubAdminDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dtbClubAdmin) updateTableName(table string) *dtbClubAdmin {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.ClubID = field.NewUint32(table, "club_id")
	d.AdminID = field.NewUint32(table, "admin_id")
	d.AddTime = field.NewUint32(table, "add_time")
	d.Plat = field.NewBool(table, "plat")

	d.fillFieldMap()

	return d
}

func (d *dtbClubAdmin) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dtbClubAdmin) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 5)
	d.fieldMap["id"] = d.ID
	d.fieldMap["club_id"] = d.ClubID
	d.fieldMap["admin_id"] = d.AdminID
	d.fieldMap["add_time"] = d.AddTime
	d.fieldMap["plat"] = d.Plat
}

func (d dtbClubAdmin) clone(db *gorm.DB) dtbClubAdmin {
	d.dtbClubAdminDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dtbClubAdmin) replaceDB(db *gorm.DB) dtbClubAdmin {
	d.dtbClubAdminDo.ReplaceDB(db)
	return d
}

type dtbClubAdminDo struct{ gen.DO }

type IDtbClubAdminDo interface {
	gen.SubQuery
	Debug() IDtbClubAdminDo
	WithContext(ctx context.Context) IDtbClubAdminDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDtbClubAdminDo
	WriteDB() IDtbClubAdminDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDtbClubAdminDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDtbClubAdminDo
	Not(conds ...gen.Condition) IDtbClubAdminDo
	Or(conds ...gen.Condition) IDtbClubAdminDo
	Select(conds ...field.Expr) IDtbClubAdminDo
	Where(conds ...gen.Condition) IDtbClubAdminDo
	Order(conds ...field.Expr) IDtbClubAdminDo
	Distinct(cols ...field.Expr) IDtbClubAdminDo
	Omit(cols ...field.Expr) IDtbClubAdminDo
	Join(table schema.Tabler, on ...field.Expr) IDtbClubAdminDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDtbClubAdminDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDtbClubAdminDo
	Group(cols ...field.Expr) IDtbClubAdminDo
	Having(conds ...gen.Condition) IDtbClubAdminDo
	Limit(limit int) IDtbClubAdminDo
	Offset(offset int) IDtbClubAdminDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbClubAdminDo
	Unscoped() IDtbClubAdminDo
	Create(values ...*model.DtbClubAdmin) error
	CreateInBatches(values []*model.DtbClubAdmin, batchSize int) error
	Save(values ...*model.DtbClubAdmin) error
	First() (*model.DtbClubAdmin, error)
	Take() (*model.DtbClubAdmin, error)
	Last() (*model.DtbClubAdmin, error)
	Find() ([]*model.DtbClubAdmin, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbClubAdmin, err error)
	FindInBatches(result *[]*model.DtbClubAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DtbClubAdmin) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDtbClubAdminDo
	Assign(attrs ...field.AssignExpr) IDtbClubAdminDo
	Joins(fields ...field.RelationField) IDtbClubAdminDo
	Preload(fields ...field.RelationField) IDtbClubAdminDo
	FirstOrInit() (*model.DtbClubAdmin, error)
	FirstOrCreate() (*model.DtbClubAdmin, error)
	FindByPage(offset int, limit int) (result []*model.DtbClubAdmin, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDtbClubAdminDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dtbClubAdminDo) Debug() IDtbClubAdminDo {
	return d.withDO(d.DO.Debug())
}

func (d dtbClubAdminDo) WithContext(ctx context.Context) IDtbClubAdminDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dtbClubAdminDo) ReadDB() IDtbClubAdminDo {
	return d.Clauses(dbresolver.Read)
}

func (d dtbClubAdminDo) WriteDB() IDtbClubAdminDo {
	return d.Clauses(dbresolver.Write)
}

func (d dtbClubAdminDo) Session(config *gorm.Session) IDtbClubAdminDo {
	return d.withDO(d.DO.Session(config))
}

func (d dtbClubAdminDo) Clauses(conds ...clause.Expression) IDtbClubAdminDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dtbClubAdminDo) Returning(value interface{}, columns ...string) IDtbClubAdminDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dtbClubAdminDo) Not(conds ...gen.Condition) IDtbClubAdminDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dtbClubAdminDo) Or(conds ...gen.Condition) IDtbClubAdminDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dtbClubAdminDo) Select(conds ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dtbClubAdminDo) Where(conds ...gen.Condition) IDtbClubAdminDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dtbClubAdminDo) Order(conds ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dtbClubAdminDo) Distinct(cols ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dtbClubAdminDo) Omit(cols ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dtbClubAdminDo) Join(table schema.Tabler, on ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dtbClubAdminDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dtbClubAdminDo) RightJoin(table schema.Tabler, on ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dtbClubAdminDo) Group(cols ...field.Expr) IDtbClubAdminDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dtbClubAdminDo) Having(conds ...gen.Condition) IDtbClubAdminDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dtbClubAdminDo) Limit(limit int) IDtbClubAdminDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dtbClubAdminDo) Offset(offset int) IDtbClubAdminDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dtbClubAdminDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbClubAdminDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dtbClubAdminDo) Unscoped() IDtbClubAdminDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dtbClubAdminDo) Create(values ...*model.DtbClubAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dtbClubAdminDo) CreateInBatches(values []*model.DtbClubAdmin, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dtbClubAdminDo) Save(values ...*model.DtbClubAdmin) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dtbClubAdminDo) First() (*model.DtbClubAdmin, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbClubAdmin), nil
	}
}

func (d dtbClubAdminDo) Take() (*model.DtbClubAdmin, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbClubAdmin), nil
	}
}

func (d dtbClubAdminDo) Last() (*model.DtbClubAdmin, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbClubAdmin), nil
	}
}

func (d dtbClubAdminDo) Find() ([]*model.DtbClubAdmin, error) {
	result, err := d.DO.Find()
	return result.([]*model.DtbClubAdmin), err
}

func (d dtbClubAdminDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbClubAdmin, err error) {
	buf := make([]*model.DtbClubAdmin, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dtbClubAdminDo) FindInBatches(result *[]*model.DtbClubAdmin, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dtbClubAdminDo) Attrs(attrs ...field.AssignExpr) IDtbClubAdminDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dtbClubAdminDo) Assign(attrs ...field.AssignExpr) IDtbClubAdminDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dtbClubAdminDo) Joins(fields ...field.RelationField) IDtbClubAdminDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dtbClubAdminDo) Preload(fields ...field.RelationField) IDtbClubAdminDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dtbClubAdminDo) FirstOrInit() (*model.DtbClubAdmin, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbClubAdmin), nil
	}
}

func (d dtbClubAdminDo) FirstOrCreate() (*model.DtbClubAdmin, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbClubAdmin), nil
	}
}

func (d dtbClubAdminDo) FindByPage(offset int, limit int) (result []*model.DtbClubAdmin, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dtbClubAdminDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dtbClubAdminDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dtbClubAdminDo) Delete(models ...*model.DtbClubAdmin) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dtbClubAdminDo) withDO(do gen.Dao) *dtbClubAdminDo {
	d.DO = *do.(*gen.DO)
	return d
}
