// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newDtbButton(db *gorm.DB, opts ...gen.DOOption) dtbButton {
	_dtbButton := dtbButton{}

	_dtbButton.dtbButtonDo.UseDB(db, opts...)
	_dtbButton.dtbButtonDo.UseModel(&model.DtbButton{})

	tableName := _dtbButton.dtbButtonDo.TableName()
	_dtbButton.ALL = field.NewAsterisk(tableName)
	_dtbButton.ID = field.NewUint32(tableName, "id")
	_dtbButton.Button1 = field.NewString(tableName, "button_1")
	_dtbButton.Button1English = field.NewString(tableName, "button_1_english")
	_dtbButton.Button2 = field.NewString(tableName, "button_2")
	_dtbButton.Button2English = field.NewString(tableName, "button_2_english")
	_dtbButton.Button3 = field.NewString(tableName, "button_3")
	_dtbButton.Button3English = field.NewString(tableName, "button_3_english")

	_dtbButton.fillFieldMap()

	return _dtbButton
}

type dtbButton struct {
	dtbButtonDo

	ALL            field.Asterisk
	ID             field.Uint32 // 主键id
	Button1        field.String // 按钮1中文描述
	Button1English field.String // 按钮1英文描述
	Button2        field.String // 按钮2中文描述
	Button2English field.String // 按钮2英文描述
	Button3        field.String // 按钮3中文描述
	Button3English field.String // 按钮3英文描述

	fieldMap map[string]field.Expr
}

func (d dtbButton) Table(newTableName string) *dtbButton {
	d.dtbButtonDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dtbButton) As(alias string) *dtbButton {
	d.dtbButtonDo.DO = *(d.dtbButtonDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dtbButton) updateTableName(table string) *dtbButton {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Button1 = field.NewString(table, "button_1")
	d.Button1English = field.NewString(table, "button_1_english")
	d.Button2 = field.NewString(table, "button_2")
	d.Button2English = field.NewString(table, "button_2_english")
	d.Button3 = field.NewString(table, "button_3")
	d.Button3English = field.NewString(table, "button_3_english")

	d.fillFieldMap()

	return d
}

func (d *dtbButton) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dtbButton) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 7)
	d.fieldMap["id"] = d.ID
	d.fieldMap["button_1"] = d.Button1
	d.fieldMap["button_1_english"] = d.Button1English
	d.fieldMap["button_2"] = d.Button2
	d.fieldMap["button_2_english"] = d.Button2English
	d.fieldMap["button_3"] = d.Button3
	d.fieldMap["button_3_english"] = d.Button3English
}

func (d dtbButton) clone(db *gorm.DB) dtbButton {
	d.dtbButtonDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dtbButton) replaceDB(db *gorm.DB) dtbButton {
	d.dtbButtonDo.ReplaceDB(db)
	return d
}

type dtbButtonDo struct{ gen.DO }

type IDtbButtonDo interface {
	gen.SubQuery
	Debug() IDtbButtonDo
	WithContext(ctx context.Context) IDtbButtonDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDtbButtonDo
	WriteDB() IDtbButtonDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDtbButtonDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDtbButtonDo
	Not(conds ...gen.Condition) IDtbButtonDo
	Or(conds ...gen.Condition) IDtbButtonDo
	Select(conds ...field.Expr) IDtbButtonDo
	Where(conds ...gen.Condition) IDtbButtonDo
	Order(conds ...field.Expr) IDtbButtonDo
	Distinct(cols ...field.Expr) IDtbButtonDo
	Omit(cols ...field.Expr) IDtbButtonDo
	Join(table schema.Tabler, on ...field.Expr) IDtbButtonDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDtbButtonDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDtbButtonDo
	Group(cols ...field.Expr) IDtbButtonDo
	Having(conds ...gen.Condition) IDtbButtonDo
	Limit(limit int) IDtbButtonDo
	Offset(offset int) IDtbButtonDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbButtonDo
	Unscoped() IDtbButtonDo
	Create(values ...*model.DtbButton) error
	CreateInBatches(values []*model.DtbButton, batchSize int) error
	Save(values ...*model.DtbButton) error
	First() (*model.DtbButton, error)
	Take() (*model.DtbButton, error)
	Last() (*model.DtbButton, error)
	Find() ([]*model.DtbButton, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbButton, err error)
	FindInBatches(result *[]*model.DtbButton, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DtbButton) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDtbButtonDo
	Assign(attrs ...field.AssignExpr) IDtbButtonDo
	Joins(fields ...field.RelationField) IDtbButtonDo
	Preload(fields ...field.RelationField) IDtbButtonDo
	FirstOrInit() (*model.DtbButton, error)
	FirstOrCreate() (*model.DtbButton, error)
	FindByPage(offset int, limit int) (result []*model.DtbButton, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDtbButtonDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dtbButtonDo) Debug() IDtbButtonDo {
	return d.withDO(d.DO.Debug())
}

func (d dtbButtonDo) WithContext(ctx context.Context) IDtbButtonDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dtbButtonDo) ReadDB() IDtbButtonDo {
	return d.Clauses(dbresolver.Read)
}

func (d dtbButtonDo) WriteDB() IDtbButtonDo {
	return d.Clauses(dbresolver.Write)
}

func (d dtbButtonDo) Session(config *gorm.Session) IDtbButtonDo {
	return d.withDO(d.DO.Session(config))
}

func (d dtbButtonDo) Clauses(conds ...clause.Expression) IDtbButtonDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dtbButtonDo) Returning(value interface{}, columns ...string) IDtbButtonDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dtbButtonDo) Not(conds ...gen.Condition) IDtbButtonDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dtbButtonDo) Or(conds ...gen.Condition) IDtbButtonDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dtbButtonDo) Select(conds ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dtbButtonDo) Where(conds ...gen.Condition) IDtbButtonDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dtbButtonDo) Order(conds ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dtbButtonDo) Distinct(cols ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dtbButtonDo) Omit(cols ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dtbButtonDo) Join(table schema.Tabler, on ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dtbButtonDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dtbButtonDo) RightJoin(table schema.Tabler, on ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dtbButtonDo) Group(cols ...field.Expr) IDtbButtonDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dtbButtonDo) Having(conds ...gen.Condition) IDtbButtonDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dtbButtonDo) Limit(limit int) IDtbButtonDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dtbButtonDo) Offset(offset int) IDtbButtonDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dtbButtonDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbButtonDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dtbButtonDo) Unscoped() IDtbButtonDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dtbButtonDo) Create(values ...*model.DtbButton) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dtbButtonDo) CreateInBatches(values []*model.DtbButton, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dtbButtonDo) Save(values ...*model.DtbButton) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dtbButtonDo) First() (*model.DtbButton, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbButton), nil
	}
}

func (d dtbButtonDo) Take() (*model.DtbButton, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbButton), nil
	}
}

func (d dtbButtonDo) Last() (*model.DtbButton, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbButton), nil
	}
}

func (d dtbButtonDo) Find() ([]*model.DtbButton, error) {
	result, err := d.DO.Find()
	return result.([]*model.DtbButton), err
}

func (d dtbButtonDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbButton, err error) {
	buf := make([]*model.DtbButton, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dtbButtonDo) FindInBatches(result *[]*model.DtbButton, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dtbButtonDo) Attrs(attrs ...field.AssignExpr) IDtbButtonDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dtbButtonDo) Assign(attrs ...field.AssignExpr) IDtbButtonDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dtbButtonDo) Joins(fields ...field.RelationField) IDtbButtonDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dtbButtonDo) Preload(fields ...field.RelationField) IDtbButtonDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dtbButtonDo) FirstOrInit() (*model.DtbButton, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbButton), nil
	}
}

func (d dtbButtonDo) FirstOrCreate() (*model.DtbButton, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbButton), nil
	}
}

func (d dtbButtonDo) FindByPage(offset int, limit int) (result []*model.DtbButton, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dtbButtonDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dtbButtonDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dtbButtonDo) Delete(models ...*model.DtbButton) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dtbButtonDo) withDO(do gen.Dao) *dtbButtonDo {
	d.DO = *do.(*gen.DO)
	return d
}
