// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newEySetting(db *gorm.DB, opts ...gen.DOOption) eySetting {
	_eySetting := eySetting{}

	_eySetting.eySettingDo.UseDB(db, opts...)
	_eySetting.eySettingDo.UseModel(&model.EySetting{})

	tableName := _eySetting.eySettingDo.TableName()
	_eySetting.ALL = field.NewAsterisk(tableName)
	_eySetting.Key = field.NewString(tableName, "key")
	_eySetting.Value = field.NewString(tableName, "value")

	_eySetting.fillFieldMap()

	return _eySetting
}

type eySetting struct {
	eySettingDo

	ALL   field.Asterisk
	Key   field.String
	Value field.String

	fieldMap map[string]field.Expr
}

func (e eySetting) Table(newTableName string) *eySetting {
	e.eySettingDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eySetting) As(alias string) *eySetting {
	e.eySettingDo.DO = *(e.eySettingDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eySetting) updateTableName(table string) *eySetting {
	e.ALL = field.NewAsterisk(table)
	e.Key = field.NewString(table, "key")
	e.Value = field.NewString(table, "value")

	e.fillFieldMap()

	return e
}

func (e *eySetting) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eySetting) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 2)
	e.fieldMap["key"] = e.Key
	e.fieldMap["value"] = e.Value
}

func (e eySetting) clone(db *gorm.DB) eySetting {
	e.eySettingDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eySetting) replaceDB(db *gorm.DB) eySetting {
	e.eySettingDo.ReplaceDB(db)
	return e
}

type eySettingDo struct{ gen.DO }

type IEySettingDo interface {
	gen.SubQuery
	Debug() IEySettingDo
	WithContext(ctx context.Context) IEySettingDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEySettingDo
	WriteDB() IEySettingDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEySettingDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEySettingDo
	Not(conds ...gen.Condition) IEySettingDo
	Or(conds ...gen.Condition) IEySettingDo
	Select(conds ...field.Expr) IEySettingDo
	Where(conds ...gen.Condition) IEySettingDo
	Order(conds ...field.Expr) IEySettingDo
	Distinct(cols ...field.Expr) IEySettingDo
	Omit(cols ...field.Expr) IEySettingDo
	Join(table schema.Tabler, on ...field.Expr) IEySettingDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEySettingDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEySettingDo
	Group(cols ...field.Expr) IEySettingDo
	Having(conds ...gen.Condition) IEySettingDo
	Limit(limit int) IEySettingDo
	Offset(offset int) IEySettingDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEySettingDo
	Unscoped() IEySettingDo
	Create(values ...*model.EySetting) error
	CreateInBatches(values []*model.EySetting, batchSize int) error
	Save(values ...*model.EySetting) error
	First() (*model.EySetting, error)
	Take() (*model.EySetting, error)
	Last() (*model.EySetting, error)
	Find() ([]*model.EySetting, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EySetting, err error)
	FindInBatches(result *[]*model.EySetting, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EySetting) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEySettingDo
	Assign(attrs ...field.AssignExpr) IEySettingDo
	Joins(fields ...field.RelationField) IEySettingDo
	Preload(fields ...field.RelationField) IEySettingDo
	FirstOrInit() (*model.EySetting, error)
	FirstOrCreate() (*model.EySetting, error)
	FindByPage(offset int, limit int) (result []*model.EySetting, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEySettingDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eySettingDo) Debug() IEySettingDo {
	return e.withDO(e.DO.Debug())
}

func (e eySettingDo) WithContext(ctx context.Context) IEySettingDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eySettingDo) ReadDB() IEySettingDo {
	return e.Clauses(dbresolver.Read)
}

func (e eySettingDo) WriteDB() IEySettingDo {
	return e.Clauses(dbresolver.Write)
}

func (e eySettingDo) Session(config *gorm.Session) IEySettingDo {
	return e.withDO(e.DO.Session(config))
}

func (e eySettingDo) Clauses(conds ...clause.Expression) IEySettingDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eySettingDo) Returning(value interface{}, columns ...string) IEySettingDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eySettingDo) Not(conds ...gen.Condition) IEySettingDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eySettingDo) Or(conds ...gen.Condition) IEySettingDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eySettingDo) Select(conds ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eySettingDo) Where(conds ...gen.Condition) IEySettingDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eySettingDo) Order(conds ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eySettingDo) Distinct(cols ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eySettingDo) Omit(cols ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eySettingDo) Join(table schema.Tabler, on ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eySettingDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eySettingDo) RightJoin(table schema.Tabler, on ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eySettingDo) Group(cols ...field.Expr) IEySettingDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eySettingDo) Having(conds ...gen.Condition) IEySettingDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eySettingDo) Limit(limit int) IEySettingDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eySettingDo) Offset(offset int) IEySettingDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eySettingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEySettingDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eySettingDo) Unscoped() IEySettingDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eySettingDo) Create(values ...*model.EySetting) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eySettingDo) CreateInBatches(values []*model.EySetting, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eySettingDo) Save(values ...*model.EySetting) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eySettingDo) First() (*model.EySetting, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EySetting), nil
	}
}

func (e eySettingDo) Take() (*model.EySetting, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EySetting), nil
	}
}

func (e eySettingDo) Last() (*model.EySetting, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EySetting), nil
	}
}

func (e eySettingDo) Find() ([]*model.EySetting, error) {
	result, err := e.DO.Find()
	return result.([]*model.EySetting), err
}

func (e eySettingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EySetting, err error) {
	buf := make([]*model.EySetting, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eySettingDo) FindInBatches(result *[]*model.EySetting, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eySettingDo) Attrs(attrs ...field.AssignExpr) IEySettingDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eySettingDo) Assign(attrs ...field.AssignExpr) IEySettingDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eySettingDo) Joins(fields ...field.RelationField) IEySettingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eySettingDo) Preload(fields ...field.RelationField) IEySettingDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eySettingDo) FirstOrInit() (*model.EySetting, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EySetting), nil
	}
}

func (e eySettingDo) FirstOrCreate() (*model.EySetting, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EySetting), nil
	}
}

func (e eySettingDo) FindByPage(offset int, limit int) (result []*model.EySetting, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eySettingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eySettingDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eySettingDo) Delete(models ...*model.EySetting) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eySettingDo) withDO(do gen.Dao) *eySettingDo {
	e.DO = *do.(*gen.DO)
	return e
}
