// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newEyTime(db *gorm.DB, opts ...gen.DOOption) eyTime {
	_eyTime := eyTime{}

	_eyTime.eyTimeDo.UseDB(db, opts...)
	_eyTime.eyTimeDo.UseModel(&model.EyTime{})

	tableName := _eyTime.eyTimeDo.TableName()
	_eyTime.ALL = field.NewAsterisk(tableName)
	_eyTime.Username = field.NewString(tableName, "username")
	_eyTime.IP = field.NewString(tableName, "ip")
	_eyTime.Logintime = field.NewUint32(tableName, "logintime")
	_eyTime.Isadmin = field.NewBool(tableName, "isadmin")
	_eyTime.Times = field.NewUint32(tableName, "times")

	_eyTime.fillFieldMap()

	return _eyTime
}

type eyTime struct {
	eyTimeDo

	ALL       field.Asterisk
	Username  field.String
	IP        field.String
	Logintime field.Uint32
	Isadmin   field.Bool
	Times     field.Uint32

	fieldMap map[string]field.Expr
}

func (e eyTime) Table(newTableName string) *eyTime {
	e.eyTimeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eyTime) As(alias string) *eyTime {
	e.eyTimeDo.DO = *(e.eyTimeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eyTime) updateTableName(table string) *eyTime {
	e.ALL = field.NewAsterisk(table)
	e.Username = field.NewString(table, "username")
	e.IP = field.NewString(table, "ip")
	e.Logintime = field.NewUint32(table, "logintime")
	e.Isadmin = field.NewBool(table, "isadmin")
	e.Times = field.NewUint32(table, "times")

	e.fillFieldMap()

	return e
}

func (e *eyTime) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eyTime) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 5)
	e.fieldMap["username"] = e.Username
	e.fieldMap["ip"] = e.IP
	e.fieldMap["logintime"] = e.Logintime
	e.fieldMap["isadmin"] = e.Isadmin
	e.fieldMap["times"] = e.Times
}

func (e eyTime) clone(db *gorm.DB) eyTime {
	e.eyTimeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eyTime) replaceDB(db *gorm.DB) eyTime {
	e.eyTimeDo.ReplaceDB(db)
	return e
}

type eyTimeDo struct{ gen.DO }

type IEyTimeDo interface {
	gen.SubQuery
	Debug() IEyTimeDo
	WithContext(ctx context.Context) IEyTimeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEyTimeDo
	WriteDB() IEyTimeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEyTimeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEyTimeDo
	Not(conds ...gen.Condition) IEyTimeDo
	Or(conds ...gen.Condition) IEyTimeDo
	Select(conds ...field.Expr) IEyTimeDo
	Where(conds ...gen.Condition) IEyTimeDo
	Order(conds ...field.Expr) IEyTimeDo
	Distinct(cols ...field.Expr) IEyTimeDo
	Omit(cols ...field.Expr) IEyTimeDo
	Join(table schema.Tabler, on ...field.Expr) IEyTimeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEyTimeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEyTimeDo
	Group(cols ...field.Expr) IEyTimeDo
	Having(conds ...gen.Condition) IEyTimeDo
	Limit(limit int) IEyTimeDo
	Offset(offset int) IEyTimeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEyTimeDo
	Unscoped() IEyTimeDo
	Create(values ...*model.EyTime) error
	CreateInBatches(values []*model.EyTime, batchSize int) error
	Save(values ...*model.EyTime) error
	First() (*model.EyTime, error)
	Take() (*model.EyTime, error)
	Last() (*model.EyTime, error)
	Find() ([]*model.EyTime, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EyTime, err error)
	FindInBatches(result *[]*model.EyTime, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EyTime) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEyTimeDo
	Assign(attrs ...field.AssignExpr) IEyTimeDo
	Joins(fields ...field.RelationField) IEyTimeDo
	Preload(fields ...field.RelationField) IEyTimeDo
	FirstOrInit() (*model.EyTime, error)
	FirstOrCreate() (*model.EyTime, error)
	FindByPage(offset int, limit int) (result []*model.EyTime, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEyTimeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eyTimeDo) Debug() IEyTimeDo {
	return e.withDO(e.DO.Debug())
}

func (e eyTimeDo) WithContext(ctx context.Context) IEyTimeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eyTimeDo) ReadDB() IEyTimeDo {
	return e.Clauses(dbresolver.Read)
}

func (e eyTimeDo) WriteDB() IEyTimeDo {
	return e.Clauses(dbresolver.Write)
}

func (e eyTimeDo) Session(config *gorm.Session) IEyTimeDo {
	return e.withDO(e.DO.Session(config))
}

func (e eyTimeDo) Clauses(conds ...clause.Expression) IEyTimeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eyTimeDo) Returning(value interface{}, columns ...string) IEyTimeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eyTimeDo) Not(conds ...gen.Condition) IEyTimeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eyTimeDo) Or(conds ...gen.Condition) IEyTimeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eyTimeDo) Select(conds ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eyTimeDo) Where(conds ...gen.Condition) IEyTimeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eyTimeDo) Order(conds ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eyTimeDo) Distinct(cols ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eyTimeDo) Omit(cols ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eyTimeDo) Join(table schema.Tabler, on ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eyTimeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eyTimeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eyTimeDo) Group(cols ...field.Expr) IEyTimeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eyTimeDo) Having(conds ...gen.Condition) IEyTimeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eyTimeDo) Limit(limit int) IEyTimeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eyTimeDo) Offset(offset int) IEyTimeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eyTimeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEyTimeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eyTimeDo) Unscoped() IEyTimeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eyTimeDo) Create(values ...*model.EyTime) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eyTimeDo) CreateInBatches(values []*model.EyTime, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eyTimeDo) Save(values ...*model.EyTime) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eyTimeDo) First() (*model.EyTime, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EyTime), nil
	}
}

func (e eyTimeDo) Take() (*model.EyTime, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EyTime), nil
	}
}

func (e eyTimeDo) Last() (*model.EyTime, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EyTime), nil
	}
}

func (e eyTimeDo) Find() ([]*model.EyTime, error) {
	result, err := e.DO.Find()
	return result.([]*model.EyTime), err
}

func (e eyTimeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EyTime, err error) {
	buf := make([]*model.EyTime, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eyTimeDo) FindInBatches(result *[]*model.EyTime, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eyTimeDo) Attrs(attrs ...field.AssignExpr) IEyTimeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eyTimeDo) Assign(attrs ...field.AssignExpr) IEyTimeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eyTimeDo) Joins(fields ...field.RelationField) IEyTimeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eyTimeDo) Preload(fields ...field.RelationField) IEyTimeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eyTimeDo) FirstOrInit() (*model.EyTime, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EyTime), nil
	}
}

func (e eyTimeDo) FirstOrCreate() (*model.EyTime, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EyTime), nil
	}
}

func (e eyTimeDo) FindByPage(offset int, limit int) (result []*model.EyTime, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eyTimeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eyTimeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eyTimeDo) Delete(models ...*model.EyTime) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eyTimeDo) withDO(do gen.Dao) *eyTimeDo {
	e.DO = *do.(*gen.DO)
	return e
}
