// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newIncomeRatioTemplateInfo(db *gorm.DB, opts ...gen.DOOption) incomeRatioTemplateInfo {
	_incomeRatioTemplateInfo := incomeRatioTemplateInfo{}

	_incomeRatioTemplateInfo.incomeRatioTemplateInfoDo.UseDB(db, opts...)
	_incomeRatioTemplateInfo.incomeRatioTemplateInfoDo.UseModel(&model.IncomeRatioTemplateInfo{})

	tableName := _incomeRatioTemplateInfo.incomeRatioTemplateInfoDo.TableName()
	_incomeRatioTemplateInfo.ALL = field.NewAsterisk(tableName)
	_incomeRatioTemplateInfo.ID = field.NewInt32(tableName, "id")
	_incomeRatioTemplateInfo.Name = field.NewString(tableName, "name")
	_incomeRatioTemplateInfo.Content = field.NewString(tableName, "content")
	_incomeRatioTemplateInfo.State = field.NewUint32(tableName, "state")
	_incomeRatioTemplateInfo.CreateTime = field.NewUint64(tableName, "create_time")
	_incomeRatioTemplateInfo.UpdateTime = field.NewInt64(tableName, "update_time")

	_incomeRatioTemplateInfo.fillFieldMap()

	return _incomeRatioTemplateInfo
}

// incomeRatioTemplateInfo 比率模板数据
type incomeRatioTemplateInfo struct {
	incomeRatioTemplateInfoDo

	ALL        field.Asterisk
	ID         field.Int32
	Name       field.String // 模板名称
	Content    field.String // json串，比例详情
	State      field.Uint32 // 状态 0关闭, 1开启
	CreateTime field.Uint64 // 创建时间
	UpdateTime field.Int64  // 更新时间

	fieldMap map[string]field.Expr
}

func (i incomeRatioTemplateInfo) Table(newTableName string) *incomeRatioTemplateInfo {
	i.incomeRatioTemplateInfoDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i incomeRatioTemplateInfo) As(alias string) *incomeRatioTemplateInfo {
	i.incomeRatioTemplateInfoDo.DO = *(i.incomeRatioTemplateInfoDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *incomeRatioTemplateInfo) updateTableName(table string) *incomeRatioTemplateInfo {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt32(table, "id")
	i.Name = field.NewString(table, "name")
	i.Content = field.NewString(table, "content")
	i.State = field.NewUint32(table, "state")
	i.CreateTime = field.NewUint64(table, "create_time")
	i.UpdateTime = field.NewInt64(table, "update_time")

	i.fillFieldMap()

	return i
}

func (i *incomeRatioTemplateInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *incomeRatioTemplateInfo) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 6)
	i.fieldMap["id"] = i.ID
	i.fieldMap["name"] = i.Name
	i.fieldMap["content"] = i.Content
	i.fieldMap["state"] = i.State
	i.fieldMap["create_time"] = i.CreateTime
	i.fieldMap["update_time"] = i.UpdateTime
}

func (i incomeRatioTemplateInfo) clone(db *gorm.DB) incomeRatioTemplateInfo {
	i.incomeRatioTemplateInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i incomeRatioTemplateInfo) replaceDB(db *gorm.DB) incomeRatioTemplateInfo {
	i.incomeRatioTemplateInfoDo.ReplaceDB(db)
	return i
}

type incomeRatioTemplateInfoDo struct{ gen.DO }

type IIncomeRatioTemplateInfoDo interface {
	gen.SubQuery
	Debug() IIncomeRatioTemplateInfoDo
	WithContext(ctx context.Context) IIncomeRatioTemplateInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIncomeRatioTemplateInfoDo
	WriteDB() IIncomeRatioTemplateInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIncomeRatioTemplateInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIncomeRatioTemplateInfoDo
	Not(conds ...gen.Condition) IIncomeRatioTemplateInfoDo
	Or(conds ...gen.Condition) IIncomeRatioTemplateInfoDo
	Select(conds ...field.Expr) IIncomeRatioTemplateInfoDo
	Where(conds ...gen.Condition) IIncomeRatioTemplateInfoDo
	Order(conds ...field.Expr) IIncomeRatioTemplateInfoDo
	Distinct(cols ...field.Expr) IIncomeRatioTemplateInfoDo
	Omit(cols ...field.Expr) IIncomeRatioTemplateInfoDo
	Join(table schema.Tabler, on ...field.Expr) IIncomeRatioTemplateInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIncomeRatioTemplateInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIncomeRatioTemplateInfoDo
	Group(cols ...field.Expr) IIncomeRatioTemplateInfoDo
	Having(conds ...gen.Condition) IIncomeRatioTemplateInfoDo
	Limit(limit int) IIncomeRatioTemplateInfoDo
	Offset(offset int) IIncomeRatioTemplateInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIncomeRatioTemplateInfoDo
	Unscoped() IIncomeRatioTemplateInfoDo
	Create(values ...*model.IncomeRatioTemplateInfo) error
	CreateInBatches(values []*model.IncomeRatioTemplateInfo, batchSize int) error
	Save(values ...*model.IncomeRatioTemplateInfo) error
	First() (*model.IncomeRatioTemplateInfo, error)
	Take() (*model.IncomeRatioTemplateInfo, error)
	Last() (*model.IncomeRatioTemplateInfo, error)
	Find() ([]*model.IncomeRatioTemplateInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IncomeRatioTemplateInfo, err error)
	FindInBatches(result *[]*model.IncomeRatioTemplateInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IncomeRatioTemplateInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIncomeRatioTemplateInfoDo
	Assign(attrs ...field.AssignExpr) IIncomeRatioTemplateInfoDo
	Joins(fields ...field.RelationField) IIncomeRatioTemplateInfoDo
	Preload(fields ...field.RelationField) IIncomeRatioTemplateInfoDo
	FirstOrInit() (*model.IncomeRatioTemplateInfo, error)
	FirstOrCreate() (*model.IncomeRatioTemplateInfo, error)
	FindByPage(offset int, limit int) (result []*model.IncomeRatioTemplateInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIncomeRatioTemplateInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i incomeRatioTemplateInfoDo) Debug() IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Debug())
}

func (i incomeRatioTemplateInfoDo) WithContext(ctx context.Context) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i incomeRatioTemplateInfoDo) ReadDB() IIncomeRatioTemplateInfoDo {
	return i.Clauses(dbresolver.Read)
}

func (i incomeRatioTemplateInfoDo) WriteDB() IIncomeRatioTemplateInfoDo {
	return i.Clauses(dbresolver.Write)
}

func (i incomeRatioTemplateInfoDo) Session(config *gorm.Session) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Session(config))
}

func (i incomeRatioTemplateInfoDo) Clauses(conds ...clause.Expression) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i incomeRatioTemplateInfoDo) Returning(value interface{}, columns ...string) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i incomeRatioTemplateInfoDo) Not(conds ...gen.Condition) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i incomeRatioTemplateInfoDo) Or(conds ...gen.Condition) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i incomeRatioTemplateInfoDo) Select(conds ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i incomeRatioTemplateInfoDo) Where(conds ...gen.Condition) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i incomeRatioTemplateInfoDo) Order(conds ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i incomeRatioTemplateInfoDo) Distinct(cols ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i incomeRatioTemplateInfoDo) Omit(cols ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i incomeRatioTemplateInfoDo) Join(table schema.Tabler, on ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i incomeRatioTemplateInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i incomeRatioTemplateInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i incomeRatioTemplateInfoDo) Group(cols ...field.Expr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i incomeRatioTemplateInfoDo) Having(conds ...gen.Condition) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i incomeRatioTemplateInfoDo) Limit(limit int) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i incomeRatioTemplateInfoDo) Offset(offset int) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i incomeRatioTemplateInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i incomeRatioTemplateInfoDo) Unscoped() IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Unscoped())
}

func (i incomeRatioTemplateInfoDo) Create(values ...*model.IncomeRatioTemplateInfo) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i incomeRatioTemplateInfoDo) CreateInBatches(values []*model.IncomeRatioTemplateInfo, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i incomeRatioTemplateInfoDo) Save(values ...*model.IncomeRatioTemplateInfo) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i incomeRatioTemplateInfoDo) First() (*model.IncomeRatioTemplateInfo, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IncomeRatioTemplateInfo), nil
	}
}

func (i incomeRatioTemplateInfoDo) Take() (*model.IncomeRatioTemplateInfo, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IncomeRatioTemplateInfo), nil
	}
}

func (i incomeRatioTemplateInfoDo) Last() (*model.IncomeRatioTemplateInfo, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IncomeRatioTemplateInfo), nil
	}
}

func (i incomeRatioTemplateInfoDo) Find() ([]*model.IncomeRatioTemplateInfo, error) {
	result, err := i.DO.Find()
	return result.([]*model.IncomeRatioTemplateInfo), err
}

func (i incomeRatioTemplateInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IncomeRatioTemplateInfo, err error) {
	buf := make([]*model.IncomeRatioTemplateInfo, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i incomeRatioTemplateInfoDo) FindInBatches(result *[]*model.IncomeRatioTemplateInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i incomeRatioTemplateInfoDo) Attrs(attrs ...field.AssignExpr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i incomeRatioTemplateInfoDo) Assign(attrs ...field.AssignExpr) IIncomeRatioTemplateInfoDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i incomeRatioTemplateInfoDo) Joins(fields ...field.RelationField) IIncomeRatioTemplateInfoDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i incomeRatioTemplateInfoDo) Preload(fields ...field.RelationField) IIncomeRatioTemplateInfoDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i incomeRatioTemplateInfoDo) FirstOrInit() (*model.IncomeRatioTemplateInfo, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IncomeRatioTemplateInfo), nil
	}
}

func (i incomeRatioTemplateInfoDo) FirstOrCreate() (*model.IncomeRatioTemplateInfo, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IncomeRatioTemplateInfo), nil
	}
}

func (i incomeRatioTemplateInfoDo) FindByPage(offset int, limit int) (result []*model.IncomeRatioTemplateInfo, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i incomeRatioTemplateInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i incomeRatioTemplateInfoDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i incomeRatioTemplateInfoDo) Delete(models ...*model.IncomeRatioTemplateInfo) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *incomeRatioTemplateInfoDo) withDO(do gen.Dao) *incomeRatioTemplateInfoDo {
	i.DO = *do.(*gen.DO)
	return i
}
