// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newKycStatus(db *gorm.DB, opts ...gen.DOOption) kycStatus {
	_kycStatus := kycStatus{}

	_kycStatus.kycStatusDo.UseDB(db, opts...)
	_kycStatus.kycStatusDo.UseModel(&model.KycStatus{})

	tableName := _kycStatus.kycStatusDo.TableName()
	_kycStatus.ALL = field.NewAsterisk(tableName)
	_kycStatus.ID = field.NewUint64(tableName, "id")
	_kycStatus.UserID = field.NewInt32(tableName, "user_id")
	_kycStatus.PlatformType = field.NewInt32(tableName, "platform_type")
	_kycStatus.VerificationID = field.NewString(tableName, "verification_id")
	_kycStatus.Status = field.NewString(tableName, "status")
	_kycStatus.Host = field.NewString(tableName, "host")
	_kycStatus.SessionToken = field.NewString(tableName, "session_token")
	_kycStatus.URL = field.NewString(tableName, "url")
	_kycStatus.VendorData = field.NewString(tableName, "vendor_data")
	_kycStatus.CreatedAt = field.NewTime(tableName, "created_at")
	_kycStatus.UpdatedAt = field.NewTime(tableName, "updated_at")
	_kycStatus.Data = field.NewString(tableName, "data")
	_kycStatus.DeletedAt = field.NewField(tableName, "deleted_at")
	_kycStatus.ModifiedAddress = field.NewString(tableName, "modified_address")
	_kycStatus.ModifiedDateOfBirth = field.NewString(tableName, "modified_dateOfBirth")
	_kycStatus.ModifiedState = field.NewString(tableName, "modified_state")
	_kycStatus.ModifiedCountry = field.NewString(tableName, "modified_country")
	_kycStatus.ModifiedStatus = field.NewString(tableName, "modified_status")
	_kycStatus.ModifiedFirstName = field.NewString(tableName, "modified_firstName")
	_kycStatus.ModifiedLastName = field.NewString(tableName, "modified_lastName")
	_kycStatus.ModifiedCity = field.NewString(tableName, "modified_city")
	_kycStatus.ModifiedStreet = field.NewString(tableName, "modified_street")
	_kycStatus.ModifiedPostalCode = field.NewString(tableName, "modified_postalCode")
	_kycStatus.ModifiedReason = field.NewString(tableName, "modified_reason")

	_kycStatus.fillFieldMap()

	return _kycStatus
}

// kycStatus KYC状态表
type kycStatus struct {
	kycStatusDo

	ALL                 field.Asterisk
	ID                  field.Uint64 // 唯一标识符
	UserID              field.Int32  // 用户ID
	PlatformType        field.Int32  // 0: clubwpt, 1: prelaunch
	VerificationID      field.String // Veriff验证ID
	Status              field.String // 验证状态
	Host                field.String // Veriff会话主机URL
	SessionToken        field.String // Veriff会话令牌
	URL                 field.String // Veriff验证URL
	VendorData          field.String // 供应商数据
	CreatedAt           field.Time   // 记录创建时间
	UpdatedAt           field.Time   // 记录更新时间
	Data                field.String // 附加数据
	DeletedAt           field.Field  // 记录删除时间
	ModifiedAddress     field.String // 手工更改地址
	ModifiedDateOfBirth field.String // 用户的出生日期
	ModifiedState       field.String // 用户的州/省
	ModifiedCountry     field.String // 用户的国家
	ModifiedStatus      field.String // 修改后的状态
	ModifiedFirstName   field.String // 修改后的名
	ModifiedLastName    field.String // 修改后的姓
	ModifiedCity        field.String // 手動更改城市
	ModifiedStreet      field.String // 手動更改街道
	ModifiedPostalCode  field.String // 手動更改邮政编码
	ModifiedReason      field.String // 修改原因

	fieldMap map[string]field.Expr
}

func (k kycStatus) Table(newTableName string) *kycStatus {
	k.kycStatusDo.UseTable(newTableName)
	return k.updateTableName(newTableName)
}

func (k kycStatus) As(alias string) *kycStatus {
	k.kycStatusDo.DO = *(k.kycStatusDo.As(alias).(*gen.DO))
	return k.updateTableName(alias)
}

func (k *kycStatus) updateTableName(table string) *kycStatus {
	k.ALL = field.NewAsterisk(table)
	k.ID = field.NewUint64(table, "id")
	k.UserID = field.NewInt32(table, "user_id")
	k.PlatformType = field.NewInt32(table, "platform_type")
	k.VerificationID = field.NewString(table, "verification_id")
	k.Status = field.NewString(table, "status")
	k.Host = field.NewString(table, "host")
	k.SessionToken = field.NewString(table, "session_token")
	k.URL = field.NewString(table, "url")
	k.VendorData = field.NewString(table, "vendor_data")
	k.CreatedAt = field.NewTime(table, "created_at")
	k.UpdatedAt = field.NewTime(table, "updated_at")
	k.Data = field.NewString(table, "data")
	k.DeletedAt = field.NewField(table, "deleted_at")
	k.ModifiedAddress = field.NewString(table, "modified_address")
	k.ModifiedDateOfBirth = field.NewString(table, "modified_dateOfBirth")
	k.ModifiedState = field.NewString(table, "modified_state")
	k.ModifiedCountry = field.NewString(table, "modified_country")
	k.ModifiedStatus = field.NewString(table, "modified_status")
	k.ModifiedFirstName = field.NewString(table, "modified_firstName")
	k.ModifiedLastName = field.NewString(table, "modified_lastName")
	k.ModifiedCity = field.NewString(table, "modified_city")
	k.ModifiedStreet = field.NewString(table, "modified_street")
	k.ModifiedPostalCode = field.NewString(table, "modified_postalCode")
	k.ModifiedReason = field.NewString(table, "modified_reason")

	k.fillFieldMap()

	return k
}

func (k *kycStatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := k.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (k *kycStatus) fillFieldMap() {
	k.fieldMap = make(map[string]field.Expr, 24)
	k.fieldMap["id"] = k.ID
	k.fieldMap["user_id"] = k.UserID
	k.fieldMap["platform_type"] = k.PlatformType
	k.fieldMap["verification_id"] = k.VerificationID
	k.fieldMap["status"] = k.Status
	k.fieldMap["host"] = k.Host
	k.fieldMap["session_token"] = k.SessionToken
	k.fieldMap["url"] = k.URL
	k.fieldMap["vendor_data"] = k.VendorData
	k.fieldMap["created_at"] = k.CreatedAt
	k.fieldMap["updated_at"] = k.UpdatedAt
	k.fieldMap["data"] = k.Data
	k.fieldMap["deleted_at"] = k.DeletedAt
	k.fieldMap["modified_address"] = k.ModifiedAddress
	k.fieldMap["modified_dateOfBirth"] = k.ModifiedDateOfBirth
	k.fieldMap["modified_state"] = k.ModifiedState
	k.fieldMap["modified_country"] = k.ModifiedCountry
	k.fieldMap["modified_status"] = k.ModifiedStatus
	k.fieldMap["modified_firstName"] = k.ModifiedFirstName
	k.fieldMap["modified_lastName"] = k.ModifiedLastName
	k.fieldMap["modified_city"] = k.ModifiedCity
	k.fieldMap["modified_street"] = k.ModifiedStreet
	k.fieldMap["modified_postalCode"] = k.ModifiedPostalCode
	k.fieldMap["modified_reason"] = k.ModifiedReason
}

func (k kycStatus) clone(db *gorm.DB) kycStatus {
	k.kycStatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return k
}

func (k kycStatus) replaceDB(db *gorm.DB) kycStatus {
	k.kycStatusDo.ReplaceDB(db)
	return k
}

type kycStatusDo struct{ gen.DO }

type IKycStatusDo interface {
	gen.SubQuery
	Debug() IKycStatusDo
	WithContext(ctx context.Context) IKycStatusDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IKycStatusDo
	WriteDB() IKycStatusDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IKycStatusDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IKycStatusDo
	Not(conds ...gen.Condition) IKycStatusDo
	Or(conds ...gen.Condition) IKycStatusDo
	Select(conds ...field.Expr) IKycStatusDo
	Where(conds ...gen.Condition) IKycStatusDo
	Order(conds ...field.Expr) IKycStatusDo
	Distinct(cols ...field.Expr) IKycStatusDo
	Omit(cols ...field.Expr) IKycStatusDo
	Join(table schema.Tabler, on ...field.Expr) IKycStatusDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IKycStatusDo
	RightJoin(table schema.Tabler, on ...field.Expr) IKycStatusDo
	Group(cols ...field.Expr) IKycStatusDo
	Having(conds ...gen.Condition) IKycStatusDo
	Limit(limit int) IKycStatusDo
	Offset(offset int) IKycStatusDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IKycStatusDo
	Unscoped() IKycStatusDo
	Create(values ...*model.KycStatus) error
	CreateInBatches(values []*model.KycStatus, batchSize int) error
	Save(values ...*model.KycStatus) error
	First() (*model.KycStatus, error)
	Take() (*model.KycStatus, error)
	Last() (*model.KycStatus, error)
	Find() ([]*model.KycStatus, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KycStatus, err error)
	FindInBatches(result *[]*model.KycStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.KycStatus) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IKycStatusDo
	Assign(attrs ...field.AssignExpr) IKycStatusDo
	Joins(fields ...field.RelationField) IKycStatusDo
	Preload(fields ...field.RelationField) IKycStatusDo
	FirstOrInit() (*model.KycStatus, error)
	FirstOrCreate() (*model.KycStatus, error)
	FindByPage(offset int, limit int) (result []*model.KycStatus, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IKycStatusDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (k kycStatusDo) Debug() IKycStatusDo {
	return k.withDO(k.DO.Debug())
}

func (k kycStatusDo) WithContext(ctx context.Context) IKycStatusDo {
	return k.withDO(k.DO.WithContext(ctx))
}

func (k kycStatusDo) ReadDB() IKycStatusDo {
	return k.Clauses(dbresolver.Read)
}

func (k kycStatusDo) WriteDB() IKycStatusDo {
	return k.Clauses(dbresolver.Write)
}

func (k kycStatusDo) Session(config *gorm.Session) IKycStatusDo {
	return k.withDO(k.DO.Session(config))
}

func (k kycStatusDo) Clauses(conds ...clause.Expression) IKycStatusDo {
	return k.withDO(k.DO.Clauses(conds...))
}

func (k kycStatusDo) Returning(value interface{}, columns ...string) IKycStatusDo {
	return k.withDO(k.DO.Returning(value, columns...))
}

func (k kycStatusDo) Not(conds ...gen.Condition) IKycStatusDo {
	return k.withDO(k.DO.Not(conds...))
}

func (k kycStatusDo) Or(conds ...gen.Condition) IKycStatusDo {
	return k.withDO(k.DO.Or(conds...))
}

func (k kycStatusDo) Select(conds ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.Select(conds...))
}

func (k kycStatusDo) Where(conds ...gen.Condition) IKycStatusDo {
	return k.withDO(k.DO.Where(conds...))
}

func (k kycStatusDo) Order(conds ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.Order(conds...))
}

func (k kycStatusDo) Distinct(cols ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.Distinct(cols...))
}

func (k kycStatusDo) Omit(cols ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.Omit(cols...))
}

func (k kycStatusDo) Join(table schema.Tabler, on ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.Join(table, on...))
}

func (k kycStatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.LeftJoin(table, on...))
}

func (k kycStatusDo) RightJoin(table schema.Tabler, on ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.RightJoin(table, on...))
}

func (k kycStatusDo) Group(cols ...field.Expr) IKycStatusDo {
	return k.withDO(k.DO.Group(cols...))
}

func (k kycStatusDo) Having(conds ...gen.Condition) IKycStatusDo {
	return k.withDO(k.DO.Having(conds...))
}

func (k kycStatusDo) Limit(limit int) IKycStatusDo {
	return k.withDO(k.DO.Limit(limit))
}

func (k kycStatusDo) Offset(offset int) IKycStatusDo {
	return k.withDO(k.DO.Offset(offset))
}

func (k kycStatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IKycStatusDo {
	return k.withDO(k.DO.Scopes(funcs...))
}

func (k kycStatusDo) Unscoped() IKycStatusDo {
	return k.withDO(k.DO.Unscoped())
}

func (k kycStatusDo) Create(values ...*model.KycStatus) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Create(values)
}

func (k kycStatusDo) CreateInBatches(values []*model.KycStatus, batchSize int) error {
	return k.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (k kycStatusDo) Save(values ...*model.KycStatus) error {
	if len(values) == 0 {
		return nil
	}
	return k.DO.Save(values)
}

func (k kycStatusDo) First() (*model.KycStatus, error) {
	if result, err := k.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.KycStatus), nil
	}
}

func (k kycStatusDo) Take() (*model.KycStatus, error) {
	if result, err := k.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.KycStatus), nil
	}
}

func (k kycStatusDo) Last() (*model.KycStatus, error) {
	if result, err := k.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.KycStatus), nil
	}
}

func (k kycStatusDo) Find() ([]*model.KycStatus, error) {
	result, err := k.DO.Find()
	return result.([]*model.KycStatus), err
}

func (k kycStatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.KycStatus, err error) {
	buf := make([]*model.KycStatus, 0, batchSize)
	err = k.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (k kycStatusDo) FindInBatches(result *[]*model.KycStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return k.DO.FindInBatches(result, batchSize, fc)
}

func (k kycStatusDo) Attrs(attrs ...field.AssignExpr) IKycStatusDo {
	return k.withDO(k.DO.Attrs(attrs...))
}

func (k kycStatusDo) Assign(attrs ...field.AssignExpr) IKycStatusDo {
	return k.withDO(k.DO.Assign(attrs...))
}

func (k kycStatusDo) Joins(fields ...field.RelationField) IKycStatusDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Joins(_f))
	}
	return &k
}

func (k kycStatusDo) Preload(fields ...field.RelationField) IKycStatusDo {
	for _, _f := range fields {
		k = *k.withDO(k.DO.Preload(_f))
	}
	return &k
}

func (k kycStatusDo) FirstOrInit() (*model.KycStatus, error) {
	if result, err := k.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.KycStatus), nil
	}
}

func (k kycStatusDo) FirstOrCreate() (*model.KycStatus, error) {
	if result, err := k.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.KycStatus), nil
	}
}

func (k kycStatusDo) FindByPage(offset int, limit int) (result []*model.KycStatus, count int64, err error) {
	result, err = k.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = k.Offset(-1).Limit(-1).Count()
	return
}

func (k kycStatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = k.Count()
	if err != nil {
		return
	}

	err = k.Offset(offset).Limit(limit).Scan(result)
	return
}

func (k kycStatusDo) Scan(result interface{}) (err error) {
	return k.DO.Scan(result)
}

func (k kycStatusDo) Delete(models ...*model.KycStatus) (result gen.ResultInfo, err error) {
	return k.DO.Delete(models)
}

func (k *kycStatusDo) withDO(do gen.Dao) *kycStatusDo {
	k.DO = *do.(*gen.DO)
	return k
}
