// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newMemePropsUser(db *gorm.DB, opts ...gen.DOOption) memePropsUser {
	_memePropsUser := memePropsUser{}

	_memePropsUser.memePropsUserDo.UseDB(db, opts...)
	_memePropsUser.memePropsUserDo.UseModel(&model.MemePropsUser{})

	tableName := _memePropsUser.memePropsUserDo.TableName()
	_memePropsUser.ALL = field.NewAsterisk(tableName)
	_memePropsUser.UserID = field.NewInt32(tableName, "user_id")
	_memePropsUser.PropsID = field.NewInt32(tableName, "props_id")
	_memePropsUser.PropsTotal = field.NewInt32(tableName, "props_total")
	_memePropsUser.CreateTime = field.NewInt64(tableName, "create_time")
	_memePropsUser.UpdateTime = field.NewInt64(tableName, "update_time")

	_memePropsUser.fillFieldMap()

	return _memePropsUser
}

// memePropsUser 道具信息表
type memePropsUser struct {
	memePropsUserDo

	ALL        field.Asterisk
	UserID     field.Int32 // 玩家id
	PropsID    field.Int32 // 道具id
	PropsTotal field.Int32 // 数量
	CreateTime field.Int64 // 创建时间
	UpdateTime field.Int64 // 创建时间

	fieldMap map[string]field.Expr
}

func (m memePropsUser) Table(newTableName string) *memePropsUser {
	m.memePropsUserDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m memePropsUser) As(alias string) *memePropsUser {
	m.memePropsUserDo.DO = *(m.memePropsUserDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *memePropsUser) updateTableName(table string) *memePropsUser {
	m.ALL = field.NewAsterisk(table)
	m.UserID = field.NewInt32(table, "user_id")
	m.PropsID = field.NewInt32(table, "props_id")
	m.PropsTotal = field.NewInt32(table, "props_total")
	m.CreateTime = field.NewInt64(table, "create_time")
	m.UpdateTime = field.NewInt64(table, "update_time")

	m.fillFieldMap()

	return m
}

func (m *memePropsUser) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *memePropsUser) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 5)
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["props_id"] = m.PropsID
	m.fieldMap["props_total"] = m.PropsTotal
	m.fieldMap["create_time"] = m.CreateTime
	m.fieldMap["update_time"] = m.UpdateTime
}

func (m memePropsUser) clone(db *gorm.DB) memePropsUser {
	m.memePropsUserDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m memePropsUser) replaceDB(db *gorm.DB) memePropsUser {
	m.memePropsUserDo.ReplaceDB(db)
	return m
}

type memePropsUserDo struct{ gen.DO }

type IMemePropsUserDo interface {
	gen.SubQuery
	Debug() IMemePropsUserDo
	WithContext(ctx context.Context) IMemePropsUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMemePropsUserDo
	WriteDB() IMemePropsUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMemePropsUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMemePropsUserDo
	Not(conds ...gen.Condition) IMemePropsUserDo
	Or(conds ...gen.Condition) IMemePropsUserDo
	Select(conds ...field.Expr) IMemePropsUserDo
	Where(conds ...gen.Condition) IMemePropsUserDo
	Order(conds ...field.Expr) IMemePropsUserDo
	Distinct(cols ...field.Expr) IMemePropsUserDo
	Omit(cols ...field.Expr) IMemePropsUserDo
	Join(table schema.Tabler, on ...field.Expr) IMemePropsUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMemePropsUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMemePropsUserDo
	Group(cols ...field.Expr) IMemePropsUserDo
	Having(conds ...gen.Condition) IMemePropsUserDo
	Limit(limit int) IMemePropsUserDo
	Offset(offset int) IMemePropsUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMemePropsUserDo
	Unscoped() IMemePropsUserDo
	Create(values ...*model.MemePropsUser) error
	CreateInBatches(values []*model.MemePropsUser, batchSize int) error
	Save(values ...*model.MemePropsUser) error
	First() (*model.MemePropsUser, error)
	Take() (*model.MemePropsUser, error)
	Last() (*model.MemePropsUser, error)
	Find() ([]*model.MemePropsUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemePropsUser, err error)
	FindInBatches(result *[]*model.MemePropsUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MemePropsUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMemePropsUserDo
	Assign(attrs ...field.AssignExpr) IMemePropsUserDo
	Joins(fields ...field.RelationField) IMemePropsUserDo
	Preload(fields ...field.RelationField) IMemePropsUserDo
	FirstOrInit() (*model.MemePropsUser, error)
	FirstOrCreate() (*model.MemePropsUser, error)
	FindByPage(offset int, limit int) (result []*model.MemePropsUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMemePropsUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m memePropsUserDo) Debug() IMemePropsUserDo {
	return m.withDO(m.DO.Debug())
}

func (m memePropsUserDo) WithContext(ctx context.Context) IMemePropsUserDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m memePropsUserDo) ReadDB() IMemePropsUserDo {
	return m.Clauses(dbresolver.Read)
}

func (m memePropsUserDo) WriteDB() IMemePropsUserDo {
	return m.Clauses(dbresolver.Write)
}

func (m memePropsUserDo) Session(config *gorm.Session) IMemePropsUserDo {
	return m.withDO(m.DO.Session(config))
}

func (m memePropsUserDo) Clauses(conds ...clause.Expression) IMemePropsUserDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m memePropsUserDo) Returning(value interface{}, columns ...string) IMemePropsUserDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m memePropsUserDo) Not(conds ...gen.Condition) IMemePropsUserDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m memePropsUserDo) Or(conds ...gen.Condition) IMemePropsUserDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m memePropsUserDo) Select(conds ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m memePropsUserDo) Where(conds ...gen.Condition) IMemePropsUserDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m memePropsUserDo) Order(conds ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m memePropsUserDo) Distinct(cols ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m memePropsUserDo) Omit(cols ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m memePropsUserDo) Join(table schema.Tabler, on ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m memePropsUserDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m memePropsUserDo) RightJoin(table schema.Tabler, on ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m memePropsUserDo) Group(cols ...field.Expr) IMemePropsUserDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m memePropsUserDo) Having(conds ...gen.Condition) IMemePropsUserDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m memePropsUserDo) Limit(limit int) IMemePropsUserDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m memePropsUserDo) Offset(offset int) IMemePropsUserDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m memePropsUserDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMemePropsUserDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m memePropsUserDo) Unscoped() IMemePropsUserDo {
	return m.withDO(m.DO.Unscoped())
}

func (m memePropsUserDo) Create(values ...*model.MemePropsUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m memePropsUserDo) CreateInBatches(values []*model.MemePropsUser, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m memePropsUserDo) Save(values ...*model.MemePropsUser) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m memePropsUserDo) First() (*model.MemePropsUser, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemePropsUser), nil
	}
}

func (m memePropsUserDo) Take() (*model.MemePropsUser, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemePropsUser), nil
	}
}

func (m memePropsUserDo) Last() (*model.MemePropsUser, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemePropsUser), nil
	}
}

func (m memePropsUserDo) Find() ([]*model.MemePropsUser, error) {
	result, err := m.DO.Find()
	return result.([]*model.MemePropsUser), err
}

func (m memePropsUserDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MemePropsUser, err error) {
	buf := make([]*model.MemePropsUser, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m memePropsUserDo) FindInBatches(result *[]*model.MemePropsUser, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m memePropsUserDo) Attrs(attrs ...field.AssignExpr) IMemePropsUserDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m memePropsUserDo) Assign(attrs ...field.AssignExpr) IMemePropsUserDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m memePropsUserDo) Joins(fields ...field.RelationField) IMemePropsUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m memePropsUserDo) Preload(fields ...field.RelationField) IMemePropsUserDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m memePropsUserDo) FirstOrInit() (*model.MemePropsUser, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemePropsUser), nil
	}
}

func (m memePropsUserDo) FirstOrCreate() (*model.MemePropsUser, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MemePropsUser), nil
	}
}

func (m memePropsUserDo) FindByPage(offset int, limit int) (result []*model.MemePropsUser, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m memePropsUserDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m memePropsUserDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m memePropsUserDo) Delete(models ...*model.MemePropsUser) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *memePropsUserDo) withDO(do gen.Dao) *memePropsUserDo {
	m.DO = *do.(*gen.DO)
	return m
}
