// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newRewardsCurrencyCfg(db *gorm.DB, opts ...gen.DOOption) rewardsCurrencyCfg {
	_rewardsCurrencyCfg := rewardsCurrencyCfg{}

	_rewardsCurrencyCfg.rewardsCurrencyCfgDo.UseDB(db, opts...)
	_rewardsCurrencyCfg.rewardsCurrencyCfgDo.UseModel(&model.RewardsCurrencyCfg{})

	tableName := _rewardsCurrencyCfg.rewardsCurrencyCfgDo.TableName()
	_rewardsCurrencyCfg.ALL = field.NewAsterisk(tableName)
	_rewardsCurrencyCfg.ID = field.NewInt32(tableName, "id")
	_rewardsCurrencyCfg.CfgID = field.NewInt32(tableName, "cfg_id")
	_rewardsCurrencyCfg.Currency = field.NewInt32(tableName, "currency")
	_rewardsCurrencyCfg.Amount = field.NewInt32(tableName, "amount")

	_rewardsCurrencyCfg.fillFieldMap()

	return _rewardsCurrencyCfg
}

// rewardsCurrencyCfg 奖励金额配置
type rewardsCurrencyCfg struct {
	rewardsCurrencyCfgDo

	ALL      field.Asterisk
	ID       field.Int32
	CfgID    field.Int32
	Currency field.Int32
	Amount   field.Int32

	fieldMap map[string]field.Expr
}

func (r rewardsCurrencyCfg) Table(newTableName string) *rewardsCurrencyCfg {
	r.rewardsCurrencyCfgDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r rewardsCurrencyCfg) As(alias string) *rewardsCurrencyCfg {
	r.rewardsCurrencyCfgDo.DO = *(r.rewardsCurrencyCfgDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *rewardsCurrencyCfg) updateTableName(table string) *rewardsCurrencyCfg {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt32(table, "id")
	r.CfgID = field.NewInt32(table, "cfg_id")
	r.Currency = field.NewInt32(table, "currency")
	r.Amount = field.NewInt32(table, "amount")

	r.fillFieldMap()

	return r
}

func (r *rewardsCurrencyCfg) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *rewardsCurrencyCfg) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["id"] = r.ID
	r.fieldMap["cfg_id"] = r.CfgID
	r.fieldMap["currency"] = r.Currency
	r.fieldMap["amount"] = r.Amount
}

func (r rewardsCurrencyCfg) clone(db *gorm.DB) rewardsCurrencyCfg {
	r.rewardsCurrencyCfgDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r rewardsCurrencyCfg) replaceDB(db *gorm.DB) rewardsCurrencyCfg {
	r.rewardsCurrencyCfgDo.ReplaceDB(db)
	return r
}

type rewardsCurrencyCfgDo struct{ gen.DO }

type IRewardsCurrencyCfgDo interface {
	gen.SubQuery
	Debug() IRewardsCurrencyCfgDo
	WithContext(ctx context.Context) IRewardsCurrencyCfgDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRewardsCurrencyCfgDo
	WriteDB() IRewardsCurrencyCfgDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRewardsCurrencyCfgDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRewardsCurrencyCfgDo
	Not(conds ...gen.Condition) IRewardsCurrencyCfgDo
	Or(conds ...gen.Condition) IRewardsCurrencyCfgDo
	Select(conds ...field.Expr) IRewardsCurrencyCfgDo
	Where(conds ...gen.Condition) IRewardsCurrencyCfgDo
	Order(conds ...field.Expr) IRewardsCurrencyCfgDo
	Distinct(cols ...field.Expr) IRewardsCurrencyCfgDo
	Omit(cols ...field.Expr) IRewardsCurrencyCfgDo
	Join(table schema.Tabler, on ...field.Expr) IRewardsCurrencyCfgDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRewardsCurrencyCfgDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRewardsCurrencyCfgDo
	Group(cols ...field.Expr) IRewardsCurrencyCfgDo
	Having(conds ...gen.Condition) IRewardsCurrencyCfgDo
	Limit(limit int) IRewardsCurrencyCfgDo
	Offset(offset int) IRewardsCurrencyCfgDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRewardsCurrencyCfgDo
	Unscoped() IRewardsCurrencyCfgDo
	Create(values ...*model.RewardsCurrencyCfg) error
	CreateInBatches(values []*model.RewardsCurrencyCfg, batchSize int) error
	Save(values ...*model.RewardsCurrencyCfg) error
	First() (*model.RewardsCurrencyCfg, error)
	Take() (*model.RewardsCurrencyCfg, error)
	Last() (*model.RewardsCurrencyCfg, error)
	Find() ([]*model.RewardsCurrencyCfg, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RewardsCurrencyCfg, err error)
	FindInBatches(result *[]*model.RewardsCurrencyCfg, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RewardsCurrencyCfg) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRewardsCurrencyCfgDo
	Assign(attrs ...field.AssignExpr) IRewardsCurrencyCfgDo
	Joins(fields ...field.RelationField) IRewardsCurrencyCfgDo
	Preload(fields ...field.RelationField) IRewardsCurrencyCfgDo
	FirstOrInit() (*model.RewardsCurrencyCfg, error)
	FirstOrCreate() (*model.RewardsCurrencyCfg, error)
	FindByPage(offset int, limit int) (result []*model.RewardsCurrencyCfg, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRewardsCurrencyCfgDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r rewardsCurrencyCfgDo) Debug() IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Debug())
}

func (r rewardsCurrencyCfgDo) WithContext(ctx context.Context) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r rewardsCurrencyCfgDo) ReadDB() IRewardsCurrencyCfgDo {
	return r.Clauses(dbresolver.Read)
}

func (r rewardsCurrencyCfgDo) WriteDB() IRewardsCurrencyCfgDo {
	return r.Clauses(dbresolver.Write)
}

func (r rewardsCurrencyCfgDo) Session(config *gorm.Session) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Session(config))
}

func (r rewardsCurrencyCfgDo) Clauses(conds ...clause.Expression) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r rewardsCurrencyCfgDo) Returning(value interface{}, columns ...string) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r rewardsCurrencyCfgDo) Not(conds ...gen.Condition) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r rewardsCurrencyCfgDo) Or(conds ...gen.Condition) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r rewardsCurrencyCfgDo) Select(conds ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r rewardsCurrencyCfgDo) Where(conds ...gen.Condition) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r rewardsCurrencyCfgDo) Order(conds ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r rewardsCurrencyCfgDo) Distinct(cols ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r rewardsCurrencyCfgDo) Omit(cols ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r rewardsCurrencyCfgDo) Join(table schema.Tabler, on ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r rewardsCurrencyCfgDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r rewardsCurrencyCfgDo) RightJoin(table schema.Tabler, on ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r rewardsCurrencyCfgDo) Group(cols ...field.Expr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r rewardsCurrencyCfgDo) Having(conds ...gen.Condition) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r rewardsCurrencyCfgDo) Limit(limit int) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r rewardsCurrencyCfgDo) Offset(offset int) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r rewardsCurrencyCfgDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r rewardsCurrencyCfgDo) Unscoped() IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Unscoped())
}

func (r rewardsCurrencyCfgDo) Create(values ...*model.RewardsCurrencyCfg) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r rewardsCurrencyCfgDo) CreateInBatches(values []*model.RewardsCurrencyCfg, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r rewardsCurrencyCfgDo) Save(values ...*model.RewardsCurrencyCfg) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r rewardsCurrencyCfgDo) First() (*model.RewardsCurrencyCfg, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardsCurrencyCfg), nil
	}
}

func (r rewardsCurrencyCfgDo) Take() (*model.RewardsCurrencyCfg, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardsCurrencyCfg), nil
	}
}

func (r rewardsCurrencyCfgDo) Last() (*model.RewardsCurrencyCfg, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardsCurrencyCfg), nil
	}
}

func (r rewardsCurrencyCfgDo) Find() ([]*model.RewardsCurrencyCfg, error) {
	result, err := r.DO.Find()
	return result.([]*model.RewardsCurrencyCfg), err
}

func (r rewardsCurrencyCfgDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RewardsCurrencyCfg, err error) {
	buf := make([]*model.RewardsCurrencyCfg, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r rewardsCurrencyCfgDo) FindInBatches(result *[]*model.RewardsCurrencyCfg, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r rewardsCurrencyCfgDo) Attrs(attrs ...field.AssignExpr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r rewardsCurrencyCfgDo) Assign(attrs ...field.AssignExpr) IRewardsCurrencyCfgDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r rewardsCurrencyCfgDo) Joins(fields ...field.RelationField) IRewardsCurrencyCfgDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r rewardsCurrencyCfgDo) Preload(fields ...field.RelationField) IRewardsCurrencyCfgDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r rewardsCurrencyCfgDo) FirstOrInit() (*model.RewardsCurrencyCfg, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardsCurrencyCfg), nil
	}
}

func (r rewardsCurrencyCfgDo) FirstOrCreate() (*model.RewardsCurrencyCfg, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RewardsCurrencyCfg), nil
	}
}

func (r rewardsCurrencyCfgDo) FindByPage(offset int, limit int) (result []*model.RewardsCurrencyCfg, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r rewardsCurrencyCfgDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r rewardsCurrencyCfgDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r rewardsCurrencyCfgDo) Delete(models ...*model.RewardsCurrencyCfg) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *rewardsCurrencyCfgDo) withDO(do gen.Dao) *rewardsCurrencyCfgDo {
	r.DO = *do.(*gen.DO)
	return r
}
