// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newTClubIncome(db *gorm.DB, opts ...gen.DOOption) tClubIncome {
	_tClubIncome := tClubIncome{}

	_tClubIncome.tClubIncomeDo.UseDB(db, opts...)
	_tClubIncome.tClubIncomeDo.UseModel(&model.TClubIncome{})

	tableName := _tClubIncome.tClubIncomeDo.TableName()
	_tClubIncome.ALL = field.NewAsterisk(tableName)
	_tClubIncome.UID = field.NewInt32(tableName, "uid")
	_tClubIncome.Data = field.NewString(tableName, "data")

	_tClubIncome.fillFieldMap()

	return _tClubIncome
}

type tClubIncome struct {
	tClubIncomeDo

	ALL  field.Asterisk
	UID  field.Int32  // 俱乐部创建者id
	Data field.String // 俱乐部收益

	fieldMap map[string]field.Expr
}

func (t tClubIncome) Table(newTableName string) *tClubIncome {
	t.tClubIncomeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tClubIncome) As(alias string) *tClubIncome {
	t.tClubIncomeDo.DO = *(t.tClubIncomeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tClubIncome) updateTableName(table string) *tClubIncome {
	t.ALL = field.NewAsterisk(table)
	t.UID = field.NewInt32(table, "uid")
	t.Data = field.NewString(table, "data")

	t.fillFieldMap()

	return t
}

func (t *tClubIncome) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tClubIncome) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["uid"] = t.UID
	t.fieldMap["data"] = t.Data
}

func (t tClubIncome) clone(db *gorm.DB) tClubIncome {
	t.tClubIncomeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tClubIncome) replaceDB(db *gorm.DB) tClubIncome {
	t.tClubIncomeDo.ReplaceDB(db)
	return t
}

type tClubIncomeDo struct{ gen.DO }

type ITClubIncomeDo interface {
	gen.SubQuery
	Debug() ITClubIncomeDo
	WithContext(ctx context.Context) ITClubIncomeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITClubIncomeDo
	WriteDB() ITClubIncomeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITClubIncomeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITClubIncomeDo
	Not(conds ...gen.Condition) ITClubIncomeDo
	Or(conds ...gen.Condition) ITClubIncomeDo
	Select(conds ...field.Expr) ITClubIncomeDo
	Where(conds ...gen.Condition) ITClubIncomeDo
	Order(conds ...field.Expr) ITClubIncomeDo
	Distinct(cols ...field.Expr) ITClubIncomeDo
	Omit(cols ...field.Expr) ITClubIncomeDo
	Join(table schema.Tabler, on ...field.Expr) ITClubIncomeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITClubIncomeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITClubIncomeDo
	Group(cols ...field.Expr) ITClubIncomeDo
	Having(conds ...gen.Condition) ITClubIncomeDo
	Limit(limit int) ITClubIncomeDo
	Offset(offset int) ITClubIncomeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITClubIncomeDo
	Unscoped() ITClubIncomeDo
	Create(values ...*model.TClubIncome) error
	CreateInBatches(values []*model.TClubIncome, batchSize int) error
	Save(values ...*model.TClubIncome) error
	First() (*model.TClubIncome, error)
	Take() (*model.TClubIncome, error)
	Last() (*model.TClubIncome, error)
	Find() ([]*model.TClubIncome, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TClubIncome, err error)
	FindInBatches(result *[]*model.TClubIncome, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TClubIncome) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITClubIncomeDo
	Assign(attrs ...field.AssignExpr) ITClubIncomeDo
	Joins(fields ...field.RelationField) ITClubIncomeDo
	Preload(fields ...field.RelationField) ITClubIncomeDo
	FirstOrInit() (*model.TClubIncome, error)
	FirstOrCreate() (*model.TClubIncome, error)
	FindByPage(offset int, limit int) (result []*model.TClubIncome, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITClubIncomeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tClubIncomeDo) Debug() ITClubIncomeDo {
	return t.withDO(t.DO.Debug())
}

func (t tClubIncomeDo) WithContext(ctx context.Context) ITClubIncomeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tClubIncomeDo) ReadDB() ITClubIncomeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tClubIncomeDo) WriteDB() ITClubIncomeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tClubIncomeDo) Session(config *gorm.Session) ITClubIncomeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tClubIncomeDo) Clauses(conds ...clause.Expression) ITClubIncomeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tClubIncomeDo) Returning(value interface{}, columns ...string) ITClubIncomeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tClubIncomeDo) Not(conds ...gen.Condition) ITClubIncomeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tClubIncomeDo) Or(conds ...gen.Condition) ITClubIncomeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tClubIncomeDo) Select(conds ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tClubIncomeDo) Where(conds ...gen.Condition) ITClubIncomeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tClubIncomeDo) Order(conds ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tClubIncomeDo) Distinct(cols ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tClubIncomeDo) Omit(cols ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tClubIncomeDo) Join(table schema.Tabler, on ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tClubIncomeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tClubIncomeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tClubIncomeDo) Group(cols ...field.Expr) ITClubIncomeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tClubIncomeDo) Having(conds ...gen.Condition) ITClubIncomeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tClubIncomeDo) Limit(limit int) ITClubIncomeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tClubIncomeDo) Offset(offset int) ITClubIncomeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tClubIncomeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITClubIncomeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tClubIncomeDo) Unscoped() ITClubIncomeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tClubIncomeDo) Create(values ...*model.TClubIncome) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tClubIncomeDo) CreateInBatches(values []*model.TClubIncome, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tClubIncomeDo) Save(values ...*model.TClubIncome) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tClubIncomeDo) First() (*model.TClubIncome, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TClubIncome), nil
	}
}

func (t tClubIncomeDo) Take() (*model.TClubIncome, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TClubIncome), nil
	}
}

func (t tClubIncomeDo) Last() (*model.TClubIncome, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TClubIncome), nil
	}
}

func (t tClubIncomeDo) Find() ([]*model.TClubIncome, error) {
	result, err := t.DO.Find()
	return result.([]*model.TClubIncome), err
}

func (t tClubIncomeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TClubIncome, err error) {
	buf := make([]*model.TClubIncome, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tClubIncomeDo) FindInBatches(result *[]*model.TClubIncome, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tClubIncomeDo) Attrs(attrs ...field.AssignExpr) ITClubIncomeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tClubIncomeDo) Assign(attrs ...field.AssignExpr) ITClubIncomeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tClubIncomeDo) Joins(fields ...field.RelationField) ITClubIncomeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tClubIncomeDo) Preload(fields ...field.RelationField) ITClubIncomeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tClubIncomeDo) FirstOrInit() (*model.TClubIncome, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TClubIncome), nil
	}
}

func (t tClubIncomeDo) FirstOrCreate() (*model.TClubIncome, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TClubIncome), nil
	}
}

func (t tClubIncomeDo) FindByPage(offset int, limit int) (result []*model.TClubIncome, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tClubIncomeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tClubIncomeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tClubIncomeDo) Delete(models ...*model.TClubIncome) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tClubIncomeDo) withDO(do gen.Dao) *tClubIncomeDo {
	t.DO = *do.(*gen.DO)
	return t
}
