// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newTPlatformIncome(db *gorm.DB, opts ...gen.DOOption) tPlatformIncome {
	_tPlatformIncome := tPlatformIncome{}

	_tPlatformIncome.tPlatformIncomeDo.UseDB(db, opts...)
	_tPlatformIncome.tPlatformIncomeDo.UseModel(&model.TPlatformIncome{})

	tableName := _tPlatformIncome.tPlatformIncomeDo.TableName()
	_tPlatformIncome.ALL = field.NewAsterisk(tableName)
	_tPlatformIncome.UID = field.NewInt32(tableName, "uid")
	_tPlatformIncome.Data = field.NewString(tableName, "data")

	_tPlatformIncome.fillFieldMap()

	return _tPlatformIncome
}

type tPlatformIncome struct {
	tPlatformIncomeDo

	ALL  field.Asterisk
	UID  field.Int32
	Data field.String // 平台收益

	fieldMap map[string]field.Expr
}

func (t tPlatformIncome) Table(newTableName string) *tPlatformIncome {
	t.tPlatformIncomeDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tPlatformIncome) As(alias string) *tPlatformIncome {
	t.tPlatformIncomeDo.DO = *(t.tPlatformIncomeDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tPlatformIncome) updateTableName(table string) *tPlatformIncome {
	t.ALL = field.NewAsterisk(table)
	t.UID = field.NewInt32(table, "uid")
	t.Data = field.NewString(table, "data")

	t.fillFieldMap()

	return t
}

func (t *tPlatformIncome) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tPlatformIncome) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 2)
	t.fieldMap["uid"] = t.UID
	t.fieldMap["data"] = t.Data
}

func (t tPlatformIncome) clone(db *gorm.DB) tPlatformIncome {
	t.tPlatformIncomeDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tPlatformIncome) replaceDB(db *gorm.DB) tPlatformIncome {
	t.tPlatformIncomeDo.ReplaceDB(db)
	return t
}

type tPlatformIncomeDo struct{ gen.DO }

type ITPlatformIncomeDo interface {
	gen.SubQuery
	Debug() ITPlatformIncomeDo
	WithContext(ctx context.Context) ITPlatformIncomeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITPlatformIncomeDo
	WriteDB() ITPlatformIncomeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITPlatformIncomeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITPlatformIncomeDo
	Not(conds ...gen.Condition) ITPlatformIncomeDo
	Or(conds ...gen.Condition) ITPlatformIncomeDo
	Select(conds ...field.Expr) ITPlatformIncomeDo
	Where(conds ...gen.Condition) ITPlatformIncomeDo
	Order(conds ...field.Expr) ITPlatformIncomeDo
	Distinct(cols ...field.Expr) ITPlatformIncomeDo
	Omit(cols ...field.Expr) ITPlatformIncomeDo
	Join(table schema.Tabler, on ...field.Expr) ITPlatformIncomeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITPlatformIncomeDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITPlatformIncomeDo
	Group(cols ...field.Expr) ITPlatformIncomeDo
	Having(conds ...gen.Condition) ITPlatformIncomeDo
	Limit(limit int) ITPlatformIncomeDo
	Offset(offset int) ITPlatformIncomeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITPlatformIncomeDo
	Unscoped() ITPlatformIncomeDo
	Create(values ...*model.TPlatformIncome) error
	CreateInBatches(values []*model.TPlatformIncome, batchSize int) error
	Save(values ...*model.TPlatformIncome) error
	First() (*model.TPlatformIncome, error)
	Take() (*model.TPlatformIncome, error)
	Last() (*model.TPlatformIncome, error)
	Find() ([]*model.TPlatformIncome, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TPlatformIncome, err error)
	FindInBatches(result *[]*model.TPlatformIncome, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TPlatformIncome) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITPlatformIncomeDo
	Assign(attrs ...field.AssignExpr) ITPlatformIncomeDo
	Joins(fields ...field.RelationField) ITPlatformIncomeDo
	Preload(fields ...field.RelationField) ITPlatformIncomeDo
	FirstOrInit() (*model.TPlatformIncome, error)
	FirstOrCreate() (*model.TPlatformIncome, error)
	FindByPage(offset int, limit int) (result []*model.TPlatformIncome, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITPlatformIncomeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tPlatformIncomeDo) Debug() ITPlatformIncomeDo {
	return t.withDO(t.DO.Debug())
}

func (t tPlatformIncomeDo) WithContext(ctx context.Context) ITPlatformIncomeDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tPlatformIncomeDo) ReadDB() ITPlatformIncomeDo {
	return t.Clauses(dbresolver.Read)
}

func (t tPlatformIncomeDo) WriteDB() ITPlatformIncomeDo {
	return t.Clauses(dbresolver.Write)
}

func (t tPlatformIncomeDo) Session(config *gorm.Session) ITPlatformIncomeDo {
	return t.withDO(t.DO.Session(config))
}

func (t tPlatformIncomeDo) Clauses(conds ...clause.Expression) ITPlatformIncomeDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tPlatformIncomeDo) Returning(value interface{}, columns ...string) ITPlatformIncomeDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tPlatformIncomeDo) Not(conds ...gen.Condition) ITPlatformIncomeDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tPlatformIncomeDo) Or(conds ...gen.Condition) ITPlatformIncomeDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tPlatformIncomeDo) Select(conds ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tPlatformIncomeDo) Where(conds ...gen.Condition) ITPlatformIncomeDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tPlatformIncomeDo) Order(conds ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tPlatformIncomeDo) Distinct(cols ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tPlatformIncomeDo) Omit(cols ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tPlatformIncomeDo) Join(table schema.Tabler, on ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tPlatformIncomeDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tPlatformIncomeDo) RightJoin(table schema.Tabler, on ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tPlatformIncomeDo) Group(cols ...field.Expr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tPlatformIncomeDo) Having(conds ...gen.Condition) ITPlatformIncomeDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tPlatformIncomeDo) Limit(limit int) ITPlatformIncomeDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tPlatformIncomeDo) Offset(offset int) ITPlatformIncomeDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tPlatformIncomeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITPlatformIncomeDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tPlatformIncomeDo) Unscoped() ITPlatformIncomeDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tPlatformIncomeDo) Create(values ...*model.TPlatformIncome) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tPlatformIncomeDo) CreateInBatches(values []*model.TPlatformIncome, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tPlatformIncomeDo) Save(values ...*model.TPlatformIncome) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tPlatformIncomeDo) First() (*model.TPlatformIncome, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPlatformIncome), nil
	}
}

func (t tPlatformIncomeDo) Take() (*model.TPlatformIncome, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPlatformIncome), nil
	}
}

func (t tPlatformIncomeDo) Last() (*model.TPlatformIncome, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPlatformIncome), nil
	}
}

func (t tPlatformIncomeDo) Find() ([]*model.TPlatformIncome, error) {
	result, err := t.DO.Find()
	return result.([]*model.TPlatformIncome), err
}

func (t tPlatformIncomeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TPlatformIncome, err error) {
	buf := make([]*model.TPlatformIncome, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tPlatformIncomeDo) FindInBatches(result *[]*model.TPlatformIncome, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tPlatformIncomeDo) Attrs(attrs ...field.AssignExpr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tPlatformIncomeDo) Assign(attrs ...field.AssignExpr) ITPlatformIncomeDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tPlatformIncomeDo) Joins(fields ...field.RelationField) ITPlatformIncomeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tPlatformIncomeDo) Preload(fields ...field.RelationField) ITPlatformIncomeDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tPlatformIncomeDo) FirstOrInit() (*model.TPlatformIncome, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPlatformIncome), nil
	}
}

func (t tPlatformIncomeDo) FirstOrCreate() (*model.TPlatformIncome, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TPlatformIncome), nil
	}
}

func (t tPlatformIncomeDo) FindByPage(offset int, limit int) (result []*model.TPlatformIncome, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tPlatformIncomeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tPlatformIncomeDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tPlatformIncomeDo) Delete(models ...*model.TPlatformIncome) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tPlatformIncomeDo) withDO(do gen.Dao) *tPlatformIncomeDo {
	t.DO = *do.(*gen.DO)
	return t
}
