// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newTSquidUserTableGold(db *gorm.DB, opts ...gen.DOOption) tSquidUserTableGold {
	_tSquidUserTableGold := tSquidUserTableGold{}

	_tSquidUserTableGold.tSquidUserTableGoldDo.UseDB(db, opts...)
	_tSquidUserTableGold.tSquidUserTableGoldDo.UseModel(&model.TSquidUserTableGold{})

	tableName := _tSquidUserTableGold.tSquidUserTableGoldDo.TableName()
	_tSquidUserTableGold.ALL = field.NewAsterisk(tableName)
	_tSquidUserTableGold.UserID = field.NewUint32(tableName, "user_id")
	_tSquidUserTableGold.LeftGold = field.NewUint32(tableName, "left_gold")
	_tSquidUserTableGold.RoomID = field.NewUint32(tableName, "room_id")
	_tSquidUserTableGold.ChangeTime = field.NewInt32(tableName, "change_time")
	_tSquidUserTableGold.Buyout = field.NewUint32(tableName, "buyout")
	_tSquidUserTableGold.EscrowBuyin = field.NewUint32(tableName, "escrow_buyin")
	_tSquidUserTableGold.BountyPayout = field.NewUint32(tableName, "bounty_payout")
	_tSquidUserTableGold.CurrencyType = field.NewBool(tableName, "currency_type")

	_tSquidUserTableGold.fillFieldMap()

	return _tSquidUserTableGold
}

// tSquidUserTableGold 存储玩家买入金币的剩余值
type tSquidUserTableGold struct {
	tSquidUserTableGoldDo

	ALL          field.Asterisk
	UserID       field.Uint32 // 玩家ID
	LeftGold     field.Uint32 // 玩家当前剩余买入金币
	RoomID       field.Uint32 // 当前玩家所在房间id
	ChangeTime   field.Int32
	Buyout       field.Uint32
	EscrowBuyin  field.Uint32
	BountyPayout field.Uint32
	CurrencyType field.Bool

	fieldMap map[string]field.Expr
}

func (t tSquidUserTableGold) Table(newTableName string) *tSquidUserTableGold {
	t.tSquidUserTableGoldDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tSquidUserTableGold) As(alias string) *tSquidUserTableGold {
	t.tSquidUserTableGoldDo.DO = *(t.tSquidUserTableGoldDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tSquidUserTableGold) updateTableName(table string) *tSquidUserTableGold {
	t.ALL = field.NewAsterisk(table)
	t.UserID = field.NewUint32(table, "user_id")
	t.LeftGold = field.NewUint32(table, "left_gold")
	t.RoomID = field.NewUint32(table, "room_id")
	t.ChangeTime = field.NewInt32(table, "change_time")
	t.Buyout = field.NewUint32(table, "buyout")
	t.EscrowBuyin = field.NewUint32(table, "escrow_buyin")
	t.BountyPayout = field.NewUint32(table, "bounty_payout")
	t.CurrencyType = field.NewBool(table, "currency_type")

	t.fillFieldMap()

	return t
}

func (t *tSquidUserTableGold) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tSquidUserTableGold) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 8)
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["left_gold"] = t.LeftGold
	t.fieldMap["room_id"] = t.RoomID
	t.fieldMap["change_time"] = t.ChangeTime
	t.fieldMap["buyout"] = t.Buyout
	t.fieldMap["escrow_buyin"] = t.EscrowBuyin
	t.fieldMap["bounty_payout"] = t.BountyPayout
	t.fieldMap["currency_type"] = t.CurrencyType
}

func (t tSquidUserTableGold) clone(db *gorm.DB) tSquidUserTableGold {
	t.tSquidUserTableGoldDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tSquidUserTableGold) replaceDB(db *gorm.DB) tSquidUserTableGold {
	t.tSquidUserTableGoldDo.ReplaceDB(db)
	return t
}

type tSquidUserTableGoldDo struct{ gen.DO }

type ITSquidUserTableGoldDo interface {
	gen.SubQuery
	Debug() ITSquidUserTableGoldDo
	WithContext(ctx context.Context) ITSquidUserTableGoldDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITSquidUserTableGoldDo
	WriteDB() ITSquidUserTableGoldDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITSquidUserTableGoldDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITSquidUserTableGoldDo
	Not(conds ...gen.Condition) ITSquidUserTableGoldDo
	Or(conds ...gen.Condition) ITSquidUserTableGoldDo
	Select(conds ...field.Expr) ITSquidUserTableGoldDo
	Where(conds ...gen.Condition) ITSquidUserTableGoldDo
	Order(conds ...field.Expr) ITSquidUserTableGoldDo
	Distinct(cols ...field.Expr) ITSquidUserTableGoldDo
	Omit(cols ...field.Expr) ITSquidUserTableGoldDo
	Join(table schema.Tabler, on ...field.Expr) ITSquidUserTableGoldDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITSquidUserTableGoldDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITSquidUserTableGoldDo
	Group(cols ...field.Expr) ITSquidUserTableGoldDo
	Having(conds ...gen.Condition) ITSquidUserTableGoldDo
	Limit(limit int) ITSquidUserTableGoldDo
	Offset(offset int) ITSquidUserTableGoldDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITSquidUserTableGoldDo
	Unscoped() ITSquidUserTableGoldDo
	Create(values ...*model.TSquidUserTableGold) error
	CreateInBatches(values []*model.TSquidUserTableGold, batchSize int) error
	Save(values ...*model.TSquidUserTableGold) error
	First() (*model.TSquidUserTableGold, error)
	Take() (*model.TSquidUserTableGold, error)
	Last() (*model.TSquidUserTableGold, error)
	Find() ([]*model.TSquidUserTableGold, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSquidUserTableGold, err error)
	FindInBatches(result *[]*model.TSquidUserTableGold, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TSquidUserTableGold) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITSquidUserTableGoldDo
	Assign(attrs ...field.AssignExpr) ITSquidUserTableGoldDo
	Joins(fields ...field.RelationField) ITSquidUserTableGoldDo
	Preload(fields ...field.RelationField) ITSquidUserTableGoldDo
	FirstOrInit() (*model.TSquidUserTableGold, error)
	FirstOrCreate() (*model.TSquidUserTableGold, error)
	FindByPage(offset int, limit int) (result []*model.TSquidUserTableGold, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITSquidUserTableGoldDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tSquidUserTableGoldDo) Debug() ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Debug())
}

func (t tSquidUserTableGoldDo) WithContext(ctx context.Context) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tSquidUserTableGoldDo) ReadDB() ITSquidUserTableGoldDo {
	return t.Clauses(dbresolver.Read)
}

func (t tSquidUserTableGoldDo) WriteDB() ITSquidUserTableGoldDo {
	return t.Clauses(dbresolver.Write)
}

func (t tSquidUserTableGoldDo) Session(config *gorm.Session) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Session(config))
}

func (t tSquidUserTableGoldDo) Clauses(conds ...clause.Expression) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tSquidUserTableGoldDo) Returning(value interface{}, columns ...string) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tSquidUserTableGoldDo) Not(conds ...gen.Condition) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tSquidUserTableGoldDo) Or(conds ...gen.Condition) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tSquidUserTableGoldDo) Select(conds ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tSquidUserTableGoldDo) Where(conds ...gen.Condition) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tSquidUserTableGoldDo) Order(conds ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tSquidUserTableGoldDo) Distinct(cols ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tSquidUserTableGoldDo) Omit(cols ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tSquidUserTableGoldDo) Join(table schema.Tabler, on ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tSquidUserTableGoldDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tSquidUserTableGoldDo) RightJoin(table schema.Tabler, on ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tSquidUserTableGoldDo) Group(cols ...field.Expr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tSquidUserTableGoldDo) Having(conds ...gen.Condition) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tSquidUserTableGoldDo) Limit(limit int) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tSquidUserTableGoldDo) Offset(offset int) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tSquidUserTableGoldDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tSquidUserTableGoldDo) Unscoped() ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tSquidUserTableGoldDo) Create(values ...*model.TSquidUserTableGold) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tSquidUserTableGoldDo) CreateInBatches(values []*model.TSquidUserTableGold, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tSquidUserTableGoldDo) Save(values ...*model.TSquidUserTableGold) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tSquidUserTableGoldDo) First() (*model.TSquidUserTableGold, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSquidUserTableGold), nil
	}
}

func (t tSquidUserTableGoldDo) Take() (*model.TSquidUserTableGold, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSquidUserTableGold), nil
	}
}

func (t tSquidUserTableGoldDo) Last() (*model.TSquidUserTableGold, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSquidUserTableGold), nil
	}
}

func (t tSquidUserTableGoldDo) Find() ([]*model.TSquidUserTableGold, error) {
	result, err := t.DO.Find()
	return result.([]*model.TSquidUserTableGold), err
}

func (t tSquidUserTableGoldDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TSquidUserTableGold, err error) {
	buf := make([]*model.TSquidUserTableGold, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tSquidUserTableGoldDo) FindInBatches(result *[]*model.TSquidUserTableGold, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tSquidUserTableGoldDo) Attrs(attrs ...field.AssignExpr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tSquidUserTableGoldDo) Assign(attrs ...field.AssignExpr) ITSquidUserTableGoldDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tSquidUserTableGoldDo) Joins(fields ...field.RelationField) ITSquidUserTableGoldDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tSquidUserTableGoldDo) Preload(fields ...field.RelationField) ITSquidUserTableGoldDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tSquidUserTableGoldDo) FirstOrInit() (*model.TSquidUserTableGold, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSquidUserTableGold), nil
	}
}

func (t tSquidUserTableGoldDo) FirstOrCreate() (*model.TSquidUserTableGold, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TSquidUserTableGold), nil
	}
}

func (t tSquidUserTableGoldDo) FindByPage(offset int, limit int) (result []*model.TSquidUserTableGold, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tSquidUserTableGoldDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tSquidUserTableGoldDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tSquidUserTableGoldDo) Delete(models ...*model.TSquidUserTableGold) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tSquidUserTableGoldDo) withDO(do gen.Dao) *tSquidUserTableGoldDo {
	t.DO = *do.(*gen.DO)
	return t
}
