// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newTUserTableGold(db *gorm.DB, opts ...gen.DOOption) tUserTableGold {
	_tUserTableGold := tUserTableGold{}

	_tUserTableGold.tUserTableGoldDo.UseDB(db, opts...)
	_tUserTableGold.tUserTableGoldDo.UseModel(&model.TUserTableGold{})

	tableName := _tUserTableGold.tUserTableGoldDo.TableName()
	_tUserTableGold.ALL = field.NewAsterisk(tableName)
	_tUserTableGold.UserID = field.NewUint32(tableName, "user_id")
	_tUserTableGold.LeftGold = field.NewUint32(tableName, "left_gold")
	_tUserTableGold.RoomID = field.NewUint32(tableName, "room_id")
	_tUserTableGold.ChangeTime = field.NewInt32(tableName, "change_time")
	_tUserTableGold.Buyout = field.NewUint32(tableName, "buyout")
	_tUserTableGold.CurrencyType = field.NewBool(tableName, "currency_type")

	_tUserTableGold.fillFieldMap()

	return _tUserTableGold
}

// tUserTableGold 存储玩家买入金币的剩余值
type tUserTableGold struct {
	tUserTableGoldDo

	ALL          field.Asterisk
	UserID       field.Uint32 // 玩家ID
	LeftGold     field.Uint32 // 玩家当前剩余买入金币
	RoomID       field.Uint32 // 当前玩家所在房间id
	ChangeTime   field.Int32
	Buyout       field.Uint32
	CurrencyType field.Bool

	fieldMap map[string]field.Expr
}

func (t tUserTableGold) Table(newTableName string) *tUserTableGold {
	t.tUserTableGoldDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tUserTableGold) As(alias string) *tUserTableGold {
	t.tUserTableGoldDo.DO = *(t.tUserTableGoldDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tUserTableGold) updateTableName(table string) *tUserTableGold {
	t.ALL = field.NewAsterisk(table)
	t.UserID = field.NewUint32(table, "user_id")
	t.LeftGold = field.NewUint32(table, "left_gold")
	t.RoomID = field.NewUint32(table, "room_id")
	t.ChangeTime = field.NewInt32(table, "change_time")
	t.Buyout = field.NewUint32(table, "buyout")
	t.CurrencyType = field.NewBool(table, "currency_type")

	t.fillFieldMap()

	return t
}

func (t *tUserTableGold) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tUserTableGold) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 6)
	t.fieldMap["user_id"] = t.UserID
	t.fieldMap["left_gold"] = t.LeftGold
	t.fieldMap["room_id"] = t.RoomID
	t.fieldMap["change_time"] = t.ChangeTime
	t.fieldMap["buyout"] = t.Buyout
	t.fieldMap["currency_type"] = t.CurrencyType
}

func (t tUserTableGold) clone(db *gorm.DB) tUserTableGold {
	t.tUserTableGoldDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tUserTableGold) replaceDB(db *gorm.DB) tUserTableGold {
	t.tUserTableGoldDo.ReplaceDB(db)
	return t
}

type tUserTableGoldDo struct{ gen.DO }

type ITUserTableGoldDo interface {
	gen.SubQuery
	Debug() ITUserTableGoldDo
	WithContext(ctx context.Context) ITUserTableGoldDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITUserTableGoldDo
	WriteDB() ITUserTableGoldDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITUserTableGoldDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITUserTableGoldDo
	Not(conds ...gen.Condition) ITUserTableGoldDo
	Or(conds ...gen.Condition) ITUserTableGoldDo
	Select(conds ...field.Expr) ITUserTableGoldDo
	Where(conds ...gen.Condition) ITUserTableGoldDo
	Order(conds ...field.Expr) ITUserTableGoldDo
	Distinct(cols ...field.Expr) ITUserTableGoldDo
	Omit(cols ...field.Expr) ITUserTableGoldDo
	Join(table schema.Tabler, on ...field.Expr) ITUserTableGoldDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITUserTableGoldDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITUserTableGoldDo
	Group(cols ...field.Expr) ITUserTableGoldDo
	Having(conds ...gen.Condition) ITUserTableGoldDo
	Limit(limit int) ITUserTableGoldDo
	Offset(offset int) ITUserTableGoldDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITUserTableGoldDo
	Unscoped() ITUserTableGoldDo
	Create(values ...*model.TUserTableGold) error
	CreateInBatches(values []*model.TUserTableGold, batchSize int) error
	Save(values ...*model.TUserTableGold) error
	First() (*model.TUserTableGold, error)
	Take() (*model.TUserTableGold, error)
	Last() (*model.TUserTableGold, error)
	Find() ([]*model.TUserTableGold, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUserTableGold, err error)
	FindInBatches(result *[]*model.TUserTableGold, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TUserTableGold) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITUserTableGoldDo
	Assign(attrs ...field.AssignExpr) ITUserTableGoldDo
	Joins(fields ...field.RelationField) ITUserTableGoldDo
	Preload(fields ...field.RelationField) ITUserTableGoldDo
	FirstOrInit() (*model.TUserTableGold, error)
	FirstOrCreate() (*model.TUserTableGold, error)
	FindByPage(offset int, limit int) (result []*model.TUserTableGold, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITUserTableGoldDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tUserTableGoldDo) Debug() ITUserTableGoldDo {
	return t.withDO(t.DO.Debug())
}

func (t tUserTableGoldDo) WithContext(ctx context.Context) ITUserTableGoldDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tUserTableGoldDo) ReadDB() ITUserTableGoldDo {
	return t.Clauses(dbresolver.Read)
}

func (t tUserTableGoldDo) WriteDB() ITUserTableGoldDo {
	return t.Clauses(dbresolver.Write)
}

func (t tUserTableGoldDo) Session(config *gorm.Session) ITUserTableGoldDo {
	return t.withDO(t.DO.Session(config))
}

func (t tUserTableGoldDo) Clauses(conds ...clause.Expression) ITUserTableGoldDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tUserTableGoldDo) Returning(value interface{}, columns ...string) ITUserTableGoldDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tUserTableGoldDo) Not(conds ...gen.Condition) ITUserTableGoldDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tUserTableGoldDo) Or(conds ...gen.Condition) ITUserTableGoldDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tUserTableGoldDo) Select(conds ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tUserTableGoldDo) Where(conds ...gen.Condition) ITUserTableGoldDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tUserTableGoldDo) Order(conds ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tUserTableGoldDo) Distinct(cols ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tUserTableGoldDo) Omit(cols ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tUserTableGoldDo) Join(table schema.Tabler, on ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tUserTableGoldDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tUserTableGoldDo) RightJoin(table schema.Tabler, on ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tUserTableGoldDo) Group(cols ...field.Expr) ITUserTableGoldDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tUserTableGoldDo) Having(conds ...gen.Condition) ITUserTableGoldDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tUserTableGoldDo) Limit(limit int) ITUserTableGoldDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tUserTableGoldDo) Offset(offset int) ITUserTableGoldDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tUserTableGoldDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITUserTableGoldDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tUserTableGoldDo) Unscoped() ITUserTableGoldDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tUserTableGoldDo) Create(values ...*model.TUserTableGold) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tUserTableGoldDo) CreateInBatches(values []*model.TUserTableGold, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tUserTableGoldDo) Save(values ...*model.TUserTableGold) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tUserTableGoldDo) First() (*model.TUserTableGold, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserTableGold), nil
	}
}

func (t tUserTableGoldDo) Take() (*model.TUserTableGold, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserTableGold), nil
	}
}

func (t tUserTableGoldDo) Last() (*model.TUserTableGold, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserTableGold), nil
	}
}

func (t tUserTableGoldDo) Find() ([]*model.TUserTableGold, error) {
	result, err := t.DO.Find()
	return result.([]*model.TUserTableGold), err
}

func (t tUserTableGoldDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TUserTableGold, err error) {
	buf := make([]*model.TUserTableGold, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tUserTableGoldDo) FindInBatches(result *[]*model.TUserTableGold, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tUserTableGoldDo) Attrs(attrs ...field.AssignExpr) ITUserTableGoldDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tUserTableGoldDo) Assign(attrs ...field.AssignExpr) ITUserTableGoldDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tUserTableGoldDo) Joins(fields ...field.RelationField) ITUserTableGoldDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tUserTableGoldDo) Preload(fields ...field.RelationField) ITUserTableGoldDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tUserTableGoldDo) FirstOrInit() (*model.TUserTableGold, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserTableGold), nil
	}
}

func (t tUserTableGoldDo) FirstOrCreate() (*model.TUserTableGold, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TUserTableGold), nil
	}
}

func (t tUserTableGoldDo) FindByPage(offset int, limit int) (result []*model.TUserTableGold, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tUserTableGoldDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tUserTableGoldDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tUserTableGoldDo) Delete(models ...*model.TUserTableGold) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tUserTableGoldDo) withDO(do gen.Dao) *tUserTableGoldDo {
	t.DO = *do.(*gen.DO)
	return t
}
