// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/coin/model"
)

func newWptPayCustomer(db *gorm.DB, opts ...gen.DOOption) wptPayCustomer {
	_wptPayCustomer := wptPayCustomer{}

	_wptPayCustomer.wptPayCustomerDo.UseDB(db, opts...)
	_wptPayCustomer.wptPayCustomerDo.UseModel(&model.WptPayCustomer{})

	tableName := _wptPayCustomer.wptPayCustomerDo.TableName()
	_wptPayCustomer.ALL = field.NewAsterisk(tableName)
	_wptPayCustomer.MainID = field.NewUint32(tableName, "main_id")
	_wptPayCustomer.CustomerID = field.NewString(tableName, "customer_id")
	_wptPayCustomer.TotalAmount = field.NewInt64(tableName, "total_amount")
	_wptPayCustomer.UpdateTime = field.NewInt64(tableName, "update_time")
	_wptPayCustomer.CreateTime = field.NewInt64(tableName, "create_time")
	_wptPayCustomer.UserType = field.NewString(tableName, "user_type")
	_wptPayCustomer.TotalRedeemAmount = field.NewInt64(tableName, "total_redeem_amount")

	_wptPayCustomer.fillFieldMap()

	return _wptPayCustomer
}

// wptPayCustomer 支付平台客户
type wptPayCustomer struct {
	wptPayCustomerDo

	ALL               field.Asterisk
	MainID            field.Uint32 // 用户ID
	CustomerID        field.String // 支付平台客户ID
	TotalAmount       field.Int64  // 累计购买金额
	UpdateTime        field.Int64  // 更新时间
	CreateTime        field.Int64  // 创建时间
	UserType          field.String // UserType
	TotalRedeemAmount field.Int64

	fieldMap map[string]field.Expr
}

func (w wptPayCustomer) Table(newTableName string) *wptPayCustomer {
	w.wptPayCustomerDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w wptPayCustomer) As(alias string) *wptPayCustomer {
	w.wptPayCustomerDo.DO = *(w.wptPayCustomerDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *wptPayCustomer) updateTableName(table string) *wptPayCustomer {
	w.ALL = field.NewAsterisk(table)
	w.MainID = field.NewUint32(table, "main_id")
	w.CustomerID = field.NewString(table, "customer_id")
	w.TotalAmount = field.NewInt64(table, "total_amount")
	w.UpdateTime = field.NewInt64(table, "update_time")
	w.CreateTime = field.NewInt64(table, "create_time")
	w.UserType = field.NewString(table, "user_type")
	w.TotalRedeemAmount = field.NewInt64(table, "total_redeem_amount")

	w.fillFieldMap()

	return w
}

func (w *wptPayCustomer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *wptPayCustomer) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 7)
	w.fieldMap["main_id"] = w.MainID
	w.fieldMap["customer_id"] = w.CustomerID
	w.fieldMap["total_amount"] = w.TotalAmount
	w.fieldMap["update_time"] = w.UpdateTime
	w.fieldMap["create_time"] = w.CreateTime
	w.fieldMap["user_type"] = w.UserType
	w.fieldMap["total_redeem_amount"] = w.TotalRedeemAmount
}

func (w wptPayCustomer) clone(db *gorm.DB) wptPayCustomer {
	w.wptPayCustomerDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w wptPayCustomer) replaceDB(db *gorm.DB) wptPayCustomer {
	w.wptPayCustomerDo.ReplaceDB(db)
	return w
}

type wptPayCustomerDo struct{ gen.DO }

type IWptPayCustomerDo interface {
	gen.SubQuery
	Debug() IWptPayCustomerDo
	WithContext(ctx context.Context) IWptPayCustomerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWptPayCustomerDo
	WriteDB() IWptPayCustomerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWptPayCustomerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWptPayCustomerDo
	Not(conds ...gen.Condition) IWptPayCustomerDo
	Or(conds ...gen.Condition) IWptPayCustomerDo
	Select(conds ...field.Expr) IWptPayCustomerDo
	Where(conds ...gen.Condition) IWptPayCustomerDo
	Order(conds ...field.Expr) IWptPayCustomerDo
	Distinct(cols ...field.Expr) IWptPayCustomerDo
	Omit(cols ...field.Expr) IWptPayCustomerDo
	Join(table schema.Tabler, on ...field.Expr) IWptPayCustomerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWptPayCustomerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWptPayCustomerDo
	Group(cols ...field.Expr) IWptPayCustomerDo
	Having(conds ...gen.Condition) IWptPayCustomerDo
	Limit(limit int) IWptPayCustomerDo
	Offset(offset int) IWptPayCustomerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWptPayCustomerDo
	Unscoped() IWptPayCustomerDo
	Create(values ...*model.WptPayCustomer) error
	CreateInBatches(values []*model.WptPayCustomer, batchSize int) error
	Save(values ...*model.WptPayCustomer) error
	First() (*model.WptPayCustomer, error)
	Take() (*model.WptPayCustomer, error)
	Last() (*model.WptPayCustomer, error)
	Find() ([]*model.WptPayCustomer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WptPayCustomer, err error)
	FindInBatches(result *[]*model.WptPayCustomer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.WptPayCustomer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWptPayCustomerDo
	Assign(attrs ...field.AssignExpr) IWptPayCustomerDo
	Joins(fields ...field.RelationField) IWptPayCustomerDo
	Preload(fields ...field.RelationField) IWptPayCustomerDo
	FirstOrInit() (*model.WptPayCustomer, error)
	FirstOrCreate() (*model.WptPayCustomer, error)
	FindByPage(offset int, limit int) (result []*model.WptPayCustomer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWptPayCustomerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w wptPayCustomerDo) Debug() IWptPayCustomerDo {
	return w.withDO(w.DO.Debug())
}

func (w wptPayCustomerDo) WithContext(ctx context.Context) IWptPayCustomerDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w wptPayCustomerDo) ReadDB() IWptPayCustomerDo {
	return w.Clauses(dbresolver.Read)
}

func (w wptPayCustomerDo) WriteDB() IWptPayCustomerDo {
	return w.Clauses(dbresolver.Write)
}

func (w wptPayCustomerDo) Session(config *gorm.Session) IWptPayCustomerDo {
	return w.withDO(w.DO.Session(config))
}

func (w wptPayCustomerDo) Clauses(conds ...clause.Expression) IWptPayCustomerDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w wptPayCustomerDo) Returning(value interface{}, columns ...string) IWptPayCustomerDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w wptPayCustomerDo) Not(conds ...gen.Condition) IWptPayCustomerDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w wptPayCustomerDo) Or(conds ...gen.Condition) IWptPayCustomerDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w wptPayCustomerDo) Select(conds ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w wptPayCustomerDo) Where(conds ...gen.Condition) IWptPayCustomerDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w wptPayCustomerDo) Order(conds ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w wptPayCustomerDo) Distinct(cols ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w wptPayCustomerDo) Omit(cols ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w wptPayCustomerDo) Join(table schema.Tabler, on ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w wptPayCustomerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w wptPayCustomerDo) RightJoin(table schema.Tabler, on ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w wptPayCustomerDo) Group(cols ...field.Expr) IWptPayCustomerDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w wptPayCustomerDo) Having(conds ...gen.Condition) IWptPayCustomerDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w wptPayCustomerDo) Limit(limit int) IWptPayCustomerDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w wptPayCustomerDo) Offset(offset int) IWptPayCustomerDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w wptPayCustomerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWptPayCustomerDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w wptPayCustomerDo) Unscoped() IWptPayCustomerDo {
	return w.withDO(w.DO.Unscoped())
}

func (w wptPayCustomerDo) Create(values ...*model.WptPayCustomer) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w wptPayCustomerDo) CreateInBatches(values []*model.WptPayCustomer, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w wptPayCustomerDo) Save(values ...*model.WptPayCustomer) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w wptPayCustomerDo) First() (*model.WptPayCustomer, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.WptPayCustomer), nil
	}
}

func (w wptPayCustomerDo) Take() (*model.WptPayCustomer, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.WptPayCustomer), nil
	}
}

func (w wptPayCustomerDo) Last() (*model.WptPayCustomer, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.WptPayCustomer), nil
	}
}

func (w wptPayCustomerDo) Find() ([]*model.WptPayCustomer, error) {
	result, err := w.DO.Find()
	return result.([]*model.WptPayCustomer), err
}

func (w wptPayCustomerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.WptPayCustomer, err error) {
	buf := make([]*model.WptPayCustomer, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w wptPayCustomerDo) FindInBatches(result *[]*model.WptPayCustomer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w wptPayCustomerDo) Attrs(attrs ...field.AssignExpr) IWptPayCustomerDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w wptPayCustomerDo) Assign(attrs ...field.AssignExpr) IWptPayCustomerDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w wptPayCustomerDo) Joins(fields ...field.RelationField) IWptPayCustomerDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w wptPayCustomerDo) Preload(fields ...field.RelationField) IWptPayCustomerDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w wptPayCustomerDo) FirstOrInit() (*model.WptPayCustomer, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.WptPayCustomer), nil
	}
}

func (w wptPayCustomerDo) FirstOrCreate() (*model.WptPayCustomer, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.WptPayCustomer), nil
	}
}

func (w wptPayCustomerDo) FindByPage(offset int, limit int) (result []*model.WptPayCustomer, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w wptPayCustomerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w wptPayCustomerDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w wptPayCustomerDo) Delete(models ...*model.WptPayCustomer) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *wptPayCustomerDo) withDO(do gen.Dao) *wptPayCustomerDo {
	w.DO = *do.(*gen.DO)
	return w
}
