// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/service/model"
)

func newBingoRecord(db *gorm.DB, opts ...gen.DOOption) bingoRecord {
	_bingoRecord := bingoRecord{}

	_bingoRecord.bingoRecordDo.UseDB(db, opts...)
	_bingoRecord.bingoRecordDo.UseModel(&model.BingoRecord{})

	tableName := _bingoRecord.bingoRecordDo.TableName()
	_bingoRecord.ALL = field.NewAsterisk(tableName)
	_bingoRecord.ID = field.NewUint32(tableName, "id")
	_bingoRecord.DrawTitle = field.NewString(tableName, "draw_title")
	_bingoRecord.DrawTime = field.NewUint32(tableName, "draw_time")
	_bingoRecord.DrawRule = field.NewString(tableName, "draw_rule")
	_bingoRecord.UID = field.NewUint32(tableName, "uid")
	_bingoRecord.NickName = field.NewString(tableName, "nick_name")
	_bingoRecord.RoomUUID = field.NewString(tableName, "room_uuid")
	_bingoRecord.RoomName = field.NewString(tableName, "room_name")
	_bingoRecord.GameType = field.NewUint32(tableName, "game_type")
	_bingoRecord.GameLevel = field.NewUint32(tableName, "game_level")
	_bingoRecord.DrawAmount = field.NewUint32(tableName, "draw_amount")
	_bingoRecord.Status = field.NewBool(tableName, "status")
	_bingoRecord.SeqCode = field.NewString(tableName, "seq_code")
	_bingoRecord.HandCount = field.NewUint32(tableName, "hand_count")
	_bingoRecord.TotalBetamount = field.NewUint64(tableName, "total_betamount")
	_bingoRecord.GameMode = field.NewUint32(tableName, "game_mode")
	_bingoRecord.Ante = field.NewUint32(tableName, "ante")
	_bingoRecord.LampMsg = field.NewString(tableName, "lamp_msg")
	_bingoRecord.ReceiveTime = field.NewUint32(tableName, "receive_time")
	_bingoRecord.InvalidFlag = field.NewUint32(tableName, "invalid_flag")
	_bingoRecord.LampTemplate = field.NewString(tableName, "lamp_template")
	_bingoRecord.GiveTime = field.NewUint32(tableName, "give_time")
	_bingoRecord.PrizeType = field.NewInt32(tableName, "prize_type")
	_bingoRecord.CurrencyType = field.NewInt32(tableName, "currency_type")
	_bingoRecord.ThirdID = field.NewInt32(tableName, "third_id")
	_bingoRecord.Plat = field.NewInt32(tableName, "plat")
	_bingoRecord.GoodsValue = field.NewInt32(tableName, "goods_value")
	_bingoRecord.GoodsDesc = field.NewString(tableName, "goods_desc")
	_bingoRecord.ToolID = field.NewInt32(tableName, "tool_id")
	_bingoRecord.ToolCount = field.NewInt32(tableName, "tool_count")
	_bingoRecord.RedWrapType = field.NewInt32(tableName, "red_wrap_type")
	_bingoRecord.HelpWrapData = field.NewString(tableName, "help_wrap_data")
	_bingoRecord.Code = field.NewInt32(tableName, "code")
	_bingoRecord.CodeCreateTime = field.NewInt32(tableName, "code_create_time")
	_bingoRecord.IsNew = field.NewBool(tableName, "is_new")
	_bingoRecord.ParentID = field.NewInt32(tableName, "parent_id")
	_bingoRecord.IsHighQualityUser = field.NewBool(tableName, "is_high_quality_user")
	_bingoRecord.IsHighQualityPrize = field.NewBool(tableName, "is_high_quality_prize")
	_bingoRecord.LooseMode = field.NewBool(tableName, "loose_mode")
	_bingoRecord.WinnerType = field.NewInt32(tableName, "winner_type")

	_bingoRecord.fillFieldMap()

	return _bingoRecord
}

// bingoRecord 存储一次抽奖中奖玩家的信息
type bingoRecord struct {
	bingoRecordDo

	ALL                field.Asterisk
	ID                 field.Uint32 // 流水ID
	DrawTitle          field.String // 标识一次抽奖活动的标题
	DrawTime           field.Uint32 // 抽奖时间
	DrawRule           field.String // 手数、金额抽奖区间
	UID                field.Uint32 // 用户ID
	NickName           field.String // 昵称
	RoomUUID           field.String // 房间的uuid
	RoomName           field.String // 房间的名称
	GameType           field.Uint32 // 2、德州扑克；10、德州牛仔；20、全下局、30、百人德州
	GameLevel          field.Uint32 // 牌局类型：德州为牌局盲注级别，牛仔为房间级别
	DrawAmount         field.Uint32 // 获奖金额
	Status             field.Bool   // 发奖状态：0抽中用户暂未发放奖励、1用户点击转盘后成功领取、3用户点击转盘后等待发放、4后台手动发放成功
	SeqCode            field.String // 该次抽奖有10个，是第1个中奖的，格式：1/10
	HandCount          field.Uint32 // 用户累计手数
	TotalBetamount     field.Uint64 // 用户累计金额
	GameMode           field.Uint32 // 牌局类型：1普通局、3短牌局
	Ante               field.Uint32 // 短牌牌局前注，没有的为0
	LampMsg            field.String // 跑马灯消息
	ReceiveTime        field.Uint32 // 玩家点击转盘领取奖励的时间
	InvalidFlag        field.Uint32 // 领取超时，是否作废:1作废，0有效
	LampTemplate       field.String // 红包跑马灯模板语
	GiveTime           field.Uint32 // 奖励发放时间(分为系统自动发放奖励的时间和后台手动发放奖励的时间)
	PrizeType          field.Int32  // 是否安慰奖：0否、1是
	CurrencyType       field.Int32  // 发奖货币的类型
	ThirdID            field.Int32  // 第三方用户id
	Plat               field.Int32  // 平台id 0：pkw 1：wpk
	GoodsValue         field.Int32  // 商品金额当currency_type为3代表商品id
	GoodsDesc          field.String // 商品描述
	ToolID             field.Int32  // mmt门票道具id
	ToolCount          field.Int32  // 门票数量
	RedWrapType        field.Int32  // 红包类型 0-抽奖发放的普通红包 1-抽奖发放的助力红包 2-后台发放胡助力红包
	HelpWrapData       field.String // 助力红包json数据
	Code               field.Int32  // 验证码
	CodeCreateTime     field.Int32  // 验证码生成时间
	IsNew              field.Bool   // 是否新语言数据
	ParentID           field.Int32  // 父id
	IsHighQualityUser  field.Bool   // 是不是高质量用户
	IsHighQualityPrize field.Bool   // 是不是高质量用户奖
	LooseMode          field.Bool   // 松浪模式
	WinnerType         field.Int32

	fieldMap map[string]field.Expr
}

func (b bingoRecord) Table(newTableName string) *bingoRecord {
	b.bingoRecordDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b bingoRecord) As(alias string) *bingoRecord {
	b.bingoRecordDo.DO = *(b.bingoRecordDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *bingoRecord) updateTableName(table string) *bingoRecord {
	b.ALL = field.NewAsterisk(table)
	b.ID = field.NewUint32(table, "id")
	b.DrawTitle = field.NewString(table, "draw_title")
	b.DrawTime = field.NewUint32(table, "draw_time")
	b.DrawRule = field.NewString(table, "draw_rule")
	b.UID = field.NewUint32(table, "uid")
	b.NickName = field.NewString(table, "nick_name")
	b.RoomUUID = field.NewString(table, "room_uuid")
	b.RoomName = field.NewString(table, "room_name")
	b.GameType = field.NewUint32(table, "game_type")
	b.GameLevel = field.NewUint32(table, "game_level")
	b.DrawAmount = field.NewUint32(table, "draw_amount")
	b.Status = field.NewBool(table, "status")
	b.SeqCode = field.NewString(table, "seq_code")
	b.HandCount = field.NewUint32(table, "hand_count")
	b.TotalBetamount = field.NewUint64(table, "total_betamount")
	b.GameMode = field.NewUint32(table, "game_mode")
	b.Ante = field.NewUint32(table, "ante")
	b.LampMsg = field.NewString(table, "lamp_msg")
	b.ReceiveTime = field.NewUint32(table, "receive_time")
	b.InvalidFlag = field.NewUint32(table, "invalid_flag")
	b.LampTemplate = field.NewString(table, "lamp_template")
	b.GiveTime = field.NewUint32(table, "give_time")
	b.PrizeType = field.NewInt32(table, "prize_type")
	b.CurrencyType = field.NewInt32(table, "currency_type")
	b.ThirdID = field.NewInt32(table, "third_id")
	b.Plat = field.NewInt32(table, "plat")
	b.GoodsValue = field.NewInt32(table, "goods_value")
	b.GoodsDesc = field.NewString(table, "goods_desc")
	b.ToolID = field.NewInt32(table, "tool_id")
	b.ToolCount = field.NewInt32(table, "tool_count")
	b.RedWrapType = field.NewInt32(table, "red_wrap_type")
	b.HelpWrapData = field.NewString(table, "help_wrap_data")
	b.Code = field.NewInt32(table, "code")
	b.CodeCreateTime = field.NewInt32(table, "code_create_time")
	b.IsNew = field.NewBool(table, "is_new")
	b.ParentID = field.NewInt32(table, "parent_id")
	b.IsHighQualityUser = field.NewBool(table, "is_high_quality_user")
	b.IsHighQualityPrize = field.NewBool(table, "is_high_quality_prize")
	b.LooseMode = field.NewBool(table, "loose_mode")
	b.WinnerType = field.NewInt32(table, "winner_type")

	b.fillFieldMap()

	return b
}

func (b *bingoRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *bingoRecord) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 40)
	b.fieldMap["id"] = b.ID
	b.fieldMap["draw_title"] = b.DrawTitle
	b.fieldMap["draw_time"] = b.DrawTime
	b.fieldMap["draw_rule"] = b.DrawRule
	b.fieldMap["uid"] = b.UID
	b.fieldMap["nick_name"] = b.NickName
	b.fieldMap["room_uuid"] = b.RoomUUID
	b.fieldMap["room_name"] = b.RoomName
	b.fieldMap["game_type"] = b.GameType
	b.fieldMap["game_level"] = b.GameLevel
	b.fieldMap["draw_amount"] = b.DrawAmount
	b.fieldMap["status"] = b.Status
	b.fieldMap["seq_code"] = b.SeqCode
	b.fieldMap["hand_count"] = b.HandCount
	b.fieldMap["total_betamount"] = b.TotalBetamount
	b.fieldMap["game_mode"] = b.GameMode
	b.fieldMap["ante"] = b.Ante
	b.fieldMap["lamp_msg"] = b.LampMsg
	b.fieldMap["receive_time"] = b.ReceiveTime
	b.fieldMap["invalid_flag"] = b.InvalidFlag
	b.fieldMap["lamp_template"] = b.LampTemplate
	b.fieldMap["give_time"] = b.GiveTime
	b.fieldMap["prize_type"] = b.PrizeType
	b.fieldMap["currency_type"] = b.CurrencyType
	b.fieldMap["third_id"] = b.ThirdID
	b.fieldMap["plat"] = b.Plat
	b.fieldMap["goods_value"] = b.GoodsValue
	b.fieldMap["goods_desc"] = b.GoodsDesc
	b.fieldMap["tool_id"] = b.ToolID
	b.fieldMap["tool_count"] = b.ToolCount
	b.fieldMap["red_wrap_type"] = b.RedWrapType
	b.fieldMap["help_wrap_data"] = b.HelpWrapData
	b.fieldMap["code"] = b.Code
	b.fieldMap["code_create_time"] = b.CodeCreateTime
	b.fieldMap["is_new"] = b.IsNew
	b.fieldMap["parent_id"] = b.ParentID
	b.fieldMap["is_high_quality_user"] = b.IsHighQualityUser
	b.fieldMap["is_high_quality_prize"] = b.IsHighQualityPrize
	b.fieldMap["loose_mode"] = b.LooseMode
	b.fieldMap["winner_type"] = b.WinnerType
}

func (b bingoRecord) clone(db *gorm.DB) bingoRecord {
	b.bingoRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b bingoRecord) replaceDB(db *gorm.DB) bingoRecord {
	b.bingoRecordDo.ReplaceDB(db)
	return b
}

type bingoRecordDo struct{ gen.DO }

type IBingoRecordDo interface {
	gen.SubQuery
	Debug() IBingoRecordDo
	WithContext(ctx context.Context) IBingoRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IBingoRecordDo
	WriteDB() IBingoRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IBingoRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IBingoRecordDo
	Not(conds ...gen.Condition) IBingoRecordDo
	Or(conds ...gen.Condition) IBingoRecordDo
	Select(conds ...field.Expr) IBingoRecordDo
	Where(conds ...gen.Condition) IBingoRecordDo
	Order(conds ...field.Expr) IBingoRecordDo
	Distinct(cols ...field.Expr) IBingoRecordDo
	Omit(cols ...field.Expr) IBingoRecordDo
	Join(table schema.Tabler, on ...field.Expr) IBingoRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IBingoRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IBingoRecordDo
	Group(cols ...field.Expr) IBingoRecordDo
	Having(conds ...gen.Condition) IBingoRecordDo
	Limit(limit int) IBingoRecordDo
	Offset(offset int) IBingoRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IBingoRecordDo
	Unscoped() IBingoRecordDo
	Create(values ...*model.BingoRecord) error
	CreateInBatches(values []*model.BingoRecord, batchSize int) error
	Save(values ...*model.BingoRecord) error
	First() (*model.BingoRecord, error)
	Take() (*model.BingoRecord, error)
	Last() (*model.BingoRecord, error)
	Find() ([]*model.BingoRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BingoRecord, err error)
	FindInBatches(result *[]*model.BingoRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.BingoRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IBingoRecordDo
	Assign(attrs ...field.AssignExpr) IBingoRecordDo
	Joins(fields ...field.RelationField) IBingoRecordDo
	Preload(fields ...field.RelationField) IBingoRecordDo
	FirstOrInit() (*model.BingoRecord, error)
	FirstOrCreate() (*model.BingoRecord, error)
	FindByPage(offset int, limit int) (result []*model.BingoRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IBingoRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (b bingoRecordDo) Debug() IBingoRecordDo {
	return b.withDO(b.DO.Debug())
}

func (b bingoRecordDo) WithContext(ctx context.Context) IBingoRecordDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b bingoRecordDo) ReadDB() IBingoRecordDo {
	return b.Clauses(dbresolver.Read)
}

func (b bingoRecordDo) WriteDB() IBingoRecordDo {
	return b.Clauses(dbresolver.Write)
}

func (b bingoRecordDo) Session(config *gorm.Session) IBingoRecordDo {
	return b.withDO(b.DO.Session(config))
}

func (b bingoRecordDo) Clauses(conds ...clause.Expression) IBingoRecordDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b bingoRecordDo) Returning(value interface{}, columns ...string) IBingoRecordDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b bingoRecordDo) Not(conds ...gen.Condition) IBingoRecordDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b bingoRecordDo) Or(conds ...gen.Condition) IBingoRecordDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b bingoRecordDo) Select(conds ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b bingoRecordDo) Where(conds ...gen.Condition) IBingoRecordDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b bingoRecordDo) Order(conds ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b bingoRecordDo) Distinct(cols ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b bingoRecordDo) Omit(cols ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b bingoRecordDo) Join(table schema.Tabler, on ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b bingoRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b bingoRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b bingoRecordDo) Group(cols ...field.Expr) IBingoRecordDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b bingoRecordDo) Having(conds ...gen.Condition) IBingoRecordDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b bingoRecordDo) Limit(limit int) IBingoRecordDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b bingoRecordDo) Offset(offset int) IBingoRecordDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b bingoRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IBingoRecordDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b bingoRecordDo) Unscoped() IBingoRecordDo {
	return b.withDO(b.DO.Unscoped())
}

func (b bingoRecordDo) Create(values ...*model.BingoRecord) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b bingoRecordDo) CreateInBatches(values []*model.BingoRecord, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b bingoRecordDo) Save(values ...*model.BingoRecord) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b bingoRecordDo) First() (*model.BingoRecord, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BingoRecord), nil
	}
}

func (b bingoRecordDo) Take() (*model.BingoRecord, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BingoRecord), nil
	}
}

func (b bingoRecordDo) Last() (*model.BingoRecord, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BingoRecord), nil
	}
}

func (b bingoRecordDo) Find() ([]*model.BingoRecord, error) {
	result, err := b.DO.Find()
	return result.([]*model.BingoRecord), err
}

func (b bingoRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BingoRecord, err error) {
	buf := make([]*model.BingoRecord, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b bingoRecordDo) FindInBatches(result *[]*model.BingoRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b bingoRecordDo) Attrs(attrs ...field.AssignExpr) IBingoRecordDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b bingoRecordDo) Assign(attrs ...field.AssignExpr) IBingoRecordDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b bingoRecordDo) Joins(fields ...field.RelationField) IBingoRecordDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b bingoRecordDo) Preload(fields ...field.RelationField) IBingoRecordDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b bingoRecordDo) FirstOrInit() (*model.BingoRecord, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BingoRecord), nil
	}
}

func (b bingoRecordDo) FirstOrCreate() (*model.BingoRecord, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BingoRecord), nil
	}
}

func (b bingoRecordDo) FindByPage(offset int, limit int) (result []*model.BingoRecord, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b bingoRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b bingoRecordDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b bingoRecordDo) Delete(models ...*model.BingoRecord) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *bingoRecordDo) withDO(do gen.Dao) *bingoRecordDo {
	b.DO = *do.(*gen.DO)
	return b
}
