// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/service/model"
)

func newCoinCaptcha(db *gorm.DB, opts ...gen.DOOption) coinCaptcha {
	_coinCaptcha := coinCaptcha{}

	_coinCaptcha.coinCaptchaDo.UseDB(db, opts...)
	_coinCaptcha.coinCaptchaDo.UseModel(&model.CoinCaptcha{})

	tableName := _coinCaptcha.coinCaptchaDo.TableName()
	_coinCaptcha.ALL = field.NewAsterisk(tableName)
	_coinCaptcha.ID = field.NewUint32(tableName, "id")
	_coinCaptcha.Duuid = field.NewString(tableName, "duuid")
	_coinCaptcha.DeviceUUID = field.NewString(tableName, "device_uuid")
	_coinCaptcha.Captcha = field.NewString(tableName, "captcha")
	_coinCaptcha.IP = field.NewString(tableName, "ip")
	_coinCaptcha.CreateTime = field.NewUint32(tableName, "create_time")
	_coinCaptcha.UpdateTime = field.NewUint32(tableName, "update_time")
	_coinCaptcha.ClientType = field.NewInt32(tableName, "client_type")

	_coinCaptcha.fillFieldMap()

	return _coinCaptcha
}

// coinCaptcha 验证码表
type coinCaptcha struct {
	coinCaptchaDo

	ALL        field.Asterisk
	ID         field.Uint32 // id
	Duuid      field.String // device_uuid的md5值
	DeviceUUID field.String // device_uuid
	Captcha    field.String // 验证码
	IP         field.String // IP
	CreateTime field.Uint32 // 创建时间
	UpdateTime field.Uint32 // 修改时间
	ClientType field.Int32  // 客户端类型 1:常规 2:海外 3:h5常规 4:H5海外 5:h5常规web 6:H5海外web

	fieldMap map[string]field.Expr
}

func (c coinCaptcha) Table(newTableName string) *coinCaptcha {
	c.coinCaptchaDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c coinCaptcha) As(alias string) *coinCaptcha {
	c.coinCaptchaDo.DO = *(c.coinCaptchaDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *coinCaptcha) updateTableName(table string) *coinCaptcha {
	c.ALL = field.NewAsterisk(table)
	c.ID = field.NewUint32(table, "id")
	c.Duuid = field.NewString(table, "duuid")
	c.DeviceUUID = field.NewString(table, "device_uuid")
	c.Captcha = field.NewString(table, "captcha")
	c.IP = field.NewString(table, "ip")
	c.CreateTime = field.NewUint32(table, "create_time")
	c.UpdateTime = field.NewUint32(table, "update_time")
	c.ClientType = field.NewInt32(table, "client_type")

	c.fillFieldMap()

	return c
}

func (c *coinCaptcha) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *coinCaptcha) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 8)
	c.fieldMap["id"] = c.ID
	c.fieldMap["duuid"] = c.Duuid
	c.fieldMap["device_uuid"] = c.DeviceUUID
	c.fieldMap["captcha"] = c.Captcha
	c.fieldMap["ip"] = c.IP
	c.fieldMap["create_time"] = c.CreateTime
	c.fieldMap["update_time"] = c.UpdateTime
	c.fieldMap["client_type"] = c.ClientType
}

func (c coinCaptcha) clone(db *gorm.DB) coinCaptcha {
	c.coinCaptchaDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c coinCaptcha) replaceDB(db *gorm.DB) coinCaptcha {
	c.coinCaptchaDo.ReplaceDB(db)
	return c
}

type coinCaptchaDo struct{ gen.DO }

type ICoinCaptchaDo interface {
	gen.SubQuery
	Debug() ICoinCaptchaDo
	WithContext(ctx context.Context) ICoinCaptchaDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICoinCaptchaDo
	WriteDB() ICoinCaptchaDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICoinCaptchaDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICoinCaptchaDo
	Not(conds ...gen.Condition) ICoinCaptchaDo
	Or(conds ...gen.Condition) ICoinCaptchaDo
	Select(conds ...field.Expr) ICoinCaptchaDo
	Where(conds ...gen.Condition) ICoinCaptchaDo
	Order(conds ...field.Expr) ICoinCaptchaDo
	Distinct(cols ...field.Expr) ICoinCaptchaDo
	Omit(cols ...field.Expr) ICoinCaptchaDo
	Join(table schema.Tabler, on ...field.Expr) ICoinCaptchaDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICoinCaptchaDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICoinCaptchaDo
	Group(cols ...field.Expr) ICoinCaptchaDo
	Having(conds ...gen.Condition) ICoinCaptchaDo
	Limit(limit int) ICoinCaptchaDo
	Offset(offset int) ICoinCaptchaDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICoinCaptchaDo
	Unscoped() ICoinCaptchaDo
	Create(values ...*model.CoinCaptcha) error
	CreateInBatches(values []*model.CoinCaptcha, batchSize int) error
	Save(values ...*model.CoinCaptcha) error
	First() (*model.CoinCaptcha, error)
	Take() (*model.CoinCaptcha, error)
	Last() (*model.CoinCaptcha, error)
	Find() ([]*model.CoinCaptcha, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CoinCaptcha, err error)
	FindInBatches(result *[]*model.CoinCaptcha, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CoinCaptcha) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICoinCaptchaDo
	Assign(attrs ...field.AssignExpr) ICoinCaptchaDo
	Joins(fields ...field.RelationField) ICoinCaptchaDo
	Preload(fields ...field.RelationField) ICoinCaptchaDo
	FirstOrInit() (*model.CoinCaptcha, error)
	FirstOrCreate() (*model.CoinCaptcha, error)
	FindByPage(offset int, limit int) (result []*model.CoinCaptcha, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICoinCaptchaDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c coinCaptchaDo) Debug() ICoinCaptchaDo {
	return c.withDO(c.DO.Debug())
}

func (c coinCaptchaDo) WithContext(ctx context.Context) ICoinCaptchaDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c coinCaptchaDo) ReadDB() ICoinCaptchaDo {
	return c.Clauses(dbresolver.Read)
}

func (c coinCaptchaDo) WriteDB() ICoinCaptchaDo {
	return c.Clauses(dbresolver.Write)
}

func (c coinCaptchaDo) Session(config *gorm.Session) ICoinCaptchaDo {
	return c.withDO(c.DO.Session(config))
}

func (c coinCaptchaDo) Clauses(conds ...clause.Expression) ICoinCaptchaDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c coinCaptchaDo) Returning(value interface{}, columns ...string) ICoinCaptchaDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c coinCaptchaDo) Not(conds ...gen.Condition) ICoinCaptchaDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c coinCaptchaDo) Or(conds ...gen.Condition) ICoinCaptchaDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c coinCaptchaDo) Select(conds ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c coinCaptchaDo) Where(conds ...gen.Condition) ICoinCaptchaDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c coinCaptchaDo) Order(conds ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c coinCaptchaDo) Distinct(cols ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c coinCaptchaDo) Omit(cols ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c coinCaptchaDo) Join(table schema.Tabler, on ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c coinCaptchaDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c coinCaptchaDo) RightJoin(table schema.Tabler, on ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c coinCaptchaDo) Group(cols ...field.Expr) ICoinCaptchaDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c coinCaptchaDo) Having(conds ...gen.Condition) ICoinCaptchaDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c coinCaptchaDo) Limit(limit int) ICoinCaptchaDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c coinCaptchaDo) Offset(offset int) ICoinCaptchaDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c coinCaptchaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICoinCaptchaDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c coinCaptchaDo) Unscoped() ICoinCaptchaDo {
	return c.withDO(c.DO.Unscoped())
}

func (c coinCaptchaDo) Create(values ...*model.CoinCaptcha) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c coinCaptchaDo) CreateInBatches(values []*model.CoinCaptcha, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c coinCaptchaDo) Save(values ...*model.CoinCaptcha) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c coinCaptchaDo) First() (*model.CoinCaptcha, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoinCaptcha), nil
	}
}

func (c coinCaptchaDo) Take() (*model.CoinCaptcha, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoinCaptcha), nil
	}
}

func (c coinCaptchaDo) Last() (*model.CoinCaptcha, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoinCaptcha), nil
	}
}

func (c coinCaptchaDo) Find() ([]*model.CoinCaptcha, error) {
	result, err := c.DO.Find()
	return result.([]*model.CoinCaptcha), err
}

func (c coinCaptchaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CoinCaptcha, err error) {
	buf := make([]*model.CoinCaptcha, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c coinCaptchaDo) FindInBatches(result *[]*model.CoinCaptcha, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c coinCaptchaDo) Attrs(attrs ...field.AssignExpr) ICoinCaptchaDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c coinCaptchaDo) Assign(attrs ...field.AssignExpr) ICoinCaptchaDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c coinCaptchaDo) Joins(fields ...field.RelationField) ICoinCaptchaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c coinCaptchaDo) Preload(fields ...field.RelationField) ICoinCaptchaDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c coinCaptchaDo) FirstOrInit() (*model.CoinCaptcha, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoinCaptcha), nil
	}
}

func (c coinCaptchaDo) FirstOrCreate() (*model.CoinCaptcha, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CoinCaptcha), nil
	}
}

func (c coinCaptchaDo) FindByPage(offset int, limit int) (result []*model.CoinCaptcha, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c coinCaptchaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c coinCaptchaDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c coinCaptchaDo) Delete(models ...*model.CoinCaptcha) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *coinCaptchaDo) withDO(do gen.Dao) *coinCaptchaDo {
	c.DO = *do.(*gen.DO)
	return c
}
