// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/service/model"
)

func newDtbLimitGameOrder(db *gorm.DB, opts ...gen.DOOption) dtbLimitGameOrder {
	_dtbLimitGameOrder := dtbLimitGameOrder{}

	_dtbLimitGameOrder.dtbLimitGameOrderDo.UseDB(db, opts...)
	_dtbLimitGameOrder.dtbLimitGameOrderDo.UseModel(&model.DtbLimitGameOrder{})

	tableName := _dtbLimitGameOrder.dtbLimitGameOrderDo.TableName()
	_dtbLimitGameOrder.ALL = field.NewAsterisk(tableName)
	_dtbLimitGameOrder.ID = field.NewUint32(tableName, "id")
	_dtbLimitGameOrder.Rid = field.NewInt32(tableName, "rid")
	_dtbLimitGameOrder.Type = field.NewInt32(tableName, "type")
	_dtbLimitGameOrder.Timezone = field.NewString(tableName, "timezone")
	_dtbLimitGameOrder.Country = field.NewString(tableName, "country")
	_dtbLimitGameOrder.Region = field.NewString(tableName, "region")
	_dtbLimitGameOrder.City = field.NewString(tableName, "city")
	_dtbLimitGameOrder.Status = field.NewInt32(tableName, "status")
	_dtbLimitGameOrder.CreateTime = field.NewUint32(tableName, "create_time")
	_dtbLimitGameOrder.UpdateTime = field.NewUint32(tableName, "update_time")

	_dtbLimitGameOrder.fillFieldMap()

	return _dtbLimitGameOrder
}

// dtbLimitGameOrder 限制游戏订单表
type dtbLimitGameOrder struct {
	dtbLimitGameOrderDo

	ALL        field.Asterisk
	ID         field.Uint32 // id
	Rid        field.Int32  // 限制游戏订单id
	Type       field.Int32  // 类别 1黑名单 2白名单
	Timezone   field.String // 洲名
	Country    field.String // 国家名
	Region     field.String // 地区名
	City       field.String // 城市名
	Status     field.Int32  // 状态：0草稿 1生效
	CreateTime field.Uint32 // 创建时间
	UpdateTime field.Uint32 // 修改时间

	fieldMap map[string]field.Expr
}

func (d dtbLimitGameOrder) Table(newTableName string) *dtbLimitGameOrder {
	d.dtbLimitGameOrderDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dtbLimitGameOrder) As(alias string) *dtbLimitGameOrder {
	d.dtbLimitGameOrderDo.DO = *(d.dtbLimitGameOrderDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dtbLimitGameOrder) updateTableName(table string) *dtbLimitGameOrder {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewUint32(table, "id")
	d.Rid = field.NewInt32(table, "rid")
	d.Type = field.NewInt32(table, "type")
	d.Timezone = field.NewString(table, "timezone")
	d.Country = field.NewString(table, "country")
	d.Region = field.NewString(table, "region")
	d.City = field.NewString(table, "city")
	d.Status = field.NewInt32(table, "status")
	d.CreateTime = field.NewUint32(table, "create_time")
	d.UpdateTime = field.NewUint32(table, "update_time")

	d.fillFieldMap()

	return d
}

func (d *dtbLimitGameOrder) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dtbLimitGameOrder) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 10)
	d.fieldMap["id"] = d.ID
	d.fieldMap["rid"] = d.Rid
	d.fieldMap["type"] = d.Type
	d.fieldMap["timezone"] = d.Timezone
	d.fieldMap["country"] = d.Country
	d.fieldMap["region"] = d.Region
	d.fieldMap["city"] = d.City
	d.fieldMap["status"] = d.Status
	d.fieldMap["create_time"] = d.CreateTime
	d.fieldMap["update_time"] = d.UpdateTime
}

func (d dtbLimitGameOrder) clone(db *gorm.DB) dtbLimitGameOrder {
	d.dtbLimitGameOrderDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dtbLimitGameOrder) replaceDB(db *gorm.DB) dtbLimitGameOrder {
	d.dtbLimitGameOrderDo.ReplaceDB(db)
	return d
}

type dtbLimitGameOrderDo struct{ gen.DO }

type IDtbLimitGameOrderDo interface {
	gen.SubQuery
	Debug() IDtbLimitGameOrderDo
	WithContext(ctx context.Context) IDtbLimitGameOrderDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDtbLimitGameOrderDo
	WriteDB() IDtbLimitGameOrderDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDtbLimitGameOrderDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDtbLimitGameOrderDo
	Not(conds ...gen.Condition) IDtbLimitGameOrderDo
	Or(conds ...gen.Condition) IDtbLimitGameOrderDo
	Select(conds ...field.Expr) IDtbLimitGameOrderDo
	Where(conds ...gen.Condition) IDtbLimitGameOrderDo
	Order(conds ...field.Expr) IDtbLimitGameOrderDo
	Distinct(cols ...field.Expr) IDtbLimitGameOrderDo
	Omit(cols ...field.Expr) IDtbLimitGameOrderDo
	Join(table schema.Tabler, on ...field.Expr) IDtbLimitGameOrderDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDtbLimitGameOrderDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDtbLimitGameOrderDo
	Group(cols ...field.Expr) IDtbLimitGameOrderDo
	Having(conds ...gen.Condition) IDtbLimitGameOrderDo
	Limit(limit int) IDtbLimitGameOrderDo
	Offset(offset int) IDtbLimitGameOrderDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbLimitGameOrderDo
	Unscoped() IDtbLimitGameOrderDo
	Create(values ...*model.DtbLimitGameOrder) error
	CreateInBatches(values []*model.DtbLimitGameOrder, batchSize int) error
	Save(values ...*model.DtbLimitGameOrder) error
	First() (*model.DtbLimitGameOrder, error)
	Take() (*model.DtbLimitGameOrder, error)
	Last() (*model.DtbLimitGameOrder, error)
	Find() ([]*model.DtbLimitGameOrder, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbLimitGameOrder, err error)
	FindInBatches(result *[]*model.DtbLimitGameOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DtbLimitGameOrder) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDtbLimitGameOrderDo
	Assign(attrs ...field.AssignExpr) IDtbLimitGameOrderDo
	Joins(fields ...field.RelationField) IDtbLimitGameOrderDo
	Preload(fields ...field.RelationField) IDtbLimitGameOrderDo
	FirstOrInit() (*model.DtbLimitGameOrder, error)
	FirstOrCreate() (*model.DtbLimitGameOrder, error)
	FindByPage(offset int, limit int) (result []*model.DtbLimitGameOrder, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDtbLimitGameOrderDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dtbLimitGameOrderDo) Debug() IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Debug())
}

func (d dtbLimitGameOrderDo) WithContext(ctx context.Context) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dtbLimitGameOrderDo) ReadDB() IDtbLimitGameOrderDo {
	return d.Clauses(dbresolver.Read)
}

func (d dtbLimitGameOrderDo) WriteDB() IDtbLimitGameOrderDo {
	return d.Clauses(dbresolver.Write)
}

func (d dtbLimitGameOrderDo) Session(config *gorm.Session) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Session(config))
}

func (d dtbLimitGameOrderDo) Clauses(conds ...clause.Expression) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dtbLimitGameOrderDo) Returning(value interface{}, columns ...string) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dtbLimitGameOrderDo) Not(conds ...gen.Condition) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dtbLimitGameOrderDo) Or(conds ...gen.Condition) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dtbLimitGameOrderDo) Select(conds ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dtbLimitGameOrderDo) Where(conds ...gen.Condition) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dtbLimitGameOrderDo) Order(conds ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dtbLimitGameOrderDo) Distinct(cols ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dtbLimitGameOrderDo) Omit(cols ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dtbLimitGameOrderDo) Join(table schema.Tabler, on ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dtbLimitGameOrderDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dtbLimitGameOrderDo) RightJoin(table schema.Tabler, on ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dtbLimitGameOrderDo) Group(cols ...field.Expr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dtbLimitGameOrderDo) Having(conds ...gen.Condition) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dtbLimitGameOrderDo) Limit(limit int) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dtbLimitGameOrderDo) Offset(offset int) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dtbLimitGameOrderDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dtbLimitGameOrderDo) Unscoped() IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dtbLimitGameOrderDo) Create(values ...*model.DtbLimitGameOrder) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dtbLimitGameOrderDo) CreateInBatches(values []*model.DtbLimitGameOrder, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dtbLimitGameOrderDo) Save(values ...*model.DtbLimitGameOrder) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dtbLimitGameOrderDo) First() (*model.DtbLimitGameOrder, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbLimitGameOrder), nil
	}
}

func (d dtbLimitGameOrderDo) Take() (*model.DtbLimitGameOrder, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbLimitGameOrder), nil
	}
}

func (d dtbLimitGameOrderDo) Last() (*model.DtbLimitGameOrder, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbLimitGameOrder), nil
	}
}

func (d dtbLimitGameOrderDo) Find() ([]*model.DtbLimitGameOrder, error) {
	result, err := d.DO.Find()
	return result.([]*model.DtbLimitGameOrder), err
}

func (d dtbLimitGameOrderDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DtbLimitGameOrder, err error) {
	buf := make([]*model.DtbLimitGameOrder, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dtbLimitGameOrderDo) FindInBatches(result *[]*model.DtbLimitGameOrder, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dtbLimitGameOrderDo) Attrs(attrs ...field.AssignExpr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dtbLimitGameOrderDo) Assign(attrs ...field.AssignExpr) IDtbLimitGameOrderDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dtbLimitGameOrderDo) Joins(fields ...field.RelationField) IDtbLimitGameOrderDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dtbLimitGameOrderDo) Preload(fields ...field.RelationField) IDtbLimitGameOrderDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dtbLimitGameOrderDo) FirstOrInit() (*model.DtbLimitGameOrder, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbLimitGameOrder), nil
	}
}

func (d dtbLimitGameOrderDo) FirstOrCreate() (*model.DtbLimitGameOrder, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DtbLimitGameOrder), nil
	}
}

func (d dtbLimitGameOrderDo) FindByPage(offset int, limit int) (result []*model.DtbLimitGameOrder, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dtbLimitGameOrderDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dtbLimitGameOrderDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dtbLimitGameOrderDo) Delete(models ...*model.DtbLimitGameOrder) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dtbLimitGameOrderDo) withDO(do gen.Dao) *dtbLimitGameOrderDo {
	d.DO = *do.(*gen.DO)
	return d
}
