// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"godemo/internal/service/model"
)

func newHelpWrapDatum(db *gorm.DB, opts ...gen.DOOption) helpWrapDatum {
	_helpWrapDatum := helpWrapDatum{}

	_helpWrapDatum.helpWrapDatumDo.UseDB(db, opts...)
	_helpWrapDatum.helpWrapDatumDo.UseModel(&model.HelpWrapDatum{})

	tableName := _helpWrapDatum.helpWrapDatumDo.TableName()
	_helpWrapDatum.ALL = field.NewAsterisk(tableName)
	_helpWrapDatum.ID = field.NewUint64(tableName, "id")
	_helpWrapDatum.BingoID = field.NewUint64(tableName, "bingo_id")
	_helpWrapDatum.HelpCount = field.NewUint32(tableName, "help_count")
	_helpWrapDatum.ExpireTime = field.NewInt32(tableName, "expire_time")
	_helpWrapDatum.LuckType = field.NewInt32(tableName, "luck_type")
	_helpWrapDatum.HelperType = field.NewInt32(tableName, "helper_type")
	_helpWrapDatum.CreateTime = field.NewInt32(tableName, "create_time")
	_helpWrapDatum.HelpState = field.NewInt32(tableName, "help_state")
	_helpWrapDatum.UpdateTime = field.NewInt32(tableName, "update_time")

	_helpWrapDatum.fillFieldMap()

	return _helpWrapDatum
}

type helpWrapDatum struct {
	helpWrapDatumDo

	ALL        field.Asterisk
	ID         field.Uint64 // 自增ID
	BingoID    field.Uint64 // 抽奖记录表id
	HelpCount  field.Uint32 // 需要助力次数
	ExpireTime field.Int32  // 过期时间(单位秒)
	LuckType   field.Int32  // 助力包类型 0-金额红包 1-门票红包
	HelperType field.Int32  // 助力者助力成功获得红包类型 0-金额红包 1-门票红包
	CreateTime field.Int32  // 验证码生成时间
	HelpState  field.Int32  // 完成状态 0-助力中 1-已过期 2-已助力完成 3-已领取
	UpdateTime field.Int32  // 状态更新时间

	fieldMap map[string]field.Expr
}

func (h helpWrapDatum) Table(newTableName string) *helpWrapDatum {
	h.helpWrapDatumDo.UseTable(newTableName)
	return h.updateTableName(newTableName)
}

func (h helpWrapDatum) As(alias string) *helpWrapDatum {
	h.helpWrapDatumDo.DO = *(h.helpWrapDatumDo.As(alias).(*gen.DO))
	return h.updateTableName(alias)
}

func (h *helpWrapDatum) updateTableName(table string) *helpWrapDatum {
	h.ALL = field.NewAsterisk(table)
	h.ID = field.NewUint64(table, "id")
	h.BingoID = field.NewUint64(table, "bingo_id")
	h.HelpCount = field.NewUint32(table, "help_count")
	h.ExpireTime = field.NewInt32(table, "expire_time")
	h.LuckType = field.NewInt32(table, "luck_type")
	h.HelperType = field.NewInt32(table, "helper_type")
	h.CreateTime = field.NewInt32(table, "create_time")
	h.HelpState = field.NewInt32(table, "help_state")
	h.UpdateTime = field.NewInt32(table, "update_time")

	h.fillFieldMap()

	return h
}

func (h *helpWrapDatum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := h.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (h *helpWrapDatum) fillFieldMap() {
	h.fieldMap = make(map[string]field.Expr, 9)
	h.fieldMap["id"] = h.ID
	h.fieldMap["bingo_id"] = h.BingoID
	h.fieldMap["help_count"] = h.HelpCount
	h.fieldMap["expire_time"] = h.ExpireTime
	h.fieldMap["luck_type"] = h.LuckType
	h.fieldMap["helper_type"] = h.HelperType
	h.fieldMap["create_time"] = h.CreateTime
	h.fieldMap["help_state"] = h.HelpState
	h.fieldMap["update_time"] = h.UpdateTime
}

func (h helpWrapDatum) clone(db *gorm.DB) helpWrapDatum {
	h.helpWrapDatumDo.ReplaceConnPool(db.Statement.ConnPool)
	return h
}

func (h helpWrapDatum) replaceDB(db *gorm.DB) helpWrapDatum {
	h.helpWrapDatumDo.ReplaceDB(db)
	return h
}

type helpWrapDatumDo struct{ gen.DO }

type IHelpWrapDatumDo interface {
	gen.SubQuery
	Debug() IHelpWrapDatumDo
	WithContext(ctx context.Context) IHelpWrapDatumDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IHelpWrapDatumDo
	WriteDB() IHelpWrapDatumDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IHelpWrapDatumDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IHelpWrapDatumDo
	Not(conds ...gen.Condition) IHelpWrapDatumDo
	Or(conds ...gen.Condition) IHelpWrapDatumDo
	Select(conds ...field.Expr) IHelpWrapDatumDo
	Where(conds ...gen.Condition) IHelpWrapDatumDo
	Order(conds ...field.Expr) IHelpWrapDatumDo
	Distinct(cols ...field.Expr) IHelpWrapDatumDo
	Omit(cols ...field.Expr) IHelpWrapDatumDo
	Join(table schema.Tabler, on ...field.Expr) IHelpWrapDatumDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IHelpWrapDatumDo
	RightJoin(table schema.Tabler, on ...field.Expr) IHelpWrapDatumDo
	Group(cols ...field.Expr) IHelpWrapDatumDo
	Having(conds ...gen.Condition) IHelpWrapDatumDo
	Limit(limit int) IHelpWrapDatumDo
	Offset(offset int) IHelpWrapDatumDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IHelpWrapDatumDo
	Unscoped() IHelpWrapDatumDo
	Create(values ...*model.HelpWrapDatum) error
	CreateInBatches(values []*model.HelpWrapDatum, batchSize int) error
	Save(values ...*model.HelpWrapDatum) error
	First() (*model.HelpWrapDatum, error)
	Take() (*model.HelpWrapDatum, error)
	Last() (*model.HelpWrapDatum, error)
	Find() ([]*model.HelpWrapDatum, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HelpWrapDatum, err error)
	FindInBatches(result *[]*model.HelpWrapDatum, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.HelpWrapDatum) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IHelpWrapDatumDo
	Assign(attrs ...field.AssignExpr) IHelpWrapDatumDo
	Joins(fields ...field.RelationField) IHelpWrapDatumDo
	Preload(fields ...field.RelationField) IHelpWrapDatumDo
	FirstOrInit() (*model.HelpWrapDatum, error)
	FirstOrCreate() (*model.HelpWrapDatum, error)
	FindByPage(offset int, limit int) (result []*model.HelpWrapDatum, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IHelpWrapDatumDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (h helpWrapDatumDo) Debug() IHelpWrapDatumDo {
	return h.withDO(h.DO.Debug())
}

func (h helpWrapDatumDo) WithContext(ctx context.Context) IHelpWrapDatumDo {
	return h.withDO(h.DO.WithContext(ctx))
}

func (h helpWrapDatumDo) ReadDB() IHelpWrapDatumDo {
	return h.Clauses(dbresolver.Read)
}

func (h helpWrapDatumDo) WriteDB() IHelpWrapDatumDo {
	return h.Clauses(dbresolver.Write)
}

func (h helpWrapDatumDo) Session(config *gorm.Session) IHelpWrapDatumDo {
	return h.withDO(h.DO.Session(config))
}

func (h helpWrapDatumDo) Clauses(conds ...clause.Expression) IHelpWrapDatumDo {
	return h.withDO(h.DO.Clauses(conds...))
}

func (h helpWrapDatumDo) Returning(value interface{}, columns ...string) IHelpWrapDatumDo {
	return h.withDO(h.DO.Returning(value, columns...))
}

func (h helpWrapDatumDo) Not(conds ...gen.Condition) IHelpWrapDatumDo {
	return h.withDO(h.DO.Not(conds...))
}

func (h helpWrapDatumDo) Or(conds ...gen.Condition) IHelpWrapDatumDo {
	return h.withDO(h.DO.Or(conds...))
}

func (h helpWrapDatumDo) Select(conds ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Select(conds...))
}

func (h helpWrapDatumDo) Where(conds ...gen.Condition) IHelpWrapDatumDo {
	return h.withDO(h.DO.Where(conds...))
}

func (h helpWrapDatumDo) Order(conds ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Order(conds...))
}

func (h helpWrapDatumDo) Distinct(cols ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Distinct(cols...))
}

func (h helpWrapDatumDo) Omit(cols ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Omit(cols...))
}

func (h helpWrapDatumDo) Join(table schema.Tabler, on ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Join(table, on...))
}

func (h helpWrapDatumDo) LeftJoin(table schema.Tabler, on ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.LeftJoin(table, on...))
}

func (h helpWrapDatumDo) RightJoin(table schema.Tabler, on ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.RightJoin(table, on...))
}

func (h helpWrapDatumDo) Group(cols ...field.Expr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Group(cols...))
}

func (h helpWrapDatumDo) Having(conds ...gen.Condition) IHelpWrapDatumDo {
	return h.withDO(h.DO.Having(conds...))
}

func (h helpWrapDatumDo) Limit(limit int) IHelpWrapDatumDo {
	return h.withDO(h.DO.Limit(limit))
}

func (h helpWrapDatumDo) Offset(offset int) IHelpWrapDatumDo {
	return h.withDO(h.DO.Offset(offset))
}

func (h helpWrapDatumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IHelpWrapDatumDo {
	return h.withDO(h.DO.Scopes(funcs...))
}

func (h helpWrapDatumDo) Unscoped() IHelpWrapDatumDo {
	return h.withDO(h.DO.Unscoped())
}

func (h helpWrapDatumDo) Create(values ...*model.HelpWrapDatum) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Create(values)
}

func (h helpWrapDatumDo) CreateInBatches(values []*model.HelpWrapDatum, batchSize int) error {
	return h.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (h helpWrapDatumDo) Save(values ...*model.HelpWrapDatum) error {
	if len(values) == 0 {
		return nil
	}
	return h.DO.Save(values)
}

func (h helpWrapDatumDo) First() (*model.HelpWrapDatum, error) {
	if result, err := h.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelpWrapDatum), nil
	}
}

func (h helpWrapDatumDo) Take() (*model.HelpWrapDatum, error) {
	if result, err := h.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelpWrapDatum), nil
	}
}

func (h helpWrapDatumDo) Last() (*model.HelpWrapDatum, error) {
	if result, err := h.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelpWrapDatum), nil
	}
}

func (h helpWrapDatumDo) Find() ([]*model.HelpWrapDatum, error) {
	result, err := h.DO.Find()
	return result.([]*model.HelpWrapDatum), err
}

func (h helpWrapDatumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.HelpWrapDatum, err error) {
	buf := make([]*model.HelpWrapDatum, 0, batchSize)
	err = h.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (h helpWrapDatumDo) FindInBatches(result *[]*model.HelpWrapDatum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return h.DO.FindInBatches(result, batchSize, fc)
}

func (h helpWrapDatumDo) Attrs(attrs ...field.AssignExpr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Attrs(attrs...))
}

func (h helpWrapDatumDo) Assign(attrs ...field.AssignExpr) IHelpWrapDatumDo {
	return h.withDO(h.DO.Assign(attrs...))
}

func (h helpWrapDatumDo) Joins(fields ...field.RelationField) IHelpWrapDatumDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Joins(_f))
	}
	return &h
}

func (h helpWrapDatumDo) Preload(fields ...field.RelationField) IHelpWrapDatumDo {
	for _, _f := range fields {
		h = *h.withDO(h.DO.Preload(_f))
	}
	return &h
}

func (h helpWrapDatumDo) FirstOrInit() (*model.HelpWrapDatum, error) {
	if result, err := h.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelpWrapDatum), nil
	}
}

func (h helpWrapDatumDo) FirstOrCreate() (*model.HelpWrapDatum, error) {
	if result, err := h.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.HelpWrapDatum), nil
	}
}

func (h helpWrapDatumDo) FindByPage(offset int, limit int) (result []*model.HelpWrapDatum, count int64, err error) {
	result, err = h.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = h.Offset(-1).Limit(-1).Count()
	return
}

func (h helpWrapDatumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = h.Count()
	if err != nil {
		return
	}

	err = h.Offset(offset).Limit(limit).Scan(result)
	return
}

func (h helpWrapDatumDo) Scan(result interface{}) (err error) {
	return h.DO.Scan(result)
}

func (h helpWrapDatumDo) Delete(models ...*model.HelpWrapDatum) (result gen.ResultInfo, err error) {
	return h.DO.Delete(models)
}

func (h *helpWrapDatumDo) withDO(do gen.Dao) *helpWrapDatumDo {
	h.DO = *do.(*gen.DO)
	return h
}
