// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDtbIslotSyncOrdersTime = "dtb_islot_sync_orders_time"

// DtbIslotSyncOrdersTime mapped from table <dtb_islot_sync_orders_time>
type DtbIslotSyncOrdersTime struct {
	ID           int32     `gorm:"column:id;type:smallint(6);primaryKey" json:"id"`
	LastSyncTime time.Time `gorm:"column:last_sync_time;type:datetime;not null" json:"last_sync_time"`
}

// TableName DtbIslotSyncOrdersTime's table name
func (*DtbIslotSyncOrdersTime) TableName() string {
	return TableNameDtbIslotSyncOrdersTime
}
