// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbUserDeviceinfo = "dtb_user_deviceinfo"

// DtbUserDeviceinfo 用户设备信息
type DtbUserDeviceinfo struct {
	ID         uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:ID" json:"id"`                // ID
	UID        uint32  `gorm:"column:uid;type:int(11) unsigned;not null;index:uid,priority:1;comment:用户ID" json:"uid"`            // 用户ID
	DeviceInfo *string `gorm:"column:device_info;type:varchar(100);index:device_info,priority:1;comment:设备信息" json:"device_info"` // 设备信息
	RegTime    *uint32 `gorm:"column:reg_time;type:int(11) unsigned;comment:注册时间" json:"reg_time"`                                // 注册时间
	DeviceType *uint32 `gorm:"column:device_type;type:int(11) unsigned;comment:设备种类" json:"device_type"`                          // 设备种类
	ClientType *uint32 `gorm:"column:client_type;type:int(11) unsigned;comment:客户种类" json:"client_type"`                          // 客户种类
}

// TableName DtbUserDeviceinfo's table name
func (*DtbUserDeviceinfo) TableName() string {
	return TableNameDtbUserDeviceinfo
}
