// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDtbLamp = "dtb_lamp"

// DtbLamp 跑马灯信息数据表
type DtbLamp struct {
	ID          int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:主键id" json:"id"`                              // 主键id
	PlayNum     *int32 `gorm:"column:play_num;type:int(11);not null;default:1;comment:播放次数" json:"play_num"`                             // 播放次数
	Content     string `gorm:"column:content;type:varchar(300);not null;comment:跑马灯内容" json:"content"`                                   // 跑马灯内容
	PublicType  *int32 `gorm:"column:public_type;type:tinyint(4);not null;default:1;comment:发布时间类型:1即时;2定时" json:"public_type"`          // 发布时间类型:1即时;2定时
	PublicTime  int32  `gorm:"column:public_time;type:int(11);not null;comment:发布时间" json:"public_time"`                                 // 发布时间
	CreatedTime int32  `gorm:"column:created_time;type:int(11);not null;comment:创建时间" json:"created_time"`                               // 创建时间
	UpdatedTime int32  `gorm:"column:updated_time;type:int(11);not null;comment:修改时间" json:"updated_time"`                               // 修改时间
	Status      int32  `gorm:"column:status;type:tinyint(4);not null;index:status,priority:1;comment:跑马灯状态:1已发布;0未发布,2撤回" json:"status"` // 跑马灯状态:1已发布;0未发布,2撤回
}

// TableName DtbLamp's table name
func (*DtbLamp) TableName() string {
	return TableNameDtbLamp
}
