// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameIncomeRatioTemplateInfo = "income_ratio_template_info"

// IncomeRatioTemplateInfo 比率模板数据
type IncomeRatioTemplateInfo struct {
	ID         int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name       *string `gorm:"column:name;type:varchar(255);uniqueIndex:unique_name,priority:1;comment:模板名称" json:"name"`                    // 模板名称
	Content    string  `gorm:"column:content;type:text;not null;comment:json串，比例详情" json:"content"`                                          // json串，比例详情
	State      *uint32 `gorm:"column:state;type:int(11) unsigned;comment:状态 0关闭, 1开启" json:"state"`                                          // 状态 0关闭, 1开启
	CreateTime *uint64 `gorm:"column:create_time;type:bigint(20) unsigned;index:idx_create_time,priority:1;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime *int64  `gorm:"column:update_time;type:bigint(20);comment:更新时间" json:"update_time"`                                           // 更新时间
}

// TableName IncomeRatioTemplateInfo's table name
func (*IncomeRatioTemplateInfo) TableName() string {
	return TableNameIncomeRatioTemplateInfo
}
