// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMemePropsInfo = "meme_props_info"

// MemePropsInfo 道具信息表
type MemePropsInfo struct {
	ID         uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true;comment:道具id" json:"id"`      // 道具id
	Img        *string `gorm:"column:img;type:varchar(256);comment:道具图片" json:"img"`                                      // 道具图片
	Amount     *int32  `gorm:"column:amount;type:int(11);comment:价格" json:"amount"`                                       // 价格
	Total      *int32  `gorm:"column:total;type:int(11);comment:现有数量" json:"total"`                                       // 现有数量
	Fee        *int64  `gorm:"column:fee;type:bigint(20);comment:服务费" json:"fee"`                                         // 服务费
	PropsDesc  *string `gorm:"column:props_desc;type:text;comment:描述" json:"props_desc"`                                  // 描述
	Name       *string `gorm:"column:name;type:varchar(128);comment:道具名" json:"name"`                                     // 道具名
	CreateTime *int64  `gorm:"column:create_time;type:bigint(20);comment:创建时间" json:"create_time"`                        // 创建时间
	UpdateTime *int64  `gorm:"column:update_time;type:bigint(20);comment:创建时间" json:"update_time"`                        // 创建时间
	Status     *int32  `gorm:"column:status;type:int(11);comment:状态 0 :使用 1:隐藏" json:"status"`                            // 状态 0 :使用 1:隐藏
	Extra      *string `gorm:"column:extra;type:varchar(255);comment:增发信息,{"min_amount":0,"incr_amount":0}" json:"extra"` // 增发信息,{"min_amount":0,"incr_amount":0}
}

// TableName MemePropsInfo's table name
func (*MemePropsInfo) TableName() string {
	return TableNameMemePropsInfo
}
