// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePkOrder = "pk_order"

// PkOrder 后台订单表
type PkOrder struct {
	ID           int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true;comment:id" json:"id"`               // id
	UID          uint32  `gorm:"column:uid;type:int(11) unsigned;not null;comment:用户id" json:"uid"`                       // 用户id
	Aid          uint32  `gorm:"column:aid;type:int(11) unsigned;not null;comment:操作人id" json:"aid"`                      // 操作人id
	AdminID      uint32  `gorm:"column:admin_id;type:int(11) unsigned;not null;comment:审核人id" json:"admin_id"`            // 审核人id
	Type         *bool   `gorm:"column:type;type:tinyint(1);not null;default:1;comment:类型 1增加 2减少" json:"type"`           // 类型 1增加 2减少
	Status       *bool   `gorm:"column:status;type:tinyint(1);not null;default:1;comment:状态 0草稿箱 1审核中 2通过" json:"status"` // 状态 0草稿箱 1审核中 2通过
	BeforeAmount *uint32 `gorm:"column:before_amount;type:int(11) unsigned;comment:金币变化前" json:"before_amount"`           // 金币变化前
	OpAmount     *uint32 `gorm:"column:op_amount;type:int(11) unsigned;comment:增加的金币" json:"op_amount"`                   // 增加的金币
	AfterAmount  *uint32 `gorm:"column:after_amount;type:int(11) unsigned;comment:金币变化后" json:"after_amount"`             // 金币变化后
	Remark       *string `gorm:"column:remark;type:varchar(255);comment:订单备注" json:"remark"`                              // 订单备注
	CreateTime   uint32  `gorm:"column:create_time;type:int(11) unsigned;not null;comment:创建时间" json:"create_time"`       // 创建时间
	UpdateTime   uint32  `gorm:"column:update_time;type:int(11) unsigned;not null;comment:修改时间" json:"update_time"`       // 修改时间
}

// TableName PkOrder's table name
func (*PkOrder) TableName() string {
	return TableNamePkOrder
}
