// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportFailLog = "report_fail_log"

// ReportFailLog 上报统计服失败的表(暂时只有货币变更)
type ReportFailLog struct {
	ID         uint32    `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	ReportURL  *string   `gorm:"column:report_url;type:varchar(256);not null;default:0;comment:数据报告的地址" json:"report_url"` // 数据报告的地址
	ReportData *string   `gorm:"column:report_data;type:text;comment:报告包含的内容" json:"report_data"`                          // 报告包含的内容
	SynState   *int32    `gorm:"column:syn_state;type:int(11);comment:是否已经同步成功 0 默认失败 1 同步成功" json:"syn_state"`            // 是否已经同步成功 0 默认失败 1 同步成功
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;index:i_create_time,priority:1" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;index:i_aaa,priority:2" json:"update_time"`
	RetryCount *int32    `gorm:"column:retry_count;type:int(11);index:i_aaa,priority:1;comment:重试次数，超过3次不再尝试" json:"retry_count"` // 重试次数，超过3次不再尝试
}

// TableName ReportFailLog's table name
func (*ReportFailLog) TableName() string {
	return TableNameReportFailLog
}
