// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTProxyIncome = "t_proxy_income"

// TProxyIncome mapped from table <t_proxy_income>
type TProxyIncome struct {
	UID  int32   `gorm:"column:uid;type:int(11);primaryKey" json:"uid"`
	Data *string `gorm:"column:data;type:text;comment:总代收益" json:"data"` // 总代收益
}

// TableName TProxyIncome's table name
func (*TProxyIncome) TableName() string {
	return TableNameTProxyIncome
}
