// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTProxyIncomeDetail = "t_proxy_income_detail"

// TProxyIncomeDetail mapped from table <t_proxy_income_detail>
type TProxyIncomeDetail struct {
	ID            uint32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	ProxyID       *uint32 `gorm:"column:proxy_id;type:int(11) unsigned;comment:收入所属代理" json:"proxy_id"`     // 收入所属代理
	Fee           *uint64 `gorm:"column:fee;type:bigint(20) unsigned;comment:服务费收入" json:"fee"`             // 服务费收入
	Insurance     *int64  `gorm:"column:insurance;type:bigint(20);comment:保险收入" json:"insurance"`           // 保险收入
	Jackpot       *uint64 `gorm:"column:jackpot;type:bigint(20) unsigned;comment:jackpot收入" json:"jackpot"` // jackpot收入
	Total         *int64  `gorm:"column:total;type:bigint(20);comment:当前总值" json:"total"`                   // 当前总值
	Roomuuid      *uint64 `gorm:"column:roomuuid;type:bigint(20) unsigned;index:roomuuid_index,priority:1" json:"roomuuid"`
	CroomTime     *uint32 `gorm:"column:croomTime;type:int(11) unsigned;comment:房间创建时间" json:"croomTime"`                                     // 房间创建时间
	StartTime     *uint32 `gorm:"column:startTime;type:int(11) unsigned;comment:开始时间" json:"startTime"`                                       // 开始时间
	IncomeTime    *uint32 `gorm:"column:incomeTime;type:int(11) unsigned;index:incomeTime_index,priority:1;comment:邀请收入日期" json:"incomeTime"` // 邀请收入日期
	Mode          *int32  `gorm:"column:mode;type:int(11)" json:"mode"`
	Ante          *int64  `gorm:"column:ante;type:bigint(20)" json:"ante"`
	RuleBlindEnum *int32  `gorm:"column:rule_blind_enum;type:int(11)" json:"rule_blind_enum"`
}

// TableName TProxyIncomeDetail's table name
func (*TProxyIncomeDetail) TableName() string {
	return TableNameTProxyIncomeDetail
}
