// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTRedbagmCache = "t_redbagm_cache"

// TRedbagmCache mapped from table <t_redbagm_cache>
type TRedbagmCache struct {
	ID               uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	LastMaxID        uint32 `gorm:"column:last_max_id;type:int(11) unsigned;not null" json:"last_max_id"`
	HistoryLastMaxID uint32 `gorm:"column:history_last_max_id;type:int(11) unsigned;not null" json:"history_last_max_id"`
}

// TableName TRedbagmCache's table name
func (*TRedbagmCache) TableName() string {
	return TableNameTRedbagmCache
}
