// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTRedbagHistory = "t_redbag_history"

// TRedbagHistory mapped from table <t_redbag_history>
type TRedbagHistory struct {
	ID          uint32 `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	UID         uint32 `gorm:"column:uid;type:int(11) unsigned;not null;index:index_uid,priority:1;comment:中奖者uid" json:"uid"` // 中奖者uid
	Name        string `gorm:"column:name;type:varchar(50);not null;comment:中奖者名称" json:"name"`                                // 中奖者名称
	HeadURL     string `gorm:"column:head_url;type:char(255);not null;comment:中奖者头像" json:"head_url"`                          // 中奖者头像
	RedbagID    uint32 `gorm:"column:redbag_id;type:int(11) unsigned;not null;comment:红包id" json:"redbag_id"`                  // 红包id
	DrawTime    uint64 `gorm:"column:draw_time;type:bigint(20) unsigned;not null;comment:抽中时间" json:"draw_time"`               // 抽中时间
	DrawAmount  uint64 `gorm:"column:draw_amount;type:bigint(20) unsigned;not null;comment:抽中金额" json:"draw_amount"`           // 抽中金额
	BoomAmount  uint64 `gorm:"column:boom_amount;type:bigint(20) unsigned;not null;comment:中雷金额" json:"boom_amount"`           // 中雷金额
	JpAmount    uint64 `gorm:"column:jp_amount;type:bigint(20) unsigned;not null;comment:jp金额" json:"jp_amount"`               // jp金额
	AmountLevel *int64 `gorm:"column:amount_level;type:bigint(20);comment:红包级别" json:"amount_level"`                           // 红包级别
	JpContrib   *int64 `gorm:"column:jp_contrib;type:bigint(20);comment:jp贡献额" json:"jp_contrib"`                              // jp贡献额
}

// TableName TRedbagHistory's table name
func (*TRedbagHistory) TableName() string {
	return TableNameTRedbagHistory
}
